/** Shared HTML document for build-time and request-time React rendering. */
import type { CSSProperties, ReactElement, ReactNode } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import {
  ACCENT_ATTRIBUTE,
  ACCENT_NONE_VALUE,
  type AppearanceProjection,
} from "discern-design-system";
import {
  designSystemAssetPath,
  type DesignSystemBundleName,
} from "../design_system.ts";
import { SITE_APPEARANCE, siteAppearanceDeclarations } from "../appearance.ts";
import { DISCERN_FAVICON_PATH } from "../brand.ts";
import { THEME_BOOTSTRAP, THEME_ROOT_ATTRIBUTES } from "../theme.ts";
import { HtmlFragment } from "./components/HtmlFragment.tsx";

/** The browser chrome colour beside each emitted theme. */
const THEME_COLORS = { light: "#F7F5F8", dark: "#22252C" } as const;

export interface DocumentProps {
  readonly source?: string;
  readonly sourceComment?: string;
  readonly title: string;
  readonly description: string;
  readonly appearance?: AppearanceProjection;
  readonly bundle?: DesignSystemBundleName;
  /** Files emitted into the selected design-system bundle. */
  readonly styles: readonly string[];
  readonly scripts: readonly string[];
  /** Repository-authored stylesheets under `/assets`, linked after the bundle's. */
  readonly siteStyles?: readonly string[];
  /** Repository-authored ES modules under `/assets`, loaded after the bundle's. */
  readonly siteModules?: readonly string[];
  /** Head content that must resolve before the first stylesheet, such as an enhancement class. */
  readonly head?: ReactNode;
  readonly bodyClassName?: string;
  readonly children: ReactNode;
}

/** Render the shared theme, metadata, and asset contract around page components. */
export function Document(
  {
    title,
    description,
    appearance = "accent",
    bundle = "compositions",
    styles,
    scripts,
    siteStyles = [],
    siteModules = [],
    head,
    bodyClassName,
    children,
  }: DocumentProps,
): ReactElement {
  const appearanceStyle: CSSProperties & Record<`--discern-${string}`, number> =
    siteAppearanceDeclarations(appearance);
  return (
    <html
      lang="en"
      {...SITE_APPEARANCE.rootAttributes}
      {...{
        [ACCENT_ATTRIBUTE]: appearance === "mono" ? ACCENT_NONE_VALUE : "",
      }}
      style={appearanceStyle}
      {...THEME_ROOT_ATTRIBUTES}
    >
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta
          name="theme-color"
          content={THEME_COLORS.light}
          media="(prefers-color-scheme: light)"
        />
        <meta
          name="theme-color"
          content={THEME_COLORS.dark}
          media="(prefers-color-scheme: dark)"
        />
        <link rel="icon" href={DISCERN_FAVICON_PATH} />
        <HtmlFragment as="script" html={THEME_BOOTSTRAP} />
        {head}
        {styles.map((file) => (
          <link
            key={file}
            rel="stylesheet"
            href={designSystemAssetPath(bundle, file)}
          />
        ))}
        {siteStyles.map((href) => (
          <link key={href} rel="stylesheet" href={href} />
        ))}
        {scripts.map((file) => (
          <script
            key={file}
            type="module"
            defer
            src={designSystemAssetPath(bundle, file)}
          >
          </script>
        ))}
        {siteModules.map((src) => (
          <script key={src} type="module" src={src}></script>
        ))}
      </head>
      <body className={bodyClassName}>{children}</body>
    </html>
  );
}

/** Serialize a complete document; generated files retain their authoring source. */
export function renderDocument(props: DocumentProps): string {
  const marker = props.source === undefined
    ? ""
    : `<!-- Generated by site/build.ts from ${props.source}. Do not edit. -->\n`;
  const note = props.sourceComment === undefined
    ? ""
    : `<!-- ${props.sourceComment} -->\n`;
  return `<!doctype html>\n${marker}${note}${
    renderToStaticMarkup(<Document {...props} />)
  }`;
}
