/** Shared HTML document for build-time and request-time React rendering. */
import type { CSSProperties, ReactElement, ReactNode } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import {
  ACCENT_ATTRIBUTE,
  ACCENT_NONE_VALUE,
  type AppearanceProjection,
} from "discern-design-system";
import {
  designSystemAssetPath,
  type DesignSystemBundleName,
} from "../design_system.ts";
import { SITE_APPEARANCE } from "../appearance.ts";
import { DISCERN_FAVICON_PATH } from "../brand.ts";
import { THEME_BOOTSTRAP, THEME_ROOT_ATTRIBUTES } from "../theme.ts";
import { HtmlFragment } from "./components/HtmlFragment.tsx";

export interface DocumentProps {
  readonly source?: string;
  readonly sourceComment?: string;
  readonly title: string;
  readonly description: string;
  readonly appearance?: AppearanceProjection;
  readonly bundle?: DesignSystemBundleName;
  readonly styles: readonly string[];
  readonly scripts: readonly string[];
  readonly bodyClassName?: string;
  readonly children: ReactNode;
}

/** Render the shared theme, metadata, and asset contract around page components. */
export function Document(
  {
    title,
    description,
    appearance = "accent",
    bundle = "compositions",
    styles,
    scripts,
    bodyClassName,
    children,
  }: DocumentProps,
): ReactElement {
  const accentStyle:
    & CSSProperties
    & Record<typeof SITE_APPEARANCE.accentHueProperty, number> = {
      [SITE_APPEARANCE.accentHueProperty]: SITE_APPEARANCE.accentHue,
    };
  return (
    <html
      lang="en"
      {...SITE_APPEARANCE.rootAttributes}
      {...{
        [ACCENT_ATTRIBUTE]: appearance === "mono" ? ACCENT_NONE_VALUE : "",
      }}
      style={appearance === "mono" ? undefined : accentStyle}
      {...THEME_ROOT_ATTRIBUTES}
    >
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="theme-color" content="#F7F5F8" />
        <link rel="icon" href={DISCERN_FAVICON_PATH} />
        <HtmlFragment as="script" html={THEME_BOOTSTRAP} />
        {styles.map((file) => (
          <link
            key={file}
            rel="stylesheet"
            href={designSystemAssetPath(bundle, file)}
          />
        ))}
        {scripts.map((file) => (
          <script
            key={file}
            type="module"
            defer
            src={designSystemAssetPath(bundle, file)}
          >
          </script>
        ))}
      </head>
      <body className={bodyClassName}>{children}</body>
    </html>
  );
}

/** Serialize a complete document; generated files retain their authoring source. */
export function renderDocument(props: DocumentProps): string {
  const marker = props.source === undefined
    ? ""
    : `<!-- Generated by site/build.ts from ${props.source}. Do not edit. -->\n`;
  const note = props.sourceComment === undefined
    ? ""
    : `<!-- ${props.sourceComment} -->\n`;
  return `<!doctype html>\n${marker}${note}${
    renderToStaticMarkup(<Document {...props} />)
  }`;
}
