/**
 * The environment-neutral documentation search projection.
 *
 * A surface decides which documents its audience may see and prepares the
 * Markdown edition it wants searched. This module turns those admitted sources
 * into the field-separated records consumed by the shared matcher in
 * `docs_search.js`. The browser site, `discern map`, and `discern help` therefore
 * share extraction and ranking without sharing audience policy.
 */

import type { DocEntry } from "./docs.ts";
import { parseFrontmatter } from "./frontmatter.ts";
import { inlineToPlain, renderMarkdownHtml } from "./markdown.ts";

/** One route or canonical target eligible to contribute to a search index. */
export interface SearchSource {
  route: string;
  section: string;
  entry: DocEntry;
}

/** One searchable heading and its destination fragment. */
export interface SearchHeading {
  id: string;
  text: string;
}

/** One search record. Field separation preserves rank weights. */
export interface SearchPage {
  route: string;
  title: string;
  section: string;
  description: string;
  aliases: string[];
  headings: SearchHeading[];
  codeTerms: string[];
  body: string;
}

/** A complete search index for a surface-specific admitted corpus. */
export interface SearchIndex {
  pages: SearchPage[];
}

/** Render the tracked browser module from the authored shared matcher. */
export function renderBrowserSearchModule(source: string): string {
  return "/* GENERATED by `deno task codegen` from src/lib/docs_search.js. " +
    "Do not edit. */\n" + source;
}

/** Flatten Markdown to readable search prose while retaining literal terms. */
export function markdownSearchText(markdown: string): string {
  const lines: string[] = [];
  let inFence = false;
  for (const raw of markdown.split(/\r?\n/)) {
    if (/^\s*(```|~~~)/.test(raw)) {
      inFence = !inFence;
      continue;
    }
    // Headings are indexed as their own higher-weight fields. Repeating them
    // in the body would add bytes without adding recall.
    if (!inFence && /^\s{0,3}#{1,6}\s+/.test(raw)) {
      continue;
    }
    const withoutBlockSyntax = inFence ? raw : raw
      .replace(/^\s*>\s?/, "")
      .replace(/^\s*(?:[-+*]|\d+[.)])\s+/, "")
      .replace(/^\s*\|?\s*:?-{3,}:?(?:\s*\|\s*:?-{3,}:?)+\s*\|?\s*$/, "")
      .replace(/\s*\|\s*/g, " ");
    const plain = inlineToPlain(withoutBlockSyntax)
      .replace(/\s+/g, " ")
      .trim();
    if (plain !== "") lines.push(plain);
  }
  return lines.join(" ");
}

/** Extract fenced and inline code as a distinct, higher-weight search field. */
export function markdownCodeTerms(markdown: string): string[] {
  const terms: string[] = [];
  let fence: string[] | undefined;
  for (const raw of markdown.split(/\r?\n/)) {
    if (/^\s*(```|~~~)/.test(raw)) {
      if (fence === undefined) {
        fence = [];
      } else {
        const block = fence.join(" ").replace(/\s+/g, " ").trim();
        if (block !== "") terms.push(block);
        fence = undefined;
      }
      continue;
    }
    if (fence !== undefined) {
      fence.push(raw);
      continue;
    }
    for (const match of raw.matchAll(/`+([^`]+?)`+/g)) {
      const term = match[1]?.replace(/\s+/g, " ").trim();
      if (term) terms.push(term);
    }
  }
  if (fence !== undefined) {
    const block = fence.join(" ").replace(/\s+/g, " ").trim();
    if (block !== "") terms.push(block);
  }
  return [...new Set(terms)];
}

/** Build one search record from the Markdown edition a surface supplies. */
export function searchPageFromMarkdown(
  source: SearchSource,
  markdown: string,
): SearchPage {
  const { body } = parseFrontmatter(markdown);
  const rendered = renderMarkdownHtml(body);
  return {
    route: source.route,
    title: source.entry.title,
    section: source.section,
    description: source.entry.description,
    aliases: source.entry.aliases,
    headings: rendered.headings
      .filter((heading) => heading.depth >= 2)
      .map((heading) => ({ id: heading.id, text: heading.text })),
    codeTerms: markdownCodeTerms(body),
    body: markdownSearchText(body),
  };
}
