// GENERATED by scripts/codegen.ts from release records. Do not edit.
import denoJson from "../../deno.json" with { type: "json" };

export const RELEASE_METADATA: { version: string; codename?: string } = {
  version: denoJson.version,
  codename: "Watershed",
};
