/**
 * The one HTML skeleton shared by every generated static page: doctype,
 * theme bootstrap, favicon, metadata, and the compositions-bundle asset
 * links. Page renderers supply body markup and name their own assets.
 */

import { designSystemAssetPath } from "../design_system.ts";
import { DISCERN_FAVICON_PATH } from "../brand.ts";

/** Applies the stored or preferred theme before first paint. */
export const THEME_BOOTSTRAP =
  `(function(){try{var t=localStorage.getItem("discern-theme");if(t==="dark"||(!t&&matchMedia("(prefers-color-scheme: dark)").matches)){document.documentElement.dataset.discernTheme="dark"}}catch(_){}})();`;

export interface PageDocument {
  /** The page-src file the output is generated from, for the marker comment. */
  readonly source: string;
  readonly title: string;
  readonly description: string;
  /** Compositions-bundle stylesheet files, in load order. */
  readonly styles: readonly string[];
  /** Compositions-bundle deferred script files. */
  readonly scripts: readonly string[];
  /** Rendered static body markup. */
  readonly body: string;
}

/** Wrap rendered body markup in the complete static document. */
export function pageDocument(page: PageDocument): string {
  const styles = page.styles.map((file) =>
    `<link rel="stylesheet" href="${
      designSystemAssetPath("compositions", file)
    }" />`
  ).join("\n");
  const scripts = page.scripts.map((file) =>
    `<script defer src="${
      designSystemAssetPath("compositions", file)
    }"></script>`
  ).join("\n");
  return `<!doctype html>
<!-- Generated by site/build.ts from site/page-src/${page.source}. Do not edit. -->
<html lang="en" data-discern-root data-discern-theme="light">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${page.title}</title>
<meta name="description" content="${page.description}" />
<meta name="theme-color" content="#F7F5F8" />
<link rel="icon" href="${DISCERN_FAVICON_PATH}" />
<script>${THEME_BOOTSTRAP}</script>
${styles}
${scripts}
</head>
<body>
${page.body}
</body>
</html>
`;
}
