/**
 * The one HTML skeleton shared by every generated static page: doctype,
 * theme bootstrap, favicon, metadata, and the compositions-bundle asset
 * links. Page renderers supply body markup and name their own assets.
 */

import { designSystemAssetPath } from "../design_system.ts";
import { DISCERN_FAVICON_PATH } from "../brand.ts";
import {
  THEME_BOOTSTRAP,
  THEME_SCRIPT_PATH,
  THEME_STYLESHEET_PATH,
} from "../theme.ts";

export interface PageDocument {
  /** The page-src file the output is generated from, for the marker comment. */
  readonly source: string;
  /** Optional source-level note placed beside the generated-file marker. */
  readonly sourceComment?: string;
  readonly title: string;
  readonly description: string;
  /** Compositions-bundle stylesheet files, in load order. */
  readonly styles: readonly string[];
  /** Compositions-bundle deferred ECMAScript module files. */
  readonly scripts: readonly string[];
  /** Rendered static body markup. */
  readonly body: string;
}

/** Wrap rendered body markup in the complete static document. */
export function pageDocument(page: PageDocument): string {
  const styles = page.styles.map((file) =>
    `<link rel="stylesheet" href="${
      designSystemAssetPath("compositions", file)
    }" />`
  ).join("\n");
  const scripts = page.scripts.map((file) =>
    `<script type="module" defer src="${
      designSystemAssetPath("compositions", file)
    }"></script>`
  ).join("\n");
  const sourceComment = page.sourceComment === undefined
    ? ""
    : `\n<!-- ${page.sourceComment} -->`;
  return `<!doctype html>
<!-- Generated by site/build.ts from site/page-src/${page.source}. Do not edit. -->${sourceComment}
<html lang="en" data-discern-root data-discern-theme="light">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${page.title}</title>
<meta name="description" content="${page.description}" />
<meta name="theme-color" content="#F7F5F8" />
<link rel="icon" href="${DISCERN_FAVICON_PATH}" />
<script>${THEME_BOOTSTRAP}</script>
${styles}
<link rel="stylesheet" href="${THEME_STYLESHEET_PATH}" />
<script defer src="${THEME_SCRIPT_PATH}"></script>
${scripts}
</head>
<body>
${page.body}
</body>
</html>
`;
}
