/**
 * The design-system demo's permanent boundary: authored sources generate the
 * committed static artifact deterministically, component additions auto-enrol,
 * and the browser-facing page remains local-asset-only with no React runtime.
 */

import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { encodeHex } from "@std/encoding/hex";
import { fromFileUrl, join, toFileUrl } from "@std/path";
import { buildDesignSystemRuntime } from "../scripts/build.ts";
import { renderDesignSystemDemo } from "../../page-src/design-system-demo.tsx";
import { formatGeneratedText } from "../../page-src/format-generated.ts";

const ROOT = fromFileUrl(new URL("../../../", import.meta.url));
const PUBLIC_ROOT = join(ROOT, "site", "pages", "assets", "design-system");
const COMPONENT_ROOT = join(ROOT, "site", "design-system", "src", "components");

async function walk(directory: string): Promise<string[]> {
  const files: string[] = [];
  for await (const entry of Deno.readDir(directory)) {
    const path = join(directory, entry.name);
    if (entry.isDirectory) files.push(...await walk(path));
    else files.push(path);
  }
  return files;
}

async function sha256(path: string): Promise<string> {
  const bytes = await Deno.readFile(path);
  return encodeHex(await crypto.subtle.digest("SHA-256", bytes));
}

Deno.test("design-system sources deterministically reproduce every committed runtime asset", async () => {
  const temp = await Deno.makeTempDir();
  try {
    const summary = await buildDesignSystemRuntime(toFileUrl(`${temp}/`));
    for (
      const relative of [
        "discern.css",
        "manifest.json",
        join("textures", "grain.png"),
      ]
    ) {
      assertEquals(
        await sha256(join(temp, relative)),
        await sha256(join(PUBLIC_ROOT, relative)),
        relative,
      );
    }

    const generatedPage = await Deno.readTextFile(
      join(ROOT, "site", "pages", "design-system-demo.html"),
    );
    assertEquals(
      generatedPage,
      await formatGeneratedText(renderDesignSystemDemo(summary), "html"),
    );
  } finally {
    await Deno.remove(temp, { recursive: true });
  }

  for (
    const [source, output] of [
      ["design-system-demo.css", "demo.css"],
      ["design-system-demo.js", "demo.js"],
      ["design-system-fonts.css", "fonts.css"],
    ] as const
  ) {
    const authored = await Deno.readTextFile(
      join(ROOT, "site", "page-src", source),
    );
    const generated = await Deno.readTextFile(join(PUBLIC_ROOT, output));
    assertEquals(
      generated,
      `/* Generated by site/build.ts from site/page-src/${source}. Do not edit. */\n${authored}`,
      output,
    );
  }
});

Deno.test("every design-system component auto-enrols its implementation surfaces", async () => {
  const files = await walk(COMPONENT_ROOT);
  const fileSet = new Set(files);
  const metaFiles = files.filter((path) => path.endsWith(".meta.ts"));
  assert(metaFiles.length > 0);

  const publicModule = await Deno.readTextFile(
    join(ROOT, "site", "design-system", "src", "mod.ts"),
  );
  for (const meta of metaFiles) {
    const stem = meta.slice(0, -".meta.ts".length);
    const directory = stem.slice(0, stem.lastIndexOf("/"));
    for (
      const sibling of [`${stem}.tsx`, `${stem}.css`, `${stem}.examples.tsx`]
    ) {
      assert(fileSet.has(sibling), `${meta} is missing ${sibling}`);
    }
    assert(fileSet.has(join(directory, "mod.ts")), `${meta} is missing mod.ts`);

    const componentRelative = directory.slice(COMPONENT_ROOT.length + 1);
    assertStringIncludes(
      publicModule,
      `./components/${componentRelative}/mod.ts`,
      `${componentRelative} is missing from src/mod.ts`,
    );
  }

  for (const path of files.filter((file) => /\.(?:css|tsx?|js)$/.test(file))) {
    const source = await Deno.readTextFile(path);
    assert(!/https?:\/\//.test(source), `${path} contains a remote asset URL`);
  }
});

Deno.test("the public demo ships static HTML and local runtime assets only", async () => {
  const html = await Deno.readTextFile(
    join(ROOT, "site", "pages", "design-system-demo.html"),
  );
  assertStringIncludes(html, "data-ds-root");
  assertStringIncludes(
    html,
    "typed React at build time · static HTML at runtime",
  );

  const runtimeRefs = [...html.matchAll(/(?:src|href)="([^"]+)"/g)]
    .map((match) => match[1] ?? "")
    .filter((value) => !value.startsWith("#") && !value.startsWith("data:"));
  assert(
    runtimeRefs.every((value) => value.startsWith("/")),
    `remote runtime references: ${runtimeRefs.join(", ")}`,
  );
  assertEquals(
    runtimeRefs.filter((value) => value.endsWith(".js")),
    ["/assets/design-system/demo.js"],
  );

  for (const asset of ["discern.css", "demo.css", "fonts.css"]) {
    const css = await Deno.readTextFile(join(PUBLIC_ROOT, asset));
    assert(!/https?:\/\//.test(css), `${asset} contains a remote URL`);
  }

  const manifest = JSON.parse(
    await Deno.readTextFile(join(PUBLIC_ROOT, "manifest.json")),
  ) as Record<string, unknown>;
  assertEquals("generatedAt" in manifest, false);
});

Deno.test("self-hosted font binaries carry their open-font licences", async () => {
  const fonts = await walk(join(PUBLIC_ROOT, "fonts"));
  assertEquals(fonts.length, 5);
  for (const font of fonts) {
    const bytes = await Deno.readFile(font);
    assertEquals(new TextDecoder().decode(bytes.slice(0, 4)), "wOF2", font);
  }

  const licences = await walk(join(PUBLIC_ROOT, "licenses"));
  assertEquals(licences.length, 4);
  for (const licence of licences) {
    assertStringIncludes(
      await Deno.readTextFile(licence),
      "SIL OPEN FONT LICENSE",
    );
  }
});
