/**
 * Architectural guard for the ADR index. The configured map's ADR README is the
 * only view of the record set most readers ever open, so an ADR missing from it
 * is invisible — exactly how 0106–0109 sat unlisted for four records. The
 * canonical set is the DIRECTORY (every `NNNN-*.md` on disk), never the index
 * itself, so a new ADR auto-enrols: write the file and this guard fails until
 * the index names it.
 *
 * The maintenance itself is the SHIPPED core (`src/lib/adr_index.ts`, driven by
 * `discern refresh` and the gate's adr_index precondition) — this file is the
 * thin proof-it-bites layer over that core plus the live-repo completeness run,
 * not a second implementation.
 */

import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { dirname, join } from "@std/path";
import { adrIndexState } from "../src/lib/adr_index.ts";
import {
  type AdrRecord,
  adrRecords,
  discoverDocs,
  renderAdrIndexBlocks,
} from "../src/lib/docs.ts";
import { REPO_AUTHORED_PATHS, REPO_ROOT } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";
import { structuralGuardScope } from "./structural_guard_scope.ts";

const ADR_DIR = join(REPO_AUTHORED_PATHS.map, "_adr");

/** Discover an ADR directory through the production map reader before deriving index records. */
async function adrRecordsIn(dir: string): Promise<AdrRecord[]> {
  const tree = await discoverDocs({
    cwd: dir,
    dir,
    includeInternal: true,
  });
  assert(tree !== undefined, `ADR directory does not exist: ${dir}`);
  return adrRecords(tree.entries);
}

Deno.test("ADR index: every record on disk is linked from the README index", async () => {
  const readme = await Deno.readTextFile(join(ADR_DIR, "README.md"));
  const missing = (await adrRecordsIn(ADR_DIR))
    .map((record) => record.entry.relToDocs)
    .filter((rel) => !readme.includes(`](${rel})`));
  assert(
    missing.length === 0,
    `${REPO_AUTHORED_PATHS.mapRel}/_adr/README.md must index every record — add: ${
      missing.join(", ")
    }`,
  );
});

Deno.test("ADR index: the live repo's maintained index is current through the shipped core", async () => {
  const state = await adrIndexState(REPO_ROOT, REPO_AUTHORED_PATHS.mapRel);
  assertEquals(
    state.kind,
    "current",
    `${REPO_AUTHORED_PATHS.mapRel}/_adr/README.md is ${state.kind} — run ` +
      "`discern refresh`" +
      (state.kind === "invalid" ? `: ${state.issue}` : ""),
  );
});

Deno.test("ADR index derivation ignores stale generated-block order", async () => {
  const render = async (listed: readonly string[]): Promise<string> => {
    const dir = await Deno.makeTempDir({ prefix: "discern-adr-order-" });
    try {
      await Deno.writeTextFile(
        join(dir, "README.md"),
        [
          "# Decisions",
          "",
          "<!-- BEGIN GENERATED: current ADR records -->",
          "<!-- Generated by `discern refresh` from the ADR headings on disk. -->",
          "",
          ...listed.map((number) =>
            `- [${number.padStart(4, "0")} — stale](${
              number.padStart(4, "0")
            }-choice.md)`
          ),
          "",
          "<!-- END GENERATED: current ADR records -->",
          "",
        ].join("\n"),
      );
      await Deno.writeTextFile(
        join(dir, "0001-choice.md"),
        "# ADR 0001: First\n",
      );
      await Deno.writeTextFile(
        join(dir, "0002-choice.md"),
        "# ADR 0002: Second\n",
      );
      return (await renderAdrIndexBlocks(await adrRecordsIn(dir))).current;
    } finally {
      await Deno.remove(dir, { recursive: true });
    }
  };

  assertEquals(
    await render(["1", "2"]),
    await render(["2", "1"]),
    "identical record files must render identically regardless of stale generated order",
  );
});

Deno.test("ADR index: the rendered index is a fixed point of the map formatter", async () => {
  // The gate's fix stage runs the Markdown formatter over the map. If the
  // shipped renderer ever emitted text the formatter rewrites, refresh and
  // format would fight forever: refresh writes, format reformats, the currency
  // check flags stale again. Hold the live README (renderer output included)
  // to the formatter's canonical form.
  const path = join(ADR_DIR, "README.md");
  const readme = await Deno.readTextFile(path);
  assertEquals(
    readme,
    await canonicalGeneratedMarkdown(path, readme),
    `${REPO_AUTHORED_PATHS.mapRel}/_adr/README.md is not formatter-canonical — ` +
      "the index renderer and the map formatter disagree",
  );
});

Deno.test("control: a record the index omits reports stale, and the expected text names it", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-stale-" });
  try {
    const adrDir = join(dir, "docs", "_adr");
    await Deno.mkdir(adrDir, { recursive: true });
    await Deno.writeTextFile(
      join(adrDir, "README.md"),
      [
        "# Decisions",
        "",
        "<!-- BEGIN GENERATED: current ADR records -->",
        "<!-- Generated by `discern refresh` from the ADR headings on disk. -->",
        "",
        "<!-- END GENERATED: current ADR records -->",
        "",
      ].join("\n"),
    );
    await Deno.writeTextFile(
      join(adrDir, "0001-first-choice.md"),
      "# ADR 0001: A first choice\n",
    );
    const state = await adrIndexState(dir, "docs/");
    assertEquals(state.kind, "stale");
    assert(
      state.kind === "stale" &&
        state.expected.includes(
          "[0001 — A first choice](0001-first-choice.md)",
        ),
      "the expected index must name the unlisted record",
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("control: a README without markers is absent — the index is opt-in", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-absent-" });
  try {
    const adrDir = join(dir, "docs", "_adr");
    await Deno.mkdir(adrDir, { recursive: true });
    await Deno.writeTextFile(
      join(adrDir, "README.md"),
      "# Decisions\n\nAn authored page with no generated lists.\n",
    );
    await Deno.writeTextFile(
      join(adrDir, "0001-first-choice.md"),
      "# ADR 0001: A first choice\n",
    );
    assertEquals((await adrIndexState(dir, "docs/")).kind, "absent");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("control: a record whose heading defeats the derivation reports invalid, naming it", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-invalid-" });
  try {
    const adrDir = join(dir, "docs", "_adr");
    await Deno.mkdir(adrDir, { recursive: true });
    await Deno.writeTextFile(
      join(adrDir, "README.md"),
      [
        "<!-- BEGIN GENERATED: current ADR records -->",
        "",
        "<!-- END GENERATED: current ADR records -->",
        "",
      ].join("\n"),
    );
    await Deno.writeTextFile(
      join(adrDir, "0001-first-choice.md"),
      "# a heading with no record number\n",
    );
    const state = await adrIndexState(dir, "docs/");
    assertEquals(state.kind, "invalid");
    assert(state.kind === "invalid");
    assertEquals(state.cause, "record");
    assertStringIncludes(
      state.issue,
      "0001-first-choice.md",
      "the issue must name the offending record file",
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("control: a start marker missing its end marker reports the markers cause, not a record", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-markers-" });
  try {
    const adrDir = join(dir, "docs", "_adr");
    await Deno.mkdir(adrDir, { recursive: true });
    // The BEGIN marker survives an edit; the END marker is gone. Every record
    // file is fine — the remedy must point at the README's pair.
    await Deno.writeTextFile(
      join(adrDir, "README.md"),
      "# Decisions\n\n<!-- BEGIN GENERATED: current ADR records -->\n",
    );
    await Deno.writeTextFile(
      join(adrDir, "0001-first-choice.md"),
      "# ADR 0001: A first choice\n",
    );
    const state = await adrIndexState(dir, "docs/");
    assertEquals(state.kind, "invalid");
    assert(state.kind === "invalid");
    assertEquals(state.cause, "markers");
    assertStringIncludes(
      state.issue,
      "END GENERATED: current ADR records",
      "the issue must name the missing end marker",
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("the two shipped ADR skeletons are identical", async () => {
  // The setup skeleton and the discern-write-adr skill's skeleton both lay the
  // same `_adr/` starter (README format guide + template + seeded record) —
  // one shipped contract, two delivery paths. The setup skeleton is the
  // authored source; `deno task codegen` produces the skill's copy. This
  // byte-identity check backstops the generator: it fails when a copy is
  // edited by hand or a new source file is not yet enrolled and regenerated.
  const setupPrefix = "templates/setup/skeleton/docs/_adr/";
  const skillPrefix = "templates/skills/discern-write-adr/skeleton/docs/_adr/";
  const skeletonFiles = await structuralGuardScope({
    guard: "tests/adr_index_test.ts#shipped-adr-skeleton-parity",
    universe: "authored-text",
    narrow: {
      reason:
        "The setup and bundled write-ADR skeleton directories are two delivery paths for one shipped record template.",
      include: (rel) =>
        rel.startsWith(setupPrefix) || rel.startsWith(skillPrefix),
    },
  });
  const filesIn = async (prefix: string): Promise<Map<string, string>> => {
    const out = new Map<string, string>();
    for (const rel of skeletonFiles.filter((path) => path.startsWith(prefix))) {
      out.set(
        rel.slice(prefix.length),
        await Deno.readTextFile(join(REPO_ROOT, rel)),
      );
    }
    return out;
  };
  const setupFiles = await filesIn(setupPrefix);
  const skillFiles = await filesIn(skillPrefix);
  assertEquals(
    [...setupFiles.keys()].sort(),
    [...skillFiles.keys()].sort(),
    "the two ADR skeletons must ship the same file set",
  );
  for (const [rel, text] of setupFiles) {
    assertEquals(
      text,
      skillFiles.get(rel),
      `templates/…/docs/_adr/${rel} differs between the setup skeleton and ` +
        "the discern-write-adr skill skeleton — edit both together",
    );
  }
});

interface NumberedAdrPath {
  number: string;
  path: string;
}

/** Report every later path that reuses an ADR number together with its first owner. */
function duplicateAdrNumberOffenders(
  records: readonly NumberedAdrPath[],
): string[] {
  const seen = new Map<string, string>();
  const offenders: string[] = [];
  for (const record of records) {
    const prior = seen.get(record.number);
    if (prior !== undefined) {
      offenders.push(
        `ADR number ${record.number} is used twice: ${prior} and ${record.path}`,
      );
    } else {
      seen.set(record.number, record.path);
    }
  }
  return offenders;
}

Deno.test("ADR index: every relative link in the README resolves to a file", async () => {
  const readme = await Deno.readTextFile(join(ADR_DIR, "README.md"));
  const targets = [...readme.matchAll(/\]\(((?:_superseded\/)?[^)#]+\.md)\)/g)]
    .map((m) => m[1] ?? "")
    .filter((t) => !t.startsWith("../"));
  assert(targets.length > 0, "the index should contain ADR links");
  const dangling: string[] = [];
  for (const target of targets) {
    try {
      await Deno.stat(join(ADR_DIR, target));
    } catch {
      dangling.push(target);
    }
  }
  assert(
    dangling.length === 0,
    `${REPO_AUTHORED_PATHS.mapRel}/_adr/README.md links files that do not exist: ${
      dangling.join(", ")
    }`,
  );
});

Deno.test("ADR record: every relative Markdown-file link resolves", async () => {
  const dangling: string[] = [];
  const prefix = `${REPO_AUTHORED_PATHS.mapRel}/_adr/`;
  for (
    const rel of await structuralGuardScope({
      guard: "tests/adr_index_test.ts#adr-relative-markdown-links",
      universe: "tracked-markdown",
      narrow: {
        reason:
          "Relative record links are an invariant of Markdown files in the configured active and superseded ADR tree.",
        include: (path) => path.startsWith(prefix),
      },
    })
  ) {
    const path = join(REPO_ROOT, rel);
    const text = await Deno.readTextFile(path);
    for (
      const match of text.matchAll(
        /\]\((?!https?:|mailto:|#)([^)#]+\.md)(?:#[^)]*)?\)/g,
      )
    ) {
      const target = match[1] ?? "";
      try {
        await Deno.stat(join(dirname(path), target));
      } catch {
        dangling.push(
          `${rel.slice(prefix.length)} -> ${target}`,
        );
      }
    }
  }
  assert(
    dangling.length === 0,
    `ADR links point at files that do not exist:\n${
      dangling.sort().join("\n")
    }`,
  );
});

Deno.test("ADR numbers are never reused across the active and superseded sets", async () => {
  const offenders = duplicateAdrNumberOffenders(
    (await adrRecordsIn(ADR_DIR)).map((record) => ({
      number: record.number,
      path: record.entry.relToDocs,
    })),
  );
  assertEquals(
    offenders,
    [],
    `ADR numbers must be unique:\n${offenders.join("\n")}`,
  );
});

Deno.test("control: a duplicate active and superseded ADR number offends", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-control-" });
  try {
    await Deno.mkdir(join(dir, "_superseded"));
    await Deno.writeTextFile(
      join(dir, "4242-new-direction.md"),
      "# ADR 4242: A new direction\n",
    );
    await Deno.writeTextFile(
      join(dir, "_superseded", "4242-retired-direction.md"),
      "# ADR 4242: A retired direction\n",
    );
    const offenders = duplicateAdrNumberOffenders(
      (await adrRecordsIn(dir)).map((record) => ({
        number: record.number,
        path: record.entry.relToDocs,
      })),
    );
    assertEquals(
      offenders,
      [
        "ADR number 4242 is used twice: 4242-new-direction.md and " +
        "_superseded/4242-retired-direction.md",
      ],
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});
