/**
 * Architectural guard for the ADR index. The configured map's ADR README is the
 * only view of the record set most readers ever open, so an ADR missing from it
 * is invisible — exactly how 0106–0109 sat unlisted for four records. The
 * canonical set is the DIRECTORY (every `NNNN-*.md` on disk), never the index
 * itself, so a new ADR auto-enrols: write the file and this guard fails until
 * the index names it.
 *
 * The maintenance itself is the SHIPPED core (`src/lib/adr_index.ts`, driven by
 * `discern refresh` and the gate's adr_index precondition) — this file is the
 * thin proof-it-bites layer over that core plus the live-repo completeness run,
 * not a second implementation.
 */

import { assert, assertEquals } from "@std/assert";
import { walk } from "@std/fs";
import { dirname, join, relative } from "@std/path";
import { adrIndexState } from "../src/lib/adr_index.ts";
import { type AdrRecord, adrRecords, discoverDocs } from "../src/lib/docs.ts";
import { REPO_AUTHORED_PATHS, REPO_ROOT } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";

const ADR_DIR = join(REPO_AUTHORED_PATHS.map, "_adr");

async function adrRecordsIn(dir: string): Promise<AdrRecord[]> {
  const tree = await discoverDocs({
    cwd: dir,
    dir,
    includeInternal: true,
  });
  assert(tree !== undefined, `ADR directory does not exist: ${dir}`);
  return adrRecords(tree.entries);
}

Deno.test("ADR index: every record on disk is linked from the README index", async () => {
  const readme = await Deno.readTextFile(join(ADR_DIR, "README.md"));
  const missing = (await adrRecordsIn(ADR_DIR))
    .map((record) => record.entry.relToDocs)
    .filter((rel) => !readme.includes(`](${rel})`));
  assert(
    missing.length === 0,
    `${REPO_AUTHORED_PATHS.mapRel}/_adr/README.md must index every record — add: ${
      missing.join(", ")
    }`,
  );
});

Deno.test("ADR index: the live repo's maintained index is current through the shipped core", async () => {
  const state = await adrIndexState(REPO_ROOT, REPO_AUTHORED_PATHS.mapRel);
  assertEquals(
    state.kind,
    "current",
    `${REPO_AUTHORED_PATHS.mapRel}/_adr/README.md is ${state.kind} — run ` +
      "`discern refresh`" +
      (state.kind === "invalid" ? `: ${state.issue}` : ""),
  );
});

Deno.test("ADR index: the rendered index is a fixed point of the map formatter", async () => {
  // The gate's fix stage runs the Markdown formatter over the map. If the
  // shipped renderer ever emitted text the formatter rewrites, refresh and
  // format would fight forever: refresh writes, format reformats, the currency
  // check flags stale again. Hold the live README (renderer output included)
  // to the formatter's canonical form.
  const path = join(ADR_DIR, "README.md");
  const readme = await Deno.readTextFile(path);
  assertEquals(
    readme,
    await canonicalGeneratedMarkdown(path, readme),
    `${REPO_AUTHORED_PATHS.mapRel}/_adr/README.md is not formatter-canonical — ` +
      "the index renderer and the map formatter disagree",
  );
});

Deno.test("control: a record the index omits reports stale, and the expected text names it", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-stale-" });
  try {
    const adrDir = join(dir, "docs", "_adr");
    await Deno.mkdir(adrDir, { recursive: true });
    await Deno.writeTextFile(
      join(adrDir, "README.md"),
      [
        "# Decisions",
        "",
        "<!-- BEGIN GENERATED: current ADR records -->",
        "<!-- Generated by `discern refresh` from the ADR headings on disk. -->",
        "",
        "<!-- END GENERATED: current ADR records -->",
        "",
      ].join("\n"),
    );
    await Deno.writeTextFile(
      join(adrDir, "0001-first-choice.md"),
      "# ADR 0001: A first choice\n",
    );
    const state = await adrIndexState(dir, "docs/");
    assertEquals(state.kind, "stale");
    assert(
      state.kind === "stale" &&
        state.expected.includes("[0001 — A first choice](0001-first-choice.md)"),
      "the expected index must name the unlisted record",
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("control: a README without markers is absent — the index is opt-in", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-absent-" });
  try {
    const adrDir = join(dir, "docs", "_adr");
    await Deno.mkdir(adrDir, { recursive: true });
    await Deno.writeTextFile(
      join(adrDir, "README.md"),
      "# Decisions\n\nAn authored page with no generated lists.\n",
    );
    await Deno.writeTextFile(
      join(adrDir, "0001-first-choice.md"),
      "# ADR 0001: A first choice\n",
    );
    assertEquals((await adrIndexState(dir, "docs/")).kind, "absent");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("control: a record whose heading defeats the derivation reports invalid, naming it", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-invalid-" });
  try {
    const adrDir = join(dir, "docs", "_adr");
    await Deno.mkdir(adrDir, { recursive: true });
    await Deno.writeTextFile(
      join(adrDir, "README.md"),
      [
        "<!-- BEGIN GENERATED: current ADR records -->",
        "",
        "<!-- END GENERATED: current ADR records -->",
        "",
      ].join("\n"),
    );
    await Deno.writeTextFile(
      join(adrDir, "0001-first-choice.md"),
      "# a heading with no record number\n",
    );
    const state = await adrIndexState(dir, "docs/");
    assertEquals(state.kind, "invalid");
    assert(
      state.kind === "invalid" && state.issue.includes("0001-first-choice.md"),
      "the issue must name the offending record file",
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

interface NumberedAdrPath {
  number: string;
  path: string;
}

function duplicateAdrNumberOffenders(
  records: readonly NumberedAdrPath[],
): string[] {
  const seen = new Map<string, string>();
  const offenders: string[] = [];
  for (const record of records) {
    const prior = seen.get(record.number);
    if (prior !== undefined) {
      offenders.push(
        `ADR number ${record.number} is used twice: ${prior} and ${record.path}`,
      );
    } else {
      seen.set(record.number, record.path);
    }
  }
  return offenders;
}

Deno.test("ADR index: every relative link in the README resolves to a file", async () => {
  const readme = await Deno.readTextFile(join(ADR_DIR, "README.md"));
  const targets = [...readme.matchAll(/\]\(((?:_superseded\/)?[^)#]+\.md)\)/g)]
    .map((m) => m[1] ?? "")
    .filter((t) => !t.startsWith("../"));
  assert(targets.length > 0, "the index should contain ADR links");
  const dangling: string[] = [];
  for (const target of targets) {
    try {
      await Deno.stat(join(ADR_DIR, target));
    } catch {
      dangling.push(target);
    }
  }
  assert(
    dangling.length === 0,
    `${REPO_AUTHORED_PATHS.mapRel}/_adr/README.md links files that do not exist: ${
      dangling.join(", ")
    }`,
  );
});

Deno.test("ADR record: every relative Markdown-file link resolves", async () => {
  const dangling: string[] = [];
  for await (
    const entry of walk(ADR_DIR, { includeDirs: false, exts: [".md"] })
  ) {
    const text = await Deno.readTextFile(entry.path);
    for (
      const match of text.matchAll(
        /\]\((?!https?:|mailto:|#)([^)#]+\.md)(?:#[^)]*)?\)/g,
      )
    ) {
      const target = match[1] ?? "";
      try {
        await Deno.stat(join(dirname(entry.path), target));
      } catch {
        dangling.push(
          `${relative(ADR_DIR, entry.path)} -> ${target}`,
        );
      }
    }
  }
  assert(
    dangling.length === 0,
    `ADR links point at files that do not exist:\n${
      dangling.sort().join("\n")
    }`,
  );
});

Deno.test("ADR numbers are never reused across the active and superseded sets", async () => {
  const offenders = duplicateAdrNumberOffenders(
    (await adrRecordsIn(ADR_DIR)).map((record) => ({
      number: record.number,
      path: record.entry.relToDocs,
    })),
  );
  assertEquals(
    offenders,
    [],
    `ADR numbers must be unique:\n${offenders.join("\n")}`,
  );
});

Deno.test("control: a duplicate active and superseded ADR number offends", async () => {
  const dir = await Deno.makeTempDir({ prefix: "discern-adr-index-control-" });
  try {
    await Deno.mkdir(join(dir, "_superseded"));
    await Deno.writeTextFile(
      join(dir, "4242-new-direction.md"),
      "# ADR 4242: A new direction\n",
    );
    await Deno.writeTextFile(
      join(dir, "_superseded", "4242-retired-direction.md"),
      "# ADR 4242: A retired direction\n",
    );
    const offenders = duplicateAdrNumberOffenders(
      (await adrRecordsIn(dir)).map((record) => ({
        number: record.number,
        path: record.entry.relToDocs,
      })),
    );
    assertEquals(
      offenders,
      [
        "ADR number 4242 is used twice: 4242-new-direction.md and " +
        "_superseded/4242-retired-direction.md",
      ],
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});
