/**
 * The private agent-integration coverage page stays in lockstep with its
 * registries (ADR 0260): the committed page matches the renderer over the
 * live provider registry (`scripts/agent_integration_registry.ts` reading
 * `PROVIDERS`), every integration seam renders exactly one coverage-matrix
 * row, the derived agent axis is the one native catalogue both research
 * matrices share, the authored field notes cover exactly the live `Provider`
 * field union, and every citation token resolves — so a new provider, seam,
 * or `Provider` field auto-enrols here and fails the gate until the page
 * answers for it.
 */

import {
  assert,
  assertEquals,
  assertStringIncludes,
  assertThrows,
} from "@std/assert";
import {
  AGENT_COMMENTARY,
  INTEGRATION_SEAMS,
  PROVIDER_FIELD_NOTES,
  renderAgentIntegrationCoverageDoc,
  resolveCitationTokens,
} from "../scripts/agent_integration_registry.ts";
import { REFERENCE_AGENTS } from "../scripts/cross_agent_registry.ts";
import { AGENT_NAMES } from "../src/shared/agent_catalogue.ts";
import { PROVIDERS } from "../src/lib/providers.ts";
import { REPO_AUTHORED_PATHS } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";

const PAGE_REL = "_private/research/agent-integration-coverage.md";
const rendered = renderAgentIntegrationCoverageDoc();

/** Read the checked-in coverage page for generator parity. */
async function committedPage(): Promise<string> {
  return await Deno.readTextFile(`${REPO_AUTHORED_PATHS.map}/${PAGE_REL}`);
}

Deno.test("the committed coverage page matches the registries (run `deno task codegen`)", async () => {
  const path = `${REPO_AUTHORED_PATHS.map}/${PAGE_REL}`;
  assertEquals(
    await committedPage(),
    await canonicalGeneratedMarkdown(path, rendered),
    `${REPO_AUTHORED_PATHS.mapRel}/${PAGE_REL} is stale — run \`deno task codegen\``,
  );
});

Deno.test("the committed page declares its generated provenance", async () => {
  assertStringIncludes(
    await committedPage(),
    "GENERATED by `deno task codegen`",
    "the committed coverage page lost its generated banner",
  );
});

Deno.test("both research matrices share the one native agent axis", () => {
  const researched = new Set(
    REFERENCE_AGENTS.flatMap((agent) =>
      agent.nativeName === undefined ? [] : [agent.nativeName]
    ),
  );
  assertEquals(
    researched,
    new Set<string>(AGENT_NAMES),
    "the cross-agent reference and the coverage page must research the same " +
      "native provider set — both derive from AGENT_NAMES",
  );
  for (const name of AGENT_NAMES) {
    assert(
      Object.hasOwn(AGENT_COMMENTARY, name),
      `native provider ${name} has no commentary in the coverage registry`,
    );
  }
});

Deno.test("the rendered coverage matrix carries every provider column and seam row", () => {
  const start = rendered.indexOf("## Coverage matrix");
  assert(start >= 0, "the rendered page lost its coverage matrix");
  const end = rendered.indexOf("\n---\n", start);
  assert(end > start, "the coverage-matrix section never closes");
  const matrix = rendered.slice(start, end);
  const rows = matrix.split("\n").filter((line) => line.startsWith("|"));
  const header = rows[0];
  assert(header !== undefined, "the coverage matrix lost its header row");
  for (const name of AGENT_NAMES) {
    assertStringIncludes(
      header,
      PROVIDERS[name].label,
      `the coverage matrix lost the ${name} column`,
    );
  }
  const ids = INTEGRATION_SEAMS.map((seam) => seam.id);
  assertEquals(new Set(ids).size, ids.length, "seam ids must be unique");
  const renderedLabels = rows.slice(2).map((row) => {
    const label = row.split("|")[1];
    assert(label !== undefined, `malformed matrix row: ${row}`);
    return label.trim();
  });
  assertEquals(
    renderedLabels,
    INTEGRATION_SEAMS.map((seam) => seam.label),
    "matrix rows must be the declared seams in declaration order",
  );
});

Deno.test("every provider renders one section with its fact table and commentary", () => {
  for (const name of AGENT_NAMES) {
    const heading = `### ${PROVIDERS[name].label} — ${
      AGENT_COMMENTARY[name].epithet
    }`;
    assertStringIncludes(
      rendered,
      heading,
      `the rendered page lost the ${name} section`,
    );
  }
});

Deno.test("the field notes cover exactly the live Provider field union", () => {
  const live = new Set<string>();
  for (const name of AGENT_NAMES) {
    for (const field of Object.keys(PROVIDERS[name])) {
      live.add(field);
    }
  }
  assertEquals(
    new Set(Object.keys(PROVIDER_FIELD_NOTES)),
    live,
    "PROVIDER_FIELD_NOTES and the live Provider record have drifted apart — " +
      "explain the new field (or delete the stale note) in " +
      "scripts/agent_integration_registry.ts",
  );
});

Deno.test("citation tokens resolve, and an unknown citation throws", () => {
  assert(
    !rendered.includes("{{g:") && !rendered.includes("{{x:"),
    "an authored body carries an unresolved citation token",
  );
  assertThrows(
    () => resolveCitationTokens("{{g:no-such-gap}}"),
    Error,
    "cites no gap section",
  );
  assertThrows(
    () => resolveCitationTokens("{{x:no-such-dimension}}"),
    Error,
    "cites no behaviour-reference dimension",
  );
});
