/**
 * The generated brand documents stay in lockstep with the brand registry
 * (`BRAND_DOCUMENTS` in `scripts/brand_registry.ts`): every generated row's
 * committed page matches its renderer byte-for-byte and carries the
 * generated banner, every citation token resolves against the live tables
 * (`CLAIMS` in `scripts/brand/claims.ts` among them), the registry's sets
 * keep unique ids, every pillar cites the claims ledger, and the
 * do-not-claim list stays non-empty. The assertions iterate the registry,
 * so a newly converted document enrols here the moment its row flips to
 * generated.
 */

import {
  assert,
  assertEquals,
  assertStringIncludes,
  assertThrows,
} from "@std/assert";
import { join } from "@std/path";
import { CLAIMS, DO_NOT_CLAIM } from "../scripts/brand/claims.ts";
import {
  CTA_BANKS,
  DESCRIPTIONS,
  HEADLINES,
  HERO_SYSTEMS,
  PILLARS,
  TERRITORIES,
} from "../scripts/brand/messaging.ts";
import {
  BRAND_DOCUMENTS,
  brandDocMapRel,
  generatedBrandDocuments,
  renderBrandDoc,
  resolveBrandCitations,
} from "../scripts/brand_registry.ts";
import { REPO_AUTHORED_PATHS } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";

Deno.test("every generated brand page matches its renderer (run `deno task codegen`)", async () => {
  const docs = generatedBrandDocuments();
  assert(docs.length > 0, "the registry declares no generated documents");
  for (const doc of docs) {
    const path = join(REPO_AUTHORED_PATHS.map, brandDocMapRel(doc));
    const committed = await Deno.readTextFile(path);
    assertEquals(
      committed,
      await canonicalGeneratedMarkdown(path, renderBrandDoc(doc.id)),
      `${brandDocMapRel(doc)} is stale — run \`deno task codegen\``,
    );
  }
});

Deno.test("every generated brand page declares its generated provenance", async () => {
  for (const doc of generatedBrandDocuments()) {
    const path = join(REPO_AUTHORED_PATHS.map, brandDocMapRel(doc));
    assertStringIncludes(
      await Deno.readTextFile(path),
      "GENERATED by `deno task codegen`",
      `${brandDocMapRel(doc)} lost its generated banner`,
    );
  }
});

Deno.test("every registered brand document exists on disk", async () => {
  for (const doc of BRAND_DOCUMENTS) {
    const path = join(REPO_AUTHORED_PATHS.map, brandDocMapRel(doc));
    const info = await Deno.stat(path).catch(() => undefined);
    assert(
      info?.isFile === true,
      `${doc.id}: ${brandDocMapRel(doc)} is registered but not on disk`,
    );
  }
});

Deno.test("registry ids, files, and slugs are unique and citable", () => {
  const unique = (label: string, values: readonly string[]): void => {
    assertEquals(
      new Set(values).size,
      values.length,
      `${label} must be unique`,
    );
  };
  unique("document ids", BRAND_DOCUMENTS.map((doc) => doc.id));
  unique("document files", BRAND_DOCUMENTS.map((doc) => doc.file));
  unique("territory ids", TERRITORIES.map((territory) => territory.id));
  unique("pillar ids", PILLARS.map((pillar) => pillar.id));
  unique(
    "description ids",
    DESCRIPTIONS.map((description) => description.id),
  );
  unique("hero ids", HERO_SYSTEMS.map((hero) => hero.id));
  unique("CTA bank ids", CTA_BANKS.map((bank) => bank.id));
  unique("headline lines", HEADLINES.map((headline) => headline.line));
  // The resolver's token pattern only matches kebab ids, so anything else
  // could never be cited.
  for (const id of BRAND_DOCUMENTS.map((doc) => doc.id)) {
    assert(/^[a-z0-9-]+$/.test(id), `document id ${id} is not citable`);
  }
  for (const slug of Object.keys(CLAIMS)) {
    assert(/^[a-z0-9-]+$/.test(slug), `claim slug ${slug} is not citable`);
  }
});

Deno.test("citation tokens resolve against the live registry, and unknown ids throw", () => {
  assertStringIncludes(
    resolveBrandCitations("{{claim:proof-exact-tree}}"),
    "claims-and-evidence.md#",
    "a claim citation must link into the claims ledger",
  );
  assertEquals(
    resolveBrandCitations("{{doc:messaging}}"),
    "[`messaging.md`](messaging.md)",
  );
  assertThrows(
    () => resolveBrandCitations("{{claim:no-such-claim}}"),
    Error,
    "cites no known claim",
  );
  assertThrows(
    () => resolveBrandCitations("{{doc:no-such-doc}}"),
    Error,
    "cites no known doc",
  );
  assertThrows(
    () => resolveBrandCitations("{{concept:no-such-concept}}"),
    Error,
    "cites no known concept",
  );
  for (const doc of generatedBrandDocuments()) {
    assert(
      !renderBrandDoc(doc.id).includes("{{"),
      `${doc.id} renders an unresolved citation token`,
    );
  }
});

Deno.test("every pillar cites at least one existing claim", () => {
  for (const pillar of PILLARS) {
    assert(pillar.claims.length > 0, `${pillar.id} cites no claims`);
    for (const slug of pillar.claims) {
      assert(
        Object.hasOwn(CLAIMS, slug),
        `${pillar.id} cites unknown claim ${slug}`,
      );
    }
  }
});

Deno.test("the claims ledger and the do-not-claim list hold their shape", () => {
  const slugs = Object.keys(CLAIMS);
  assert(slugs.length > 0, "the claims ledger must not be empty");
  for (const [slug, claim] of Object.entries(CLAIMS)) {
    assert(
      claim.evidence.length > 0,
      `${slug} carries no evidence class`,
    );
  }
  assert(DO_NOT_CLAIM.length > 0, "DO_NOT_CLAIM must not be empty");
});
