/**
 * The generated brand documents stay in lockstep with the brand registry
 * (`BRAND_DOCUMENTS` in `scripts/brand_registry.ts`): every generated row's
 * committed page matches its renderer byte-for-byte and carries the
 * generated banner, every citation token resolves against the live tables
 * (`CLAIMS` in `scripts/brand/claims.ts` among them), the registry's sets
 * keep unique ids, every pillar cites the claims ledger, and the
 * do-not-claim list stays non-empty. The assertions iterate the registry,
 * so a newly converted document enrols here the moment its row flips to
 * generated.
 */

import {
  assert,
  assertEquals,
  assertStringIncludes,
  assertThrows,
} from "@std/assert";
import { join } from "@std/path";
import { directoryExists, fileExists } from "../src/shared/fs_presence.ts";
import { CONCEPTS, TRANSLATIONS } from "../scripts/brand/bridge.ts";
import { CLAIMS, DO_NOT_CLAIM } from "../scripts/brand/claims.ts";
import { COPY_PATTERNS } from "../scripts/brand/patterns.ts";
import { PROPOSED_MECHANICAL_CHECKS } from "../scripts/brand/mechanical_checks.ts";
import {
  OUTSTANDING_WORK,
  PRIVATE_OVERLAY_MARKER,
  READING_PATHS,
} from "../scripts/brand/docs/readme.ts";
import {
  CTA_BANKS,
  DESCRIPTIONS,
  FACT_LINES,
  HEADLINES,
  HERO_SYSTEMS,
  PILLARS,
  POSITIONING_GRID,
  TERRITORIES,
} from "../scripts/brand/messaging.ts";
import {
  BRAND_DOCUMENTS,
  brandDocMapRel,
  generatedBrandDocuments,
  renderBrandDoc,
  resolveBrandCitations,
} from "../scripts/brand_registry.ts";
import {
  BRAND_OVERLAY_DIR,
  brandDocHrefFromGenerated,
  REGISTERS,
} from "../scripts/brand/model.ts";
import {
  BANNED_MOVES,
  BANNED_WORDS,
  BRAND_FOUNDATION_READING_STEPS,
  MECHANICS,
  renderVoiceSkill,
  VOICES,
  voiceSkillName,
  voiceSkillRel,
} from "../scripts/brand/voice.ts";
import { skillFrontmatterIssues } from "../src/lib/skills.ts";
import { REPO_AUTHORED_PATHS, REPO_ROOT } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";

Deno.test("every generated brand page matches its renderer (run `deno task codegen`)", async () => {
  const docs = generatedBrandDocuments();
  assert(docs.length > 0, "the registry declares no generated documents");
  for (const doc of docs) {
    const path = join(REPO_AUTHORED_PATHS.map, brandDocMapRel(doc));
    const committed = await Deno.readTextFile(path);
    assertEquals(
      committed,
      await canonicalGeneratedMarkdown(path, renderBrandDoc(doc.id)),
      `${brandDocMapRel(doc)} is stale — run \`deno task codegen\``,
    );
  }
});

Deno.test("every generated brand page declares its generated provenance", async () => {
  for (const doc of generatedBrandDocuments()) {
    const path = join(REPO_AUTHORED_PATHS.map, brandDocMapRel(doc));
    assertStringIncludes(
      await Deno.readTextFile(path),
      "GENERATED by `deno task codegen`",
      `${brandDocMapRel(doc)} lost its generated banner`,
    );
  }
});

Deno.test("the homepage path and brand voice both route through the demand canon", () => {
  const homepage = READING_PATHS.find((path) =>
    path.id === "homepage-or-campaign"
  );
  assert(homepage !== undefined, "missing homepage-or-campaign reading path");
  assertEquals(
    homepage.steps.slice(0, BRAND_FOUNDATION_READING_STEPS.length),
    BRAND_FOUNDATION_READING_STEPS.map((step) => step.instruction),
    "the homepage reading path diverges from the brand-writing foundations",
  );
  const brandReading = VOICES.brand.sections.find((section) =>
    section.heading === "Read before writing"
  );
  assert(
    brandReading?.kind === "prose",
    "the brand voice skill lost its reading instructions",
  );
  let previous = -1;
  for (const step of BRAND_FOUNDATION_READING_STEPS) {
    const current = brandReading.body.indexOf(step.instruction);
    assert(
      current > previous,
      `the brand voice skill skips or reorders its foundation: ${step.id}`,
    );
    previous = current;
  }
});

Deno.test("every register's generated skill matches its renderer (run `deno task codegen`)", async () => {
  for (const register of REGISTERS) {
    const rel = voiceSkillRel(register);
    const path = join(REPO_ROOT, rel);
    const committed = await Deno.readTextFile(path);
    assertEquals(
      committed,
      await canonicalGeneratedMarkdown(path, renderVoiceSkill(register)),
      `${rel} is stale — run \`deno task codegen\``,
    );
  }
});

Deno.test("every generated voice skill is a well-formed skill in the configured skills dir", () => {
  for (const register of REGISTERS) {
    const path = join(REPO_ROOT, voiceSkillRel(register));
    assert(
      path.startsWith(REPO_AUTHORED_PATHS.skills),
      `${voiceSkillRel(register)} sits outside the configured [skills].dir — ` +
        "agents would never materialize it",
    );
    assertEquals(
      skillFrontmatterIssues(
        renderVoiceSkill(register),
        voiceSkillName(register),
      ),
      [],
      `${register}: the rendered skill fails the frontmatter contract`,
    );
  }
});

Deno.test("every generated voice skill carries the banner directly after its frontmatter", () => {
  for (const register of REGISTERS) {
    const rendered = renderVoiceSkill(register);
    assert(
      rendered.startsWith("---\n"),
      `${register}: frontmatter must open the file`,
    );
    const close = rendered.indexOf("\n---\n", 3);
    assert(close > 0, `${register}: no closing frontmatter fence`);
    const afterFrontmatter = rendered.slice(close + "\n---\n".length);
    assert(
      afterFrontmatter.startsWith("\n<!-- GENERATED"),
      `${register}: the generated banner must directly follow the frontmatter`,
    );
  }
});

Deno.test("the shared canon renders where the owner placed it", () => {
  // Owner selection, 2026-08-08: product and brand carry the banned canon;
  // every register carries the mechanics. A dropped marker is a silent loss
  // of enforcement canon, so the placement is held here.
  const kinds = (register: (typeof REGISTERS)[number]): Set<string> =>
    new Set(VOICES[register].sections.map((section) => section.kind));
  for (const register of ["brand", "product"] as const) {
    assert(
      kinds(register).has("banned-words") &&
        kinds(register).has("banned-moves"),
      `${register}: the banned canon must render into this skill`,
    );
  }
  for (const register of REGISTERS) {
    assert(
      kinds(register).has("mechanics"),
      `${register}: the mechanics must render into this skill`,
    );
  }
  for (const word of BANNED_WORDS) {
    assert(
      word.registers.includes("product"),
      `${word.id}: every banned word renders at least into the product skill`,
    );
  }
});

Deno.test("every registered brand document exists on disk", async () => {
  // Authored rows live in the `_private` overlay tree, which the launch
  // scrub turns into a local, gitignored clone: present on the owner's
  // machines, absent from a contributor's clean checkout. Their existence is
  // only checkable when the overlay itself is present — a conditional, so
  // the same commit passes identically on both kinds of machine.
  const overlay = join(REPO_AUTHORED_PATHS.map, BRAND_OVERLAY_DIR);
  const overlayPresent = await directoryExists(overlay);
  for (const doc of BRAND_DOCUMENTS) {
    if (doc.mode.kind === "authored" && !overlayPresent) continue;
    const path = join(REPO_AUTHORED_PATHS.map, brandDocMapRel(doc));
    assert(
      await fileExists(path),
      `${doc.id}: ${brandDocMapRel(doc)} is registered but not on disk`,
    );
  }
});

Deno.test("registry ids, files, and slugs are unique and citable", () => {
  const unique = (label: string, values: readonly string[]): void => {
    assertEquals(
      new Set(values).size,
      values.length,
      `${label} must be unique`,
    );
  };
  unique("document ids", BRAND_DOCUMENTS.map((doc) => doc.id));
  unique("document files", BRAND_DOCUMENTS.map((doc) => doc.file));
  unique("territory ids", TERRITORIES.map((territory) => territory.id));
  unique("pillar ids", PILLARS.map((pillar) => pillar.id));
  unique("positioning-grid ids", POSITIONING_GRID.map((row) => row.id));
  unique("fact-line ids", FACT_LINES.map((fact) => fact.id));
  unique(
    "description ids",
    DESCRIPTIONS.map((description) => description.id),
  );
  unique("hero ids", HERO_SYSTEMS.map((hero) => hero.id));
  unique("CTA bank ids", CTA_BANKS.map((bank) => bank.id));
  unique("headline lines", HEADLINES.map((headline) => headline.line));
  unique("concept ids", CONCEPTS.map((concept) => concept.id));
  unique(
    "translation ids",
    TRANSLATIONS.map((translation) => translation.id),
  );
  unique("copy-pattern ids", COPY_PATTERNS.map((pattern) => pattern.id));
  unique("reading-path ids", READING_PATHS.map((path) => path.id));
  unique("outstanding-work ids", OUTSTANDING_WORK.map((item) => item.id));
  unique("banned-word ids", BANNED_WORDS.map((word) => word.id));
  unique("banned-move ids", BANNED_MOVES.map((move) => move.id));
  unique("mechanics ids", MECHANICS.map((rule) => rule.id));
  for (const register of REGISTERS) {
    const sections = VOICES[register].sections;
    unique(
      `${register} voice section headings`,
      sections.map((section) => section.heading),
    );
    unique(
      `${register} voice rules-section ids`,
      sections.flatMap((section) =>
        section.kind === "rules" ? [section.id] : []
      ),
    );
    for (const section of sections) {
      if (section.kind !== "rules" && section.kind !== "principles") continue;
      unique(
        `${register} "${section.heading}" item ids`,
        section.items.map((item) => item.id),
      );
    }
  }
  for (const register of REGISTERS) {
    unique(
      `${register} proposed-check ids`,
      PROPOSED_MECHANICAL_CHECKS[register].map((check) => check.id),
    );
  }
  // The resolver's token pattern only matches kebab ids, so anything else
  // could never be cited.
  for (const id of BRAND_DOCUMENTS.map((doc) => doc.id)) {
    assert(/^[a-z0-9-]+$/.test(id), `document id ${id} is not citable`);
  }
  for (const slug of Object.keys(CLAIMS)) {
    assert(/^[a-z0-9-]+$/.test(slug), `claim slug ${slug} is not citable`);
  }
  for (const id of CONCEPTS.map((concept) => concept.id)) {
    assert(/^[a-z0-9-]+$/.test(id), `concept id ${id} is not citable`);
  }
});

Deno.test("citation tokens resolve against the live registry, and unknown ids throw", () => {
  assertStringIncludes(
    resolveBrandCitations("{{claim:proof-exact-tree}}"),
    "claims-and-evidence.md#",
    "a claim citation must link into the claims ledger",
  );
  assertEquals(
    resolveBrandCitations("{{doc:messaging}}"),
    "[`messaging.md`](messaging.md)",
  );
  assertEquals(
    resolveBrandCitations("{{doc:audiences}}"),
    "[`audiences.md`](../../_private/brand/audiences.md)",
    "an overlay-document citation must cross the tier boundary",
  );
  assertEquals(
    resolveBrandCitations("{{concept:gate}}"),
    "[Gate](register-bridge.md#core-concept-map)",
    "a concept citation must link into the register bridge's concept map",
  );
  assertThrows(
    () => resolveBrandCitations("{{claim:no-such-claim}}"),
    Error,
    "cites no known claim",
  );
  assertThrows(
    () => resolveBrandCitations("{{doc:no-such-doc}}"),
    Error,
    "cites no known doc",
  );
  assertThrows(
    () => resolveBrandCitations("{{concept:no-such-concept}}"),
    Error,
    "cites no known concept",
  );
  for (const doc of generatedBrandDocuments()) {
    assert(
      !renderBrandDoc(doc.id).includes("{{"),
      `${doc.id} renders an unresolved citation token`,
    );
  }
});

Deno.test("the rendered README document map equals the registry", () => {
  const rendered = renderBrandDoc("readme");
  for (const doc of BRAND_DOCUMENTS) {
    // A skill row displays its repo-relative path over the traversal href;
    // an authored row's href crosses into the `_private` overlay tree.
    const display = doc.mode.kind === "skill"
      ? voiceSkillRel(doc.mode.register)
      : doc.file;
    const href = brandDocHrefFromGenerated(doc);
    if (doc.id === "readme") {
      assert(
        !rendered.includes(`[\`${display}\`](${href})`),
        "the README must not list itself in the document map",
      );
      continue;
    }
    const row = rendered.split("\n").find((line) =>
      line.includes(`[\`${display}\`](${href})`)
    );
    assert(row !== undefined, `${doc.id} is missing from the document map`);
    const overlay = doc.mode.kind === "authored" && doc.mode.privateOverlay;
    assertEquals(
      row.includes(PRIVATE_OVERLAY_MARKER),
      overlay,
      `${doc.id}: the map row and the registry disagree about the overlay`,
    );
  }
});

Deno.test("every pillar, contrast, and fact line cites existing claims", () => {
  const citers = [
    ...PILLARS.map((pillar) => ({ id: pillar.id, claims: pillar.claims })),
    ...POSITIONING_GRID.map((row) => ({ id: row.id, claims: row.claims })),
    ...FACT_LINES.map((fact) => ({ id: fact.id, claims: [fact.claim] })),
  ];
  for (const citer of citers) {
    assert(citer.claims.length > 0, `${citer.id} cites no claims`);
    for (const slug of citer.claims) {
      assert(
        Object.hasOwn(CLAIMS, slug),
        `${citer.id} cites unknown claim ${slug}`,
      );
    }
  }
});

Deno.test("the claims ledger and the do-not-claim list hold their shape", () => {
  const slugs = Object.keys(CLAIMS);
  assert(slugs.length > 0, "the claims ledger must not be empty");
  for (const [slug, claim] of Object.entries(CLAIMS)) {
    assert(
      claim.evidence.length > 0,
      `${slug} carries no evidence class`,
    );
  }
  assert(DO_NOT_CLAIM.length > 0, "DO_NOT_CLAIM must not be empty");
});
