/**
 * The generated register Vale styles stay in lockstep with their registry
 * (`VALE_STYLE_RULES` in `scripts/brand/vale.ts`): every committed style
 * file matches its renderer byte-for-byte, every style directory contains
 * exactly the rendered set, the canonical-sets entry declares exactly the
 * live artifacts, and every rule's source citations resolve against the
 * voice registry — so a rule added to the registry fails the gate until
 * the styles regenerate, and a renamed source strands nothing.
 *
 * The partition guard is the audited boundary behind "to the extent
 * practical": every proposed mechanical check in the copy review is either
 * cited by a generated rule or carries exactly one recorded disposition in
 * `VALE_DISPOSITIONS` — never both, never neither — so a new proposal
 * cannot land without enforcement or a reason on record.
 */

import { assert, assertEquals, assertThrows } from "@std/assert";
import { join } from "@std/path";
import { REGISTERS } from "../scripts/brand/model.ts";
import { PROPOSED_MECHANICAL_CHECKS } from "../scripts/brand/docs/copy_review.ts";
import {
  resolveValeSource,
  VALE_DISPOSITIONS,
  VALE_STYLE_RULES,
  valeCheckPatterns,
  valePatternOffences,
  type ValeRuleSource,
  valeStyleFiles,
  valeStyleName,
} from "../scripts/brand/vale.ts";
import { CANONICAL_SETS } from "../scripts/canonical_sets.ts";
import { REPO_ROOT } from "./repo_authored_paths.ts";

Deno.test("every committed style file matches its renderer (run `deno task codegen`)", async () => {
  const files = valeStyleFiles();
  assert(files.length > 0, "the registry declares no style files");
  for (const file of files) {
    const committed = await Deno.readTextFile(join(REPO_ROOT, file.rel));
    assertEquals(
      committed,
      file.text,
      `${file.rel} is stale — run \`deno task codegen\``,
    );
  }
});

Deno.test("every generated style directory contains exactly the rendered set", async () => {
  const expected = new Map<string, Set<string>>();
  for (const register of REGISTERS) {
    expected.set(valeStyleName(register), new Set());
  }
  for (const file of valeStyleFiles()) {
    const [, style, name] = file.rel.split("/");
    assert(style !== undefined && name !== undefined, `odd rel ${file.rel}`);
    expected.get(style)?.add(name);
  }
  for (const [style, names] of expected) {
    assert(
      names.size > 0,
      `${style} renders no rules — a register lost its enforcement`,
    );
    const onDisk = new Set<string>();
    for await (const entry of Deno.readDir(join(REPO_ROOT, ".vale", style))) {
      if (entry.isFile) onDisk.add(entry.name);
    }
    assertEquals(
      [...onDisk].sort(),
      [...names].sort(),
      `.vale/${style}/ and the registry disagree — a stray file in a ` +
        "generated style directory is invisible to the registry; declare " +
        "the rule in scripts/brand/vale.ts and regenerate",
    );
  }
});

Deno.test("every rendered style file carries the generated banner", () => {
  for (const file of valeStyleFiles()) {
    assert(
      file.text.startsWith("# GENERATED by `deno task codegen`"),
      `${file.rel} lost its generated banner`,
    );
  }
});

Deno.test("the canonical-sets entry declares exactly the live artifacts", () => {
  const entry = CANONICAL_SETS.find((set) => set.id === "brand-vale-styles");
  assert(entry !== undefined, "brand-vale-styles left the meta-registry");
  assertEquals(
    entry.artifacts.map((artifact) => artifact.path).sort(),
    valeStyleFiles().map((file) => file.rel).sort(),
    "brand-vale-styles artifacts and the rendered style files have " +
      "drifted apart — declare the rule's file in scripts/canonical_sets.ts " +
      "(and [generated.codegen].paths) with the registry change",
  );
});

Deno.test("every rule's source citations resolve, and an unknown id throws", () => {
  for (const rule of VALE_STYLE_RULES) {
    for (const source of rule.sources) {
      const label = resolveValeSource(source);
      assert(label.length > 0, `${rule.id}: empty provenance label`);
    }
  }
  const unknown = {
    kind: "banned-word",
    word: "no-such-word",
  } as unknown as ValeRuleSource;
  assertThrows(
    () => resolveValeSource(unknown),
    Error,
    "unknown banned word",
    "the resolver must throw on an id the registry no longer declares",
  );
});

Deno.test("every proposed check is implemented or recorded — exactly one of the two", () => {
  const cited = new Set<string>();
  for (const rule of VALE_STYLE_RULES) {
    for (const source of rule.sources) {
      if (source.kind === "proposed-check") {
        cited.add(`${source.register}/${source.check}`);
      }
    }
  }
  const recorded = new Map<string, number>();
  for (const disposition of VALE_DISPOSITIONS) {
    const key = `${disposition.check.register}/${disposition.check.check}`;
    recorded.set(key, (recorded.get(key) ?? 0) + 1);
    assert(
      disposition.reason.trim().length > 0,
      `${key}: a disposition carries its reason`,
    );
  }
  const offenders: string[] = [];
  for (const register of REGISTERS) {
    for (const check of PROPOSED_MECHANICAL_CHECKS[register]) {
      const key = `${register}/${check.id}`;
      const isCited = cited.has(key);
      const dispositions = recorded.get(key) ?? 0;
      if (!isCited && dispositions === 0) {
        offenders.push(
          `${key} is neither implemented by a generated rule nor recorded ` +
            "in VALE_DISPOSITIONS — implement it or record the deferral",
        );
      }
      if (isCited && dispositions > 0) {
        offenders.push(
          `${key} is implemented but still carries a disposition — delete ` +
            "the stale record",
        );
      }
      if (dispositions > 1) {
        offenders.push(`${key} carries ${dispositions} dispositions`);
      }
    }
  }
  assertEquals(
    offenders,
    [],
    `the proposed-check partition drifted:\n  ${offenders.join("\n  ")}`,
  );
});

Deno.test("every generated pattern survives a source-line wrap", () => {
  // The map hard-wraps prose, so a literal space in a pattern silently
  // misses wrapped instances — the same class the authored style's guard
  // holds (tests/voice_vale_parity_test.ts); the renderer throws on it, and
  // this control proves the predicate discriminates.
  for (const rule of VALE_STYLE_RULES) {
    for (const pattern of valeCheckPatterns(rule.check)) {
      assertEquals(
        valePatternOffences(pattern),
        [],
        `${rule.id}: pattern would miss wrapped instances`,
      );
    }
  }
  assert(
    valePatternOffences("literal space").length > 0,
    "the literal-space predicate no longer discriminates",
  );
  assert(
    valePatternOffences("").length > 0,
    "the empty-pattern predicate no longer discriminates",
  );
});

Deno.test("rule ids are unique per style and PascalCase", () => {
  const seen = new Set<string>();
  for (const rule of VALE_STYLE_RULES) {
    assert(
      /^[A-Z][A-Za-z]+$/.test(rule.id),
      `${rule.id}: a rule id is its Vale check name — PascalCase, letters only`,
    );
    const key = `${rule.register}/${rule.id}`;
    assert(!seen.has(key), `${key} is declared twice`);
    seen.add(key);
  }
});
