/**
 * The generated register Vale styles stay in lockstep with their registry
 * (`VALE_STYLE_RULES` in `scripts/brand/vale.ts`): every committed style
 * file matches its renderer byte-for-byte, every style directory contains
 * exactly the rendered set, the canonical-sets entry declares exactly the
 * live artifacts, and every rule's source citations resolve against the
 * voice registry — so a rule added to the registry fails the gate until
 * the styles regenerate, and a renamed source strands nothing.
 *
 * The partition guard is the audited boundary behind "to the extent
 * practical": every proposed mechanical check in the copy review is either
 * cited by a generated rule or carries exactly one recorded disposition in
 * `VALE_DISPOSITIONS` — never both, never neither — so a new proposal
 * cannot land without enforcement or a reason on record.
 */

import {
  assert,
  assertEquals,
  assertStringIncludes,
  assertThrows,
} from "@std/assert";
import { dirname, join } from "@std/path";
import { REGISTERS } from "../scripts/brand/model.ts";
import { PROPOSED_MECHANICAL_CHECKS } from "../scripts/brand/docs/copy_review.ts";
import {
  coveragePartitionIssues,
  renderVoiceEnforcementCoverageDoc,
  resolveValeSource,
  VALE_DISPOSITIONS,
  VALE_STYLE_RULES,
  valeCheckPatterns,
  valePatternOffences,
  type ValeRuleSource,
  valeStyleFiles,
  valeStyleName,
  VOICE_ENFORCEMENT_COVERAGE_PAGE_REL,
  voiceEnforcementCoverage,
  voiceEnforcementReferences,
} from "../scripts/brand/vale.ts";
import { CANONICAL_SETS } from "../scripts/canonical_sets.ts";
import { runVale } from "../scripts/vale_lib.ts";
import { withTempDir } from "./helpers.ts";
import { REPO_AUTHORED_PATHS, REPO_ROOT } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";
import { structuralGuardScope } from "./structural_guard_scope.ts";

Deno.test("every committed style file matches its renderer (run `deno task codegen`)", async () => {
  const files = valeStyleFiles();
  assert(files.length > 0, "the registry declares no style files");
  for (const file of files) {
    const committed = await Deno.readTextFile(join(REPO_ROOT, file.rel));
    assertEquals(
      committed,
      file.text,
      `${file.rel} is stale — run \`deno task codegen\``,
    );
  }
});

Deno.test("every generated style directory contains exactly the rendered set", async () => {
  const styleFiles = await structuralGuardScope({
    guard: "tests/brand_vale_codegen_test.ts#generated-vale-style-files",
    universe: "authored-text",
    narrow: {
      reason:
        "The Vale registry generates the tracked YAML files beneath the repository's .vale style directories.",
      include: (path) => path.startsWith(".vale/") && path.endsWith(".yml"),
    },
  });
  const expected = new Map<string, Set<string>>();
  for (const register of REGISTERS) {
    expected.set(valeStyleName(register), new Set());
  }
  for (const file of valeStyleFiles()) {
    const [, style, name] = file.rel.split("/");
    assert(style !== undefined && name !== undefined, `odd rel ${file.rel}`);
    expected.get(style)?.add(name);
  }
  for (const [style, names] of expected) {
    assert(
      names.size > 0,
      `${style} renders no rules — a register lost its enforcement`,
    );
    const prefix = `.vale/${style}/`;
    const onDisk = new Set(
      styleFiles.filter((rel) => rel.startsWith(prefix)).map((rel) =>
        rel.slice(prefix.length)
      ),
    );
    assertEquals(
      [...onDisk].sort(),
      [...names].sort(),
      `.vale/${style}/ and the registry disagree — a stray file in a ` +
        "generated style directory is invisible to the registry; declare " +
        "the rule in scripts/brand/vale.ts and regenerate",
    );
  }
});

Deno.test("every rendered style file carries the generated banner", () => {
  for (const file of valeStyleFiles()) {
    assert(
      file.text.startsWith("# GENERATED by `deno task codegen`"),
      `${file.rel} lost its generated banner`,
    );
  }
});

Deno.test("the canonical-sets entry declares exactly the live artifacts", () => {
  const entry = CANONICAL_SETS.find((set) => set.id === "brand-vale-styles");
  assert(entry !== undefined, "brand-vale-styles left the meta-registry");
  assertEquals(
    entry.artifacts.map((artifact) => artifact.path).sort(),
    valeStyleFiles().map((file) => file.rel).sort(),
    "brand-vale-styles artifacts and the rendered style files have " +
      "drifted apart — declare the rule's file in scripts/canonical_sets.ts " +
      "(and [generated.codegen].paths) with the registry change",
  );
});

Deno.test("every rule's source citations resolve, and an unknown id throws", () => {
  for (const rule of VALE_STYLE_RULES) {
    for (const source of rule.sources) {
      const label = resolveValeSource(source);
      assert(label.length > 0, `${rule.id}: empty provenance label`);
    }
  }
  const unknown = {
    kind: "banned-word",
    word: "no-such-word",
  } as unknown as ValeRuleSource;
  assertThrows(
    () => resolveValeSource(unknown),
    Error,
    "unknown banned word",
    "the resolver must throw on an id the registry no longer declares",
  );
});

Deno.test("every proposed check has exactly one coverage classification", () => {
  assertEquals(
    coveragePartitionIssues(
      PROPOSED_MECHANICAL_CHECKS,
      VALE_STYLE_RULES,
      VALE_DISPOSITIONS,
    ),
    [],
    "the proposed-check partition drifted",
  );
  assertEquals(
    voiceEnforcementCoverage().length,
    REGISTERS.reduce(
      (total, register) => total + PROPOSED_MECHANICAL_CHECKS[register].length,
      0,
    ),
  );
});

Deno.test("a future proposal fails until it receives one classification", () => {
  const future = {
    ...PROPOSED_MECHANICAL_CHECKS,
    brand: [
      ...PROPOSED_MECHANICAL_CHECKS.brand,
      { id: "future-model-smell", text: "future model smell;" },
    ],
  };
  const missing = coveragePartitionIssues(
    future,
    VALE_STYLE_RULES,
    VALE_DISPOSITIONS,
  );
  assertEquals(missing.length, 1);
  assertStringIncludes(missing[0] ?? "", "brand/future-model-smell");

  const classified = coveragePartitionIssues(
    future,
    VALE_STYLE_RULES,
    [
      ...VALE_DISPOSITIONS,
      {
        check: { register: "brand", check: "future-model-smell" },
        disposition: "deferred",
      },
    ],
  );
  assertEquals(classified, []);
});

Deno.test("every coverage citation and generated target exists", async () => {
  const seen = new Set<string>();
  for (const reference of voiceEnforcementReferences()) {
    const key = `${reference.path}#${reference.symbol ?? ""}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const text = await Deno.readTextFile(join(REPO_ROOT, reference.path));
    if (reference.symbol !== undefined) {
      assertStringIncludes(
        text,
        reference.symbol,
        `${key}: cited symbol no longer exists`,
      );
    }
  }
});

Deno.test("the voice enforcement coverage page matches its typed renderer", async () => {
  const rel = VOICE_ENFORCEMENT_COVERAGE_PAGE_REL;
  const path = join(REPO_AUTHORED_PATHS.map, rel);
  assertEquals(
    await Deno.readTextFile(path),
    await canonicalGeneratedMarkdown(
      path,
      renderVoiceEnforcementCoverageDoc(),
    ),
    `${REPO_AUTHORED_PATHS.mapRel}/${rel} is stale — run \`deno task codegen\``,
  );
});

interface GeneratedValeAlert {
  Check?: unknown;
  Severity?: unknown;
}

/** Alerts for one generated-rule fixture, tolerant of temp-path symlinks. */
function generatedFixtureAlerts(
  output: Record<string, unknown>,
  suffix: string,
): GeneratedValeAlert[] {
  const entry = Object.entries(output).find(([path]) => path.endsWith(suffix));
  return Array.isArray(entry?.[1]) ? entry[1] as GeneratedValeAlert[] : [];
}

/** Write one Markdown fixture in the path tier that scopes its register. */
async function writeGeneratedFixture(
  root: string,
  rel: string,
  body: string,
): Promise<void> {
  const path = join(root, rel);
  await Deno.mkdir(dirname(path), { recursive: true });
  await Deno.writeTextFile(path, `# Generated Vale fixture\n\n${body}\n`);
}

Deno.test("every generated Vale rule fires on its bad case and ignores its safe case", async () => {
  await withTempDir(async (dir) => {
    for (const rule of VALE_STYLE_RULES) {
      const base = rule.register === "brand"
        ? `_internal/brand/${rule.id}`
        : `00-orientation/${rule.register}-${rule.id}`;
      await writeGeneratedFixture(dir, `${base}-bad.md`, rule.contract.bad);
      await writeGeneratedFixture(dir, `${base}-safe.md`, rule.contract.safe);
      assert(
        rule.contract.residual.trim().length > 0,
        `${rule.register}/${rule.id}: coverage needs its semantic boundary`,
      );
    }

    const run = await runVale(REPO_ROOT, [
      "--output=JSON",
      "--minAlertLevel=suggestion",
      dir,
    ]);
    const output = JSON.parse(
      new TextDecoder().decode(run.stdout),
    ) as Record<string, unknown>;
    for (const rule of VALE_STYLE_RULES) {
      const base = rule.register === "brand"
        ? `_internal/brand/${rule.id}`
        : `00-orientation/${rule.register}-${rule.id}`;
      const check = `${valeStyleName(rule.register)}.${rule.id}`;
      const bad = generatedFixtureAlerts(output, `${base}-bad.md`);
      const safe = generatedFixtureAlerts(output, `${base}-safe.md`);
      assertEquals(
        bad.find((alert) => alert.Check === check)?.Severity,
        rule.level,
        `${rule.register}/${rule.id}: the real Vale rule must fire at its declared severity`,
      );
      assert(
        !safe.some((alert) => alert.Check === check),
        `${rule.register}/${rule.id}: the safe fixture must not fire ${check}`,
      );
    }
  });
});

Deno.test("every generated pattern survives a source-line wrap", () => {
  // The map hard-wraps prose, so a literal space in a pattern silently
  // misses wrapped instances — the same class the authored style's guard
  // holds (tests/voice_vale_parity_test.ts); the renderer throws on it, and
  // this control proves the predicate discriminates.
  for (const rule of VALE_STYLE_RULES) {
    for (const pattern of valeCheckPatterns(rule.check)) {
      assertEquals(
        valePatternOffences(pattern),
        [],
        `${rule.id}: pattern would miss wrapped instances`,
      );
    }
  }
  assert(
    valePatternOffences("literal space").length > 0,
    "the literal-space predicate no longer discriminates",
  );
  assert(
    valePatternOffences("").length > 0,
    "the empty-pattern predicate no longer discriminates",
  );
});

Deno.test("rule ids are unique per style and PascalCase", () => {
  const seen = new Set<string>();
  for (const rule of VALE_STYLE_RULES) {
    assert(
      /^[A-Z][A-Za-z]+$/.test(rule.id),
      `${rule.id}: a rule id is its Vale check name — PascalCase, letters only`,
    );
    const key = `${rule.register}/${rule.id}`;
    assert(!seen.has(key), `${key} is declared twice`);
    seen.add(key);
  }
});
