/**
 * The private cross-agent behaviour reference stays in lockstep with its
 * canonical registry (`BEHAVIOUR_DIMENSIONS` in
 * `scripts/cross_agent_registry.ts`): the committed page matches the
 * renderer, every dimension renders exactly one numbered section, the
 * headline matrix carries every declared row grouped by category, and every
 * native provider integration has a researched column — so a new provider
 * or dimension auto-enrols here and fails the gate until the research
 * answers for it.
 */

import {
  assert,
  assertEquals,
  assertStringIncludes,
  assertThrows,
} from "@std/assert";
import {
  BEHAVIOUR_CATEGORIES,
  BEHAVIOUR_DIMENSIONS,
  REFERENCE_AGENTS,
  renderCrossAgentReferenceDoc,
  resolveSectionTokens,
} from "../scripts/cross_agent_registry.ts";
import { AGENT_NAMES } from "../src/shared/agent_catalogue.ts";
import { REPO_AUTHORED_PATHS } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";

const PAGE_REL = "_private/research/cross-agent-behaviour-reference.md";
const rendered = renderCrossAgentReferenceDoc();

/** Read the checked-in reference page for generator parity. */
async function committedReference(): Promise<string> {
  return await Deno.readTextFile(`${REPO_AUTHORED_PATHS.map}/${PAGE_REL}`);
}

Deno.test("the committed cross-agent reference matches the registry (run `deno task codegen`)", async () => {
  const path = `${REPO_AUTHORED_PATHS.map}/${PAGE_REL}`;
  assertEquals(
    await committedReference(),
    await canonicalGeneratedMarkdown(path, rendered),
    `${REPO_AUTHORED_PATHS.mapRel}/${PAGE_REL} is stale — run \`deno task codegen\``,
  );
});

Deno.test("the committed reference declares its generated provenance", async () => {
  assertStringIncludes(
    await committedReference(),
    "GENERATED by `deno task codegen`",
    "the committed cross-agent reference lost its generated banner",
  );
});

Deno.test("every native provider integration has a researched column", () => {
  const researched = new Set(
    REFERENCE_AGENTS.flatMap((agent) =>
      agent.nativeName === undefined ? [] : [agent.nativeName]
    ),
  );
  for (const name of AGENT_NAMES) {
    assert(
      researched.has(name),
      `native provider ${name} has no column in the cross-agent reference — ` +
        "research the agent and add its REFERENCE_AGENTS entry " +
        "(scripts/cross_agent_registry.ts)",
    );
  }
  const native = new Set<string>(AGENT_NAMES);
  for (const agent of REFERENCE_AGENTS) {
    if (agent.nativeName !== undefined) {
      assert(
        native.has(agent.nativeName),
        `${agent.id} binds provider ${agent.nativeName}, which the agent ` +
          "catalogue no longer names natively",
      );
    }
  }
});

Deno.test("every dimension renders one numbered section, in declaration order", () => {
  const ids = BEHAVIOUR_DIMENSIONS.map((dimension) => dimension.id);
  assertEquals(new Set(ids).size, ids.length, "dimension ids must be unique");
  const headings = [...rendered.matchAll(/^## (\d+)\. (.+)$/gm)];
  assertEquals(
    headings.length,
    BEHAVIOUR_DIMENSIONS.length,
    "the rendered reference must carry one numbered section per dimension",
  );
  for (const [index, dimension] of BEHAVIOUR_DIMENSIONS.entries()) {
    assertEquals(headings[index]?.[1], String(index + 1));
    assertEquals(headings[index]?.[2], dimension.title);
  }
});

Deno.test("the headline matrix carries every declared row, grouped by category", () => {
  const start = rendered.indexOf("## Headline matrix");
  assert(start >= 0, "the rendered reference lost its headline matrix");
  const end = rendered.indexOf("\n---\n", start);
  assert(end > start, "the headline matrix section never closes");
  const matrix = rendered.slice(start, end);
  const rows = matrix.split("\n").filter((line) => line.startsWith("|"));
  const expectedLabels = BEHAVIOUR_CATEGORIES.flatMap((category) =>
    BEHAVIOUR_DIMENSIONS.filter((dimension) =>
      dimension.category === category.id
    ).flatMap((dimension) => dimension.headline.map((row) => row.label))
  );
  const renderedLabels = rows.slice(2).map((row) => {
    const label = row.split("|")[1];
    assert(label !== undefined, `malformed matrix row: ${row}`);
    return label.trim();
  });
  assertEquals(
    renderedLabels,
    expectedLabels,
    "matrix rows must be the declared headline rows in category order",
  );
});

Deno.test("every category classifies at least one dimension", () => {
  for (const category of BEHAVIOUR_CATEGORIES) {
    assert(
      BEHAVIOUR_DIMENSIONS.some((dimension) =>
        dimension.category === category.id
      ),
      `category ${category.id} classifies nothing — retire it or use it`,
    );
  }
});

Deno.test("section citations resolve, and an unknown citation throws", () => {
  assert(
    !rendered.includes("{{s:"),
    "an authored body carries an unresolved section citation",
  );
  assertThrows(
    () => resolveSectionTokens("{{s:no-such-dimension}}"),
    Error,
    "cites no behaviour dimension",
  );
});
