/**
 * Engine coverage for `discern refresh` — the verb that compiles the agent
 * instruction files (job 1: built-in guidance + the project's `[guidance].sources`)
 * AND materializes skills into `.claude/skills/` (job 2): bundled built-ins are
 * copied in, authored skills (under `[skills].dir`) are symlinked. The two jobs
 * are independent, each gated on its feature, so a project with no authored
 * guidance still gets discoverable skills. These tests pin both jobs under the
 * real dispatcher.
 */

import {
  assert,
  assertEquals,
  assertRejects,
  assertStringIncludes,
} from "@std/assert";
import { join } from "@std/path";
import { ensureDir, exists } from "@std/fs";
import { withTempDir } from "./helpers.ts";
import { runAgent, scaffoldEngine, writeExecutable } from "./engine_helpers.ts";

Deno.test("engine refresh: compiles agent files and materializes bundled skills", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);

    const r = await runAgent(dir, ["refresh"]);
    assertEquals(r.code, 0, r.output);

    // Job 1: the configured agent file (claude_code → CLAUDE.md) was compiled,
    // with the generated banner heading it.
    assert(
      await exists(join(dir, "CLAUDE.md")),
      `CLAUDE.md missing\n${r.output}`,
    );
    const claude = await Deno.readTextFile(join(dir, "CLAUDE.md"));
    assert(
      claude.startsWith("<!-- GENERATED by"),
      `no banner\n${claude.slice(0, 80)}`,
    );

    // Job 2: a bundled built-in is COPIED into .claude/skills/ (a real SKILL.md,
    // not a dangling link) — exactly what the agent reads to discover a skill.
    assert(
      await exists(join(dir, ".claude/skills/handoff-worktree/SKILL.md")),
      `.claude/skills/handoff-worktree must hold a SKILL.md\n${r.output}`,
    );
    assertStringIncludes(r.stdout, "skills materialized into .claude/skills/");
  });
});

Deno.test("engine refresh: materializes skills even with no guideline sources (jobs are independent)", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);
    // A fresh scaffold has no `guidance.md` source at all: job 1 compiles only
    // the built-in guidance, but job 2 (skills) must still run.
    assert(
      !(await exists(join(dir, "guidance.md"))),
      "precondition: no source",
    );

    const r = await runAgent(dir, ["refresh"]);
    assertEquals(r.code, 0, r.output);
    assert(
      await exists(join(dir, ".claude/skills/handoff-worktree/SKILL.md")),
      `skills must materialize independently of guideline compilation\n${r.output}`,
    );
  });
});

Deno.test("engine refresh: compiled agent files are world-readable (0644)", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);

    const r = await runAgent(dir, ["refresh"]);
    assertEquals(r.code, 0, r.output);

    const mode = (await Deno.stat(join(dir, "CLAUDE.md"))).mode ?? 0;
    assertEquals(
      mode & 0o044,
      0o044,
      `CLAUDE.md must be group/other-readable; got mode ${
        (mode & 0o777).toString(8)
      }`,
    );
  });
});

Deno.test("engine refresh: prunes the link of an authored skill removed from the source tree", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);
    // An authored skill under ./skills/ is symlinked into .claude/skills/.
    await writeExecutable(join(dir, "skills/temp/SKILL.md"), "temp skill");

    let r = await runAgent(dir, ["refresh"]);
    assertEquals(r.code, 0, r.output);
    assert(
      await exists(join(dir, ".claude/skills/temp/SKILL.md")),
      `precondition: temp must be linked\n${r.output}`,
    );

    // Remove the authored skill; re-running must prune the now-dangling link.
    await Deno.remove(join(dir, "skills/temp"), { recursive: true });
    r = await runAgent(dir, ["refresh"]);
    assertEquals(r.code, 0, r.output);

    await assertRejects(
      () => Deno.lstat(join(dir, ".claude/skills/temp")),
      Deno.errors.NotFound,
      undefined,
      `stale link must be pruned, not left dangling\n${r.output}`,
    );
    // A bundled built-in keeps its materialized copy.
    assert(
      await exists(join(dir, ".claude/skills/write-adr/SKILL.md")),
      `bundled skills must stay materialized\n${r.output}`,
    );
    assertStringIncludes(r.stdout, "pruned 1 stale");
  });
});

Deno.test("engine refresh: reconcile leaves a foreign entry it did not create alone", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);
    await ensureDir(join(dir, ".claude/skills"));

    // A user's own symlink pointing OUTSIDE the managed set, with a real target.
    await ensureDir(join(dir, "external/shared"));
    await Deno.writeTextFile(
      join(dir, "external/shared/SKILL.md"),
      "shared skill",
    );
    await Deno.symlink(
      "../../external/shared",
      join(dir, ".claude/skills/shared"),
    );

    const r = await runAgent(dir, ["refresh"]);
    assertEquals(r.code, 0, r.output);

    // It is not a managed name and not dangling, so reconcile must leave it.
    const st = await Deno.lstat(join(dir, ".claude/skills/shared"));
    assert(
      st.isSymlink,
      `a user's symlink with a live target must survive reconcile\n${r.output}`,
    );
  });
});
