/**
 * Engine coverage for the maintained ADR index: `discern refresh` regenerates
 * the record lists between markers in the map's ADR README, `discern status`
 * reports drift advisorily, and `discern done` refuses a stale index through
 * the adr_index precondition. Opt-in by construction — a README without the
 * markers is never touched — and the fresh `discern setup` skeleton ships the
 * markers, so a new install gets a working index end-to-end. All black-box,
 * through the real dispatcher.
 */

import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { join } from "@std/path";
import { HINTS } from "../src/shared/hints.ts";
import { assertTerminalTextIncludes, withTempDir } from "./helpers.ts";
import { assertHasHint } from "./hint_asserts.ts";
import {
  defaultMapPath,
  gitInit,
  runAgent,
  scaffoldEngine,
} from "./engine_helpers.ts";

const ADR_README_REL = "discern/map/_adr/README.md";

const MARKED_README = [
  "# Decisions",
  "",
  "<!-- BEGIN GENERATED: current ADR records -->",
  "<!-- Generated by `discern refresh` from the ADR headings on disk. -->",
  "",
  "<!-- END GENERATED: current ADR records -->",
  "",
].join("\n");

/** Create a configured ADR directory with a chosen index and minimal record headings. */
async function writeAdrDir(
  dir: string,
  readme: string,
  records: Record<string, string> = {},
): Promise<string> {
  const adrDir = defaultMapPath(dir, "_adr");
  await Deno.mkdir(adrDir, { recursive: true });
  await Deno.writeTextFile(join(adrDir, "README.md"), readme);
  for (const [name, heading] of Object.entries(records)) {
    await Deno.writeTextFile(join(adrDir, name), `${heading}\n`);
  }
  return adrDir;
}

Deno.test("engine adr-index: refresh writes the index from the records, and a new record updates it", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);
    const adrDir = await writeAdrDir(dir, MARKED_README, {
      "0001-first-choice.md": "# ADR 0001: A first choice",
    });

    const first = await runAgent(dir, ["refresh", "--json"]);
    assertEquals(first.code, 0, first.output);
    assertEquals(
      JSON.parse(first.stdout).data.adr_index_written,
      [ADR_README_REL],
      first.stdout,
    );
    const indexed = await Deno.readTextFile(join(adrDir, "README.md"));
    assertStringIncludes(
      indexed,
      "[0001 — A first choice](0001-first-choice.md)",
    );

    // Idempotent: a second refresh over the current index writes nothing.
    const unchanged = await runAgent(dir, ["refresh", "--json"]);
    assertEquals(unchanged.code, 0, unchanged.output);
    assertEquals(JSON.parse(unchanged.stdout).data.adr_index_written, []);

    // A newly added record enrols on the next refresh — the directory is the
    // canonical set, never the list itself.
    await Deno.writeTextFile(
      join(adrDir, "0002-second-choice.md"),
      "# ADR 0002: A second choice\n",
    );
    const second = await runAgent(dir, ["refresh", "--json"]);
    assertEquals(second.code, 0, second.output);
    assertEquals(
      JSON.parse(second.stdout).data.adr_index_written,
      [ADR_README_REL],
    );
    assertStringIncludes(
      await Deno.readTextFile(join(adrDir, "README.md")),
      "[0002 — A second choice](0002-second-choice.md)",
    );
  });
});

Deno.test("engine adr-index: a README without markers is never touched — opt-in by construction", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);
    const authored =
      "# Decisions\n\nAn authored page that never adopted the index.\n";
    const adrDir = await writeAdrDir(dir, authored, {
      "0001-first-choice.md": "# ADR 0001: A first choice",
    });

    const r = await runAgent(dir, ["refresh", "--json"]);
    assertEquals(r.code, 0, r.output);
    assertEquals(JSON.parse(r.stdout).data.adr_index_written, []);
    assertEquals(
      await Deno.readTextFile(join(adrDir, "README.md")),
      authored,
      "refresh must leave a marker-less README byte-identical",
    );
  });
});

Deno.test("engine adr-index: a stale index surfaces in status and refuses the gate until refreshed", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);
    await gitInit(dir);
    // Markers present, list empty, record on disk → the index is stale.
    await writeAdrDir(dir, MARKED_README, {
      "0001-first-choice.md": "# ADR 0001: A first choice",
    });

    // status: advisory — the structured field plus the generated-drift hint.
    const status = await runAgent(dir, ["status", "--json"]);
    assertEquals(status.code, 0, status.output);
    const statusObj = JSON.parse(status.stdout);
    assertEquals(statusObj.data.stale_adr_index, [ADR_README_REL]);
    assertHasHint(statusObj, HINTS["adr-index-stale"], {
      path: ADR_README_REL,
    });

    // done: the adr_index precondition blocks with the refresh remedy.
    const red = await runAgent(dir, ["done", "--json"]);
    assertEquals(red.code, 1, red.output);
    const redObj = JSON.parse(red.stdout);
    assertEquals(redObj.data.failed_stage, "adr_index");
    const diag = (redObj.diagnostics ?? []).find(
      (d: { tool: string }) => d.tool === "adr-index",
    );
    assert(
      diag !== undefined,
      `expected an adr-index diagnostic: ${red.stdout}`,
    );
    assertEquals(diag.reproduce_cmd, "discern refresh");
    assertStringIncludes(diag.message, ADR_README_REL);
    assertHasHint(redObj, HINTS["gate-failure-adr-index"]);

    // refresh heals it; the gate then passes.
    const healed = await runAgent(dir, ["refresh", "--json"]);
    assertEquals(healed.code, 0, healed.output);
    assertEquals(
      JSON.parse(healed.stdout).data.adr_index_written,
      [ADR_README_REL],
    );
    const green = await runAgent(dir, ["done", "--json"]);
    assertEquals(green.code, 0, green.output);
  });
});

Deno.test("engine adr-index: a record the derivation cannot title fails the gate naming the record", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);
    await gitInit(dir);
    await writeAdrDir(dir, MARKED_README, {
      "0001-first-choice.md": "# a heading with no record number",
    });

    const r = await runAgent(dir, ["done", "--json"]);
    assertEquals(r.code, 1, r.output);
    const obj = JSON.parse(r.stdout);
    assertEquals(obj.data.failed_stage, "adr_index");
    const diag = (obj.diagnostics ?? []).find(
      (d: { tool: string }) => d.tool === "adr-index",
    );
    assert(diag !== undefined, `expected an adr-index diagnostic: ${r.stdout}`);
    assertStringIncludes(diag.output, "0001-first-choice.md");
    assertTerminalTextIncludes(diag.output, "first heading");
  });
});

Deno.test("engine adr-index: a marker pair missing its end marker points the remedy at the README, not a record", async () => {
  await withTempDir(async (dir) => {
    await scaffoldEngine(dir);
    await gitInit(dir);
    // The BEGIN marker survives a bad edit; the END marker is gone. The record
    // file is fine, so the remedy must name the README's marker pair.
    await writeAdrDir(
      dir,
      "# Decisions\n\n<!-- BEGIN GENERATED: current ADR records -->\n",
      { "0001-first-choice.md": "# ADR 0001: A first choice" },
    );

    const r = await runAgent(dir, ["done", "--json"]);
    assertEquals(r.code, 1, r.output);
    const obj = JSON.parse(r.stdout);
    assertEquals(obj.data.failed_stage, "adr_index");
    const diag = (obj.diagnostics ?? []).find(
      (d: { tool: string }) => d.tool === "adr-index",
    );
    assert(diag !== undefined, `expected an adr-index diagnostic: ${r.stdout}`);
    assertStringIncludes(diag.message, ADR_README_REL);
    assertTerminalTextIncludes(
      diag.output,
      "END GENERATED: current ADR records",
    );
    assertTerminalTextIncludes(
      diag.output,
      `Repair the marker pair in ${ADR_README_REL}`,
    );
    assert(
      !diag.output.includes("Fix the named record file"),
      `a mangled pair must not point the reader at a record file:\n${diag.output}`,
    );
  });
});

Deno.test("engine adr-index: the fresh setup skeleton yields a working index end-to-end", async () => {
  await withTempDir(async (dir) => {
    const setup = await runAgent(dir, [
      "setup",
      "begin",
      "--confirmed",
      "--agents",
      "claude_code",
    ]);
    assertEquals(setup.code, 0, setup.output);
    const readmePath = defaultMapPath(dir, "_adr", "README.md");
    const skeleton = await Deno.readTextFile(readmePath);
    assertStringIncludes(
      skeleton,
      "<!-- BEGIN GENERATED: current ADR records -->",
    );

    // The scaffolded empty index is born current: refresh rewrites nothing.
    const current = await runAgent(dir, ["refresh", "--json"]);
    assertEquals(current.code, 0, current.output);
    assertEquals(JSON.parse(current.stdout).data.adr_index_written, []);
    assertEquals(await Deno.readTextFile(readmePath), skeleton);

    // The first real record flows into the index on the next refresh.
    await Deno.writeTextFile(
      defaultMapPath(dir, "_adr", "0001-first-choice.md"),
      "# ADR 0001: A first choice\n",
    );
    const r = await runAgent(dir, ["refresh", "--json"]);
    assertEquals(r.code, 0, r.output);
    assertEquals(
      JSON.parse(r.stdout).data.adr_index_written,
      [ADR_README_REL],
    );
    assertStringIncludes(
      await Deno.readTextFile(readmePath),
      "[0001 — A first choice](0001-first-choice.md)",
    );
  });
});
