import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { join } from "@std/path";
import {
  agentExperienceNodes,
  allFeatureNodes,
  allSurfaceClaims,
  FEATURE_CANON,
  FEATURE_CANON_PAGE_REL,
  FEATURE_CANON_PLAIN_PAGE_REL,
  parseSurfaceKey,
  renderFeatureCanonDoc,
  renderFeatureCanonPlainDoc,
} from "../scripts/feature_registry.ts";
import { KNOWN_VERBS } from "../src/engine/dispatch.ts";
import { REPO_AUTHORED_PATHS } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";

// These prove the committed canon page stays in lockstep with the feature
// registry (the same drift-guard discipline as the glossary and the CLI and
// config references): a registry change that isn't regenerated
// (`deno task codegen`) fails here, in the gate's test stage.

Deno.test("the configured map's feature canon matches the generator (run `deno task codegen`)", async () => {
  const path = join(REPO_AUTHORED_PATHS.map, FEATURE_CANON_PAGE_REL);
  const committed = await Deno.readTextFile(path);
  assertEquals(
    committed,
    await canonicalGeneratedMarkdown(path, renderFeatureCanonDoc()),
    `${
      join(REPO_AUTHORED_PATHS.mapRel, FEATURE_CANON_PAGE_REL)
    } is stale — run \`deno task codegen\``,
  );
});

Deno.test("the configured map's plain-language canon matches the generator (run `deno task codegen`)", async () => {
  const path = join(REPO_AUTHORED_PATHS.map, FEATURE_CANON_PLAIN_PAGE_REL);
  const committed = await Deno.readTextFile(path);
  assertEquals(
    committed,
    await canonicalGeneratedMarkdown(path, renderFeatureCanonPlainDoc()),
    `${
      join(REPO_AUTHORED_PATHS.mapRel, FEATURE_CANON_PLAIN_PAGE_REL)
    } is stale — run \`deno task codegen\``,
  );
});

Deno.test("every id is unique and kebab-case, and every node states a complete sentence", () => {
  const seen = new Set<string>();
  for (const { node } of allFeatureNodes()) {
    assert(!seen.has(node.id), `duplicate feature id: ${node.id}`);
    seen.add(node.id);
    assert(
      /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(node.id),
      `feature id is not kebab-case: ${node.id}`,
    );
    assert(node.title.trim().length > 0, `empty title for: ${node.id}`);
    assert(
      !node.title.endsWith("."),
      `title carries a trailing period: ${node.id}`,
    );
    assert(
      /[.!?]$/u.test(node.what.trim()),
      `"what" is not a complete sentence for: ${node.id}`,
    );
    if (node.why !== undefined) {
      assert(
        /[.!?]$/u.test(node.why.trim()),
        `"why" is not a complete sentence for: ${node.id}`,
      );
    }
    if (node.agent !== undefined) {
      assert(
        /[.!?]$/u.test(node.agent.trim()),
        `"agent" is not a complete sentence for: ${node.id}`,
      );
    }
    if (node.hints !== undefined) {
      assert(
        node.agent !== undefined,
        `hint citations ride an agent-experience account, but ${node.id} has none`,
      );
      assert(node.hints.length > 0, `empty hints list on: ${node.id}`);
    }
  }
});

Deno.test("every plain account is complete and in parity with its technical twin", () => {
  for (const { node } of allFeatureNodes()) {
    assert(
      node.plain.title.trim().length > 0,
      `empty plain title for: ${node.id}`,
    );
    assert(
      !node.plain.title.endsWith("."),
      `plain title carries a trailing period: ${node.id}`,
    );
    assert(
      /[.!?]$/u.test(node.plain.what.trim()),
      `plain "what" is not a complete sentence for: ${node.id}`,
    );
    assertEquals(
      node.plain.why !== undefined,
      node.why !== undefined,
      `plain "why" must exist exactly when the technical "why" does: ${node.id}`,
    );
    assertEquals(
      node.plain.agent !== undefined,
      node.agent !== undefined,
      `plain "agent" must exist exactly when the technical "agent" does: ${node.id}`,
    );
    if (node.plain.why !== undefined) {
      assert(
        /[.!?]$/u.test(node.plain.why.trim()),
        `plain "why" is not a complete sentence for: ${node.id}`,
      );
    }
    if (node.plain.agent !== undefined) {
      assert(
        /[.!?]$/u.test(node.plain.agent.trim()),
        `plain "agent" is not a complete sentence for: ${node.id}`,
      );
    }
  }
});

Deno.test("every pillar states its benefit and decomposes at least one level", () => {
  for (const pillar of FEATURE_CANON) {
    assert(
      pillar.why !== undefined && pillar.why.trim().length > 0,
      `pillar ${pillar.id} has no "why" — every pillar states its benefit`,
    );
    assert(
      (pillar.children ?? []).length > 0,
      `pillar ${pillar.id} has no children — a pillar is a category, not a leaf`,
    );
  }
});

Deno.test("the rendered page carries the banner, every node, and the coverage appendix", () => {
  const doc = renderFeatureCanonDoc();
  assertStringIncludes(doc, "<!-- GENERATED by `deno task codegen`");
  for (const { node } of allFeatureNodes()) {
    assertStringIncludes(
      doc,
      `**${node.title}**`,
      `no rendering for node: ${node.id}`,
    );
  }
  for (const claim of allSurfaceClaims()) {
    assertStringIncludes(
      doc,
      `- \`${claim.member}\` — `,
      `coverage appendix misses claimed member: ${claim.set}:${claim.member}`,
    );
  }
});

Deno.test("benefit nodes are marked in the rendered tree", () => {
  const doc = renderFeatureCanonDoc();
  const benefits = allFeatureNodes().filter(({ node }) =>
    node.kind === "benefit"
  );
  assert(benefits.length > 0, "the canon carries benefit nodes by design");
  for (const { node } of benefits) {
    assertStringIncludes(
      doc,
      `**${node.title}** *(benefit)*`,
      `benefit node renders unmarked: ${node.id}`,
    );
  }
});

Deno.test("agent-experience accounts render marked, indexed, and counted", () => {
  const doc = renderFeatureCanonDoc();
  const carriers = agentExperienceNodes();
  if (carriers.length === 0) return;
  assertStringIncludes(doc, "## The agent's-eye view");
  assertStringIncludes(doc, ` · ${carriers.length} agent-experience accounts`);
  for (const { node } of carriers) {
    assertStringIncludes(
      doc,
      `**Agent:** *${node.agent}*`,
      `agent account renders unmarked: ${node.id}`,
    );
  }
});

// Every `discern <verb>` mention in canon prose must name a live verb — the
// same command-reference discipline the hint corpus and the map's fenced
// examples are held to, so a rename fails the canon mechanically.

const COMMAND_MENTION = /`discern ([a-z][a-z-]*)/g;

function mentionedVerbs(text: string): string[] {
  return [...text.matchAll(COMMAND_MENTION)].map((m) => m[1] ?? "");
}

Deno.test("every discern command mentioned in canon prose is a live verb", () => {
  for (const { node } of allFeatureNodes()) {
    const texts = [
      node.what,
      node.why ?? "",
      node.agent ?? "",
      node.plain.title,
      node.plain.what,
      node.plain.why ?? "",
      node.plain.agent ?? "",
    ];
    for (const text of texts) {
      for (const verb of mentionedVerbs(text)) {
        assert(
          KNOWN_VERBS.has(verb),
          `node ${node.id} mentions \`discern ${verb}\`, which is not a live verb`,
        );
      }
    }
  }
});

Deno.test("the rendered plain page carries the banner, every node, and the coverage appendix", () => {
  const doc = renderFeatureCanonPlainDoc();
  assertStringIncludes(doc, "<!-- GENERATED by `deno task codegen`");
  assertStringIncludes(doc, "# The complete feature guide");
  for (const { node } of allFeatureNodes()) {
    assertStringIncludes(
      doc,
      `**${node.plain.title}**`,
      `no plain rendering for node: ${node.id}`,
    );
  }
  for (const claim of allSurfaceClaims()) {
    assertStringIncludes(
      doc,
      `- \`${claim.member}\` — `,
      `plain coverage appendix misses claimed member: ${claim.set}:${claim.member}`,
    );
  }
});

Deno.test("plain agent accounts render marked as Coding agent, benefits marked, tips cited", () => {
  const doc = renderFeatureCanonPlainDoc();
  const carriers = agentExperienceNodes();
  if (carriers.length > 0) {
    assertStringIncludes(doc, "## What the coding agent sees");
    assertStringIncludes(
      doc,
      ` · ${carriers.length} accounts of what the coding agent experiences`,
    );
    for (const { node } of carriers) {
      assertStringIncludes(
        doc,
        `**Coding agent:** _${node.plain.agent}_`,
        `plain agent account renders unmarked: ${node.id}`,
      );
    }
    // Hints render in the plain register as tips, singular and plural.
    assertStringIncludes(doc, "(tip: `");
    assertStringIncludes(doc, "(tips: `");
  }
  for (
    const { node } of allFeatureNodes().filter(({ node }) =>
      node.kind === "benefit"
    )
  ) {
    assertStringIncludes(
      doc,
      `**${node.plain.title}** _(benefit)_`,
      `plain benefit node renders unmarked: ${node.id}`,
    );
  }
});

Deno.test("command-mention extraction discriminates (positive controls)", () => {
  assertEquals(mentionedVerbs("run `discern done` then `discern accept`"), [
    "done",
    "accept",
  ]);
  assertEquals(mentionedVerbs("`discern worktree prune` reclaims"), [
    "worktree",
  ]);
  assertEquals(
    mentionedVerbs("bare `discern` opens the desk; `discern.toml` is config"),
    [],
  );
});

Deno.test("surface keys parse and malformed keys fail loudly", () => {
  assertEquals(parseSurfaceKey("verb:done"), { set: "verb", member: "done" });
  assertEquals(parseSurfaceKey("no-colon"), undefined);
  // The tree's own claims all parse — allSurfaceClaims throws otherwise.
  assert(allSurfaceClaims().length > 0, "the canon claims surfaces by design");
});
