import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { join } from "@std/path";
import { compileGuidelines } from "../src/engine/guidelines.ts";

/** Scaffold a temp project with an icculus.toml, a guidance source, and one
 * authored skill (under ./skills/). Built-in guidance + bundled skills come from
 * the repo's own templates/ tree (resolved by the compiler). */
async function scaffold(): Promise<string> {
  const tmp = await Deno.makeTempDir({ prefix: "icculus-guidelines-test-" });
  await Deno.writeTextFile(
    join(tmp, "icculus.toml"),
    [
      "[guidance]",
      'agents = ["claude_code", "codex"]',
      'sources = ["guidance.md"]',
      "[skills]",
      'dir = "skills"',
      "",
    ].join("\n"),
  );
  await Deno.writeTextFile(
    join(tmp, "guidance.md"),
    "# Project guidance\nMy own rule.\n",
  );
  await Deno.mkdir(join(tmp, "skills/demo"), { recursive: true });
  await Deno.writeTextFile(join(tmp, "skills/demo/SKILL.md"), "demo skill");
  return tmp;
}

Deno.test("compileGuidelines: banner + built-in + sources; copies built-ins, symlinks authored, prunes", async () => {
  const tmp = await scaffold();
  try {
    const first = await compileGuidelines(tmp);
    // Provider files written in [guidance].agents order.
    assertEquals(first.agentsWritten, ["CLAUDE.md", "AGENTS.md"]);
    // The authored demo is symlinked; the bundled built-ins are copied.
    assertEquals(first.skillsLinked, 1);
    assert(first.skillsCopied >= 1, "expected bundled built-ins to be copied");
    assertEquals(first.skillsPruned, 0);

    const claude = await Deno.readTextFile(join(tmp, "CLAUDE.md"));
    // A generated banner heads the file.
    assert(
      claude.startsWith("<!-- GENERATED by"),
      "expected a generated banner",
    );
    // icculus's built-in harness guidance is prepended (the base section names
    // the gate command), then the user's own guidance.md is appended after it.
    assertStringIncludes(claude, "icculus finish");
    assertStringIncludes(claude, "My own rule.");
    assert(
      claude.indexOf("icculus finish") < claude.indexOf("My own rule."),
      "built-in guidance should come before the user's sources",
    );
    // AGENTS.md mirrors CLAUDE.md exactly.
    assertEquals(await Deno.readTextFile(join(tmp, "AGENTS.md")), claude);

    // The authored skill is a relative symlink into ./skills/.
    const link = join(tmp, ".claude/skills/demo");
    assert((await Deno.lstat(link)).isSymlink, "expected a symlink");
    assertEquals(await Deno.readLink(link), "../../skills/demo");
    // A bundled built-in is copied in as a real directory (not a symlink).
    const bootstrap = await Deno.lstat(join(tmp, ".claude/skills/bootstrap"));
    assert(bootstrap.isDirectory && !bootstrap.isSymlink);

    // --- prune: remove the authored skill, re-run → the dangling link is gone --
    await Deno.remove(join(tmp, "skills/demo"), { recursive: true });
    const second = await compileGuidelines(tmp);
    assertEquals(second.skillsLinked, 0);
    assertEquals(second.skillsPruned, 1);
    assertEquals(
      await Deno.lstat(link).then(() => true).catch(() => false),
      false,
      "expected the dangling skill link to be pruned",
    );
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});
