/**
 * The committed internal hint inventory stays in lockstep with HINTS. A new
 * entry auto-enrols in both the page and this guard; hand edits drift at once.
 */

import { renderCommandRefsCli } from "../src/shared/command_reference.ts";
import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { renderHintInventoryDoc } from "../src/shared/hint_inventory_codegen.ts";
import { type HintDef, HINTS } from "../src/shared/hints.ts";
import { REPO_AUTHORED_PATHS } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";

const rendered = renderHintInventoryDoc();
const defs = Object.values(HINTS) as unknown as readonly HintDef<unknown>[];

/** Read the checked-in internal hint inventory for generator parity. */
async function committedInventory(): Promise<string> {
  return await Deno.readTextFile(
    `${REPO_AUTHORED_PATHS.map}/_internal/hint-inventory.md`,
  );
}

Deno.test("the configured map's hint inventory matches the generator (run `deno task codegen`)", async () => {
  const path = `${REPO_AUTHORED_PATHS.map}/_internal/hint-inventory.md`;
  assertEquals(
    await committedInventory(),
    await canonicalGeneratedMarkdown(path, rendered),
    `${REPO_AUTHORED_PATHS.mapRel}/_internal/hint-inventory.md is stale — run \`deno task codegen\``,
  );
});

Deno.test("the hint inventory is total over HINTS and renders every example", () => {
  const expectedIds = defs.map((def) => def.id).sort();
  const headings = [...rendered.matchAll(/^## `([^`]+)`$/gm)];
  const renderedIds = headings.map((match) => match[1] ?? "");
  assertEquals(
    renderedIds,
    expectedIds,
    "the generated inventory must contain one id-sorted section per hint",
  );

  const byId = new Map(defs.map((def) => [def.id, def]));
  for (const [index, heading] of headings.entries()) {
    const id = heading[1] ?? "";
    const def = byId.get(id);
    assert(def !== undefined, `inventory contains unknown hint ${id}`);
    const when = def.when?.trim();
    assert(when !== undefined && when !== "", `${def.id} needs a when value`);
    assert(!/[\r\n]/.test(when), `${def.id}.when must stay on one line`);
    const start = heading.index ?? 0;
    const end = headings[index + 1]?.index ?? rendered.length;
    const section = rendered.slice(start, end);
    assertStringIncludes(section, `- Category: \`${def.category}\``);
    assertStringIncludes(section, `- Audience: \`${def.audience}\``);
    assertStringIncludes(
      section,
      `- Family: ${def.family === undefined ? "—" : `\`${def.family}\``}`,
    );
    assertStringIncludes(section, `- Emitting context: ${when}`);
    const canonical = renderCommandRefsCli(def.template(def.example));
    assertStringIncludes(section, canonical);
    const interactive = def.interactiveTemplate === undefined
      ? undefined
      : renderCommandRefsCli(def.interactiveTemplate(def.example));
    if (interactive !== undefined && interactive !== canonical) {
      assertStringIncludes(section, "Interactive example:");
      assertStringIncludes(section, interactive);
    }
  }
});

Deno.test("the committed hint inventory declares its generated provenance", async () => {
  assertStringIncludes(
    await committedInventory(),
    "GENERATED by `deno task codegen`",
    "the committed hint inventory lost its generated banner",
  );
});
