/**
 * The install corpus proves ADR 0014's keystone invariant on real captured
 * installations: an installation captured at a past schema and brought
 * forward by `discern upgrade` matches a fresh installation from the current
 * build in everything discern maintains. The comparison follows the
 * file-ownership registry: Generated and Shared artifacts converge byte for
 * byte, `discern.toml` converges in its managed projection, and project-owned
 * seeds are the project's and converge by presence. The corpus itself is
 * frozen by its manifests, and `SCHEMA_VERSION` cannot advance past the newest
 * captured schema plus one.
 */

import { assert, assertEquals, assertExists, assertMatch } from "@std/assert";
import { dirname, join } from "@std/path";
import {
  type ArtifactPathEntry,
  artifactPathMatches,
  projectArtifactPaths,
} from "../src/lib/artifact_ownership.ts";
import { scanRuledBanners } from "../src/lib/config_banners.ts";
import { parseDiscernToml } from "../src/lib/toml_render.ts";
import { DISCERN_VERSION, SCHEMA_VERSION } from "../src/lib/version.ts";
import { isGeneratedArtifactMarker } from "../src/shared/brand.ts";
import { parseConfigOrThrow } from "../src/shared/config_schema.ts";
import { CONFIG_REL } from "../src/shared/env.ts";
import {
  ARTIFACT_PROVENANCE_SOURCES,
  declaredFileOwnership,
} from "../src/shared/file_ownership.ts";
import { CAPTURE_COMMAND } from "../scripts/capture_install_fixture.ts";
import { assertResultDataKey, decodeCliResult } from "./decode_cli_result.ts";
import { git, gitInit, runAgent } from "./engine_helpers.ts";
import { withTempDir } from "./helpers.ts";
import {
  FIXTURE_MANIFEST,
  freshInstall,
  INSTALL_CORPUS_REL,
  type InstallFixture,
  installFixtures,
  readSnapshot,
  snapshotTree,
  type TreeEntry,
} from "./install_corpus.ts";
import { structuralGuardScope } from "./structural_guard_scope.ts";

/** The setup-provenance header line a rendered config carries. */
const PROVENANCE_HEADER = /^# Generated by discern (\S+) for "/mu;

/** How one path is compared, chosen from the file-ownership registry. */
type Comparison = "managed-config" | "exact" | "presence";

/** The parts of a config discern maintains: schema directive, provenance marker, ruled banners, and values. */
interface ManagedConfigState {
  readonly directive: string | undefined;
  readonly marker: string | undefined;
  readonly banners: readonly string[];
  readonly values: Record<string, unknown>;
}

/** True for a non-null, non-array object. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Choose the comparison for one path: discern-maintained bytes exactly, project-owned content by presence. */
function comparisonFor(
  rel: string,
  entries: readonly ArtifactPathEntry[],
): Comparison {
  if (rel === CONFIG_REL) return "managed-config";
  const entry = entries.find((candidate) =>
    artifactPathMatches(candidate, rel)
  );
  if (entry === undefined) return "presence";
  const ownership = declaredFileOwnership(entry);
  return ownership === "shared" || ownership === "generated"
    ? "exact"
    : "presence";
}

/** Project a config onto its discern-managed state; comments outside ruled banners are the project's. */
function managedConfigState(text: string): ManagedConfigState {
  const lines = text.split("\n");
  const first = lines[0] ?? "";
  return {
    directive: first.startsWith("#:schema ") ? first : undefined,
    marker: lines.find((line) =>
      isGeneratedArtifactMarker(line, ARTIFACT_PROVENANCE_SOURCES.config)
    ),
    banners: scanRuledBanners(text).map((span) =>
      lines.slice(span.start, span.end + 1).join("\n")
    ),
    values: parseDiscernToml(text).raw,
  };
}

/**
 * Assert and set aside the two `[meta]` values that legitimately differ:
 * setup provenance names the release that ran setup and survives upgrade;
 * adoption is recorded by completion or upgrade, never by setup begin.
 */
function withoutProvenance(
  state: ManagedConfigState,
  expected: { setupVersion: string; managedVersion: string | undefined },
): ManagedConfigState {
  const meta = state.values.meta;
  assert(isRecord(meta), "the config records a [meta] table");
  assertEquals(meta.setup_version, expected.setupVersion);
  assertEquals(meta.managed_version, expected.managedVersion);
  const rest = { ...meta };
  delete rest.setup_version;
  delete rest.managed_version;
  assertExists(state.directive, "the config opens with its schema directive");
  assertExists(state.marker, "the config carries its provenance marker");
  return { ...state, values: { ...state.values, meta: rest } };
}

/** Describe the first line where two texts differ. */
function firstDifference(left: string, right: string): string {
  const leftLines = left.split("\n");
  const rightLines = right.split("\n");
  const limit = Math.max(leftLines.length, rightLines.length);
  for (let index = 0; index < limit; index++) {
    if (leftLines[index] !== rightLines[index]) {
      return `line ${index + 1}\n    upgraded: ${
        leftLines[index] ?? "<end of file>"
      }\n    fresh:    ${rightLines[index] ?? "<end of file>"}`;
    }
  }
  return "identical text";
}

/** Compare two installation snapshots path by path under the ownership-derived comparisons. */
function convergenceProblems(
  fixture: InstallFixture,
  entries: readonly ArtifactPathEntry[],
  upgraded: Map<string, TreeEntry>,
  fresh: Map<string, TreeEntry>,
): string[] {
  const problems: string[] = [];
  const paths = [...new Set([...upgraded.keys(), ...fresh.keys()])].sort();
  for (const path of paths) {
    const left = upgraded.get(path);
    const right = fresh.get(path);
    if (left === undefined || right === undefined) {
      problems.push(
        `${path}: only in the ${
          left === undefined ? "fresh" : "upgraded"
        } installation`,
      );
      continue;
    }
    const comparison = comparisonFor(path, entries);
    if (comparison === "presence") continue;
    if (left.executable !== right.executable) {
      problems.push(`${path}: executable bit differs`);
    }
    const texts = comparison === "exact"
      ? { upgraded: left.text, fresh: right.text }
      : {
        upgraded: JSON.stringify(
          withoutProvenance(managedConfigState(left.text), {
            setupVersion: fixture.manifest.discern_version,
            managedVersion: DISCERN_VERSION,
          }),
          null,
          2,
        ),
        fresh: JSON.stringify(
          withoutProvenance(managedConfigState(right.text), {
            setupVersion: DISCERN_VERSION,
            managedVersion: undefined,
          }),
          null,
          2,
        ),
      };
    if (texts.upgraded !== texts.fresh) {
      problems.push(
        `${path} (${comparison}): differs at ${
          firstDifference(texts.upgraded, texts.fresh)
        }`,
      );
    }
  }
  return problems;
}

/** Restore a fixture's captured installation into a committed Git repository named like the capture. */
async function restoreFixture(
  fixture: InstallFixture,
  snapshot: Readonly<Record<string, string>>,
  temp: string,
): Promise<string> {
  const root = join(temp, fixture.manifest.project_directory);
  await Deno.mkdir(root);
  for (const [rel, text] of Object.entries(fixture.manifest.seed)) {
    await Deno.mkdir(dirname(join(root, rel)), { recursive: true });
    await Deno.writeTextFile(join(root, rel), text);
  }
  await gitInit(root);
  for (const [rel, text] of Object.entries(snapshot)) {
    await Deno.mkdir(dirname(join(root, rel)), { recursive: true });
    await Deno.writeTextFile(join(root, rel), text);
  }
  await git(root, "add", "-A");
  await git(root, "commit", "-q", "-m", "install discern", "--no-gpg-sign");
  return root;
}

Deno.test("SCHEMA_VERSION cannot advance past the newest captured schema plus one", async () => {
  const fixtures = await installFixtures();
  const schemas = fixtures.map((fixture) => fixture.manifest.schema);
  assertEquals(
    schemas,
    schemas.map((_, index) => index + 1),
    "every schema that was ever current keeps its captured installation",
  );
  const newest = schemas.at(-1);
  assertExists(newest, "the corpus starts at schema 1");
  assert(
    SCHEMA_VERSION <= newest + 1,
    `SCHEMA_VERSION is ${SCHEMA_VERSION} but the newest captured installation is schema ${newest}; capture schema ${
      SCHEMA_VERSION - 1
    } with \`${CAPTURE_COMMAND}\` before raising the schema again`,
  );
});

Deno.test("every captured installation is archived and frozen by its manifest", async () => {
  const fixtures = await installFixtures();
  // Only the manifest is loose text: the installation stays archived so
  // repository searches find live sources rather than the capture.
  const listed = await structuralGuardScope({
    guard: "tests/install_corpus_test.ts#frozen-fixture-members",
    universe: {
      kind: "specialized",
      name: "text including install fixtures",
      text: true,
      reason:
        "Captured installations are inert fixture data outside the authored-text universe.",
    },
    narrow: {
      reason:
        "The corpus holds only a plaintext manifest beside each archived installation.",
      include: (rel) => rel.startsWith(`${INSTALL_CORPUS_REL}/schema-`),
    },
  });
  assertEquals(
    listed,
    fixtures.map((fixture) => `${fixture.rel}/${FIXTURE_MANIFEST}`),
  );
  for (const fixture of fixtures) {
    assertEquals(fixture.manifest.reproduce, CAPTURE_COMMAND);
    const snapshot = await readSnapshot(fixture);
    const config = snapshot[CONFIG_REL];
    assertExists(config, "a captured installation records its config");
    assertMatch(
      config,
      new RegExp(`^\\s*schema_version = ${fixture.manifest.schema}$`, "mu"),
    );
    assertEquals(
      config.match(PROVENANCE_HEADER)?.[1],
      fixture.manifest.discern_version,
    );
  }
});

/** Model an installation from captured files, with one file's text replaced. */
function modelled(
  snapshot: Readonly<Record<string, string>>,
  edits: Readonly<Record<string, string | undefined>>,
): Map<string, TreeEntry> {
  const tree = new Map<string, TreeEntry>();
  for (const [rel, text] of Object.entries({ ...snapshot, ...edits })) {
    if (text !== undefined) tree.set(rel, { executable: false, text });
  }
  return tree;
}

Deno.test("the ownership comparison flags managed drift and tolerates project-owned edits", async () => {
  const fixture = (await installFixtures())[0];
  assertExists(fixture);
  const snapshot = await readSnapshot(fixture);
  const config = snapshot[CONFIG_REL];
  assertExists(config);
  const entries = projectArtifactPaths(parseConfigOrThrow(config));
  // Model the upgraded side: upgrade records adoption; setup begin does not.
  const adopted = config.replace(
    /^(\s*)schema_version = (\d+)$/mu,
    `$1schema_version = $2\n$1managed_version = "${DISCERN_VERSION}"`,
  );
  assert(adopted !== config, "the modelled upgrade recorded adoption");
  const upgraded = modelled(snapshot, { [CONFIG_REL]: adopted });
  const problemsWith = (
    edits: Readonly<Record<string, string | undefined>>,
  ): string[] =>
    convergenceProblems(fixture, entries, upgraded, modelled(snapshot, edits));

  assertEquals(problemsWith({}), []);
  // Project-owned content may differ: a polished key comment, a changed seed.
  const keyComment = "# Short, lowercase, dash-separated identity";
  assert(config.includes(keyComment));
  assertEquals(
    problemsWith({
      [CONFIG_REL]: config.replace(keyComment, "# A polished key comment"),
      "discern/instructions.md": "# Rewritten seed\n",
    }),
    [],
  );
  // Managed state may not: a banner, a value, a generated file, a missing file.
  const banner = "# Help:    `discern config explain project`";
  assert(config.includes(banner));
  const drifted = [
    problemsWith({ [CONFIG_REL]: config.replace(banner, "# Help: elsewhere") }),
    problemsWith({
      [CONFIG_REL]: config.replace('slug = "demo"', 'slug = "other"'),
    }),
    problemsWith({ "AGENTS.md": "# Different agent file\n" }),
    problemsWith({ ".mcp.json": undefined }),
  ];
  assertEquals(drifted.map((problems) => problems.length), [1, 1, 1, 1]);
  assertMatch(drifted[0]?.[0] ?? "", /^discern\.toml \(managed-config\)/u);
  assertMatch(drifted[1]?.[0] ?? "", /^discern\.toml \(managed-config\)/u);
  assertMatch(drifted[2]?.[0] ?? "", /^AGENTS\.md \(exact\)/u);
  assertMatch(drifted[3]?.[0] ?? "", /^\.mcp\.json: only in the upgraded/u);
});

Deno.test("every captured installation upgraded by this build converges with a fresh installation", async () => {
  for (const fixture of await installFixtures()) {
    const snapshot = await readSnapshot(fixture);
    await withTempDir(async (upgradeTemp) => {
      await withTempDir(async (freshTemp) => {
        const upgraded = await restoreFixture(fixture, snapshot, upgradeTemp);
        const upgrade = await runAgent(upgraded, ["upgrade", "--json"]);
        assertEquals(upgrade.code, 0, upgrade.output);
        const result = decodeCliResult(upgrade.stdout, "upgrade");
        assertResultDataKey(result, "migrations_applied");
        assertEquals(result.data.schema, {
          from: fixture.manifest.schema,
          current: SCHEMA_VERSION,
        });
        const applied = result.data.migrations_applied;
        assertExists(applied);
        assertEquals(applied.length, SCHEMA_VERSION - fixture.manifest.schema);

        const fresh = join(freshTemp, fixture.manifest.project_directory);
        const setup = await freshInstall(
          fresh,
          fixture.manifest.seed,
          fixture.manifest.setup_args,
        );
        assertEquals(setup.code, 0, setup.output);
        const entries = projectArtifactPaths(
          parseConfigOrThrow(await Deno.readTextFile(join(fresh, CONFIG_REL))),
        );
        const converged = await snapshotTree(upgraded);
        const problems = convergenceProblems(
          fixture,
          entries,
          converged,
          await snapshotTree(fresh),
        );
        assertEquals(
          problems,
          [],
          `${fixture.rel} did not converge with a fresh installation:\n  ${
            problems.join("\n  ")
          }`,
        );

        // A reviewed upgrade is committed before the next one runs; the
        // second upgrade then finds nothing to change.
        await git(upgraded, "add", "-A");
        await git(
          upgraded,
          "commit",
          "-q",
          "-m",
          "upgrade discern",
          "--no-gpg-sign",
        );
        const again = await runAgent(upgraded, ["upgrade", "--json"]);
        assertEquals(again.code, 0, again.output);
        assertEquals(
          await snapshotTree(upgraded),
          converged,
          "a second upgrade changes nothing",
        );
      });
    });
  }
});
