/**
 * The install corpus proves ADR 0014's keystone invariant on real captured
 * installations: an installation captured at a past schema and brought
 * forward by `discern upgrade` equals a fresh installation from the current
 * build, except for the differences an explicit registry names and checks.
 * The corpus itself is frozen by its manifests, and `SCHEMA_VERSION` cannot
 * advance past the newest captured schema plus one.
 */

import {
  assert,
  assertEquals,
  assertExists,
  assertMatch,
  assertStringIncludes,
} from "@std/assert";
import { dirname, join } from "@std/path";
import { DISCERN_VERSION, SCHEMA_VERSION } from "../src/lib/version.ts";
import { sha256Hex } from "../src/shared/sha256.ts";
import { CAPTURE_COMMAND } from "../scripts/capture_install_fixture.ts";
import { assertResultDataKey, decodeCliResult } from "./decode_cli_result.ts";
import { git, gitInit, runAgent } from "./engine_helpers.ts";
import { withTempDir } from "./helpers.ts";
import {
  FIXTURE_MANIFEST,
  FIXTURE_PROJECT_DIR,
  freshInstall,
  INSTALL_CORPUS_REL,
  type InstallFixture,
  installFixtures,
  snapshotTree,
  type TreeEntry,
} from "./install_corpus.ts";
import { structuralGuardScope } from "./structural_guard_scope.ts";

/** The setup-provenance header line a rendered config carries. */
const PROVENANCE_HEADER = /^# Generated by discern (\S+) for "/mu;

/**
 * One intentional difference between an upgraded fixture and a fresh
 * installation. Each entry asserts the exact shape it expects on both sides
 * before removing it, so the allowance cannot absorb unrelated drift.
 */
interface ConvergenceAllowance {
  readonly path: string;
  readonly reason: string;
  readonly normalize: (
    fixture: InstallFixture,
    upgraded: string,
    fresh: string,
  ) => { upgraded: string; fresh: string };
}

/** Replace the recorded setup-provenance version with a placeholder after asserting it. */
function withProvenancePlaceholder(config: string, version: string): string {
  const header = config.match(PROVENANCE_HEADER);
  assertEquals(
    header?.[1],
    version,
    "the config header names its setup release",
  );
  const stamp = `setup_version = "${version}"`;
  assertStringIncludes(config, stamp);
  return config
    .replace(PROVENANCE_HEADER, '# Generated by discern <setup-version> for "')
    .replace(stamp, 'setup_version = "<setup-version>"');
}

/** Remove the adoption fact upgrade records, after asserting it names this build. */
function withoutAdoption(config: string): string {
  const adopted = `managed_version = "${DISCERN_VERSION}"`;
  assertStringIncludes(config, adopted, "upgrade adopts the running version");
  return config.split("\n").filter((line) => line.trim() !== adopted).join(
    "\n",
  );
}

const CONVERGENCE_ALLOWANCES: readonly ConvergenceAllowance[] = [
  {
    path: "discern.toml",
    reason:
      "Setup provenance names the release that ran setup and survives upgrade; adoption is recorded by completion or upgrade, never by setup begin.",
    normalize: (fixture, upgraded, fresh) => {
      assert(
        !fresh.includes("managed_version"),
        "setup begin records no adoption",
      );
      return {
        upgraded: withoutAdoption(
          withProvenancePlaceholder(upgraded, fixture.manifest.discern_version),
        ),
        fresh: withProvenancePlaceholder(fresh, DISCERN_VERSION),
      };
    },
  },
];

/** Describe the first line where two texts differ. */
function firstDifference(left: string, right: string): string {
  const leftLines = left.split("\n");
  const rightLines = right.split("\n");
  const limit = Math.max(leftLines.length, rightLines.length);
  for (let index = 0; index < limit; index++) {
    if (leftLines[index] !== rightLines[index]) {
      return `line ${index + 1}\n    upgraded: ${
        leftLines[index] ?? "<end of file>"
      }\n    fresh:    ${rightLines[index] ?? "<end of file>"}`;
    }
  }
  return "identical text";
}

/** Compare two installation snapshots path by path under the registered allowances. */
function convergenceProblems(
  fixture: InstallFixture,
  upgraded: Map<string, TreeEntry>,
  fresh: Map<string, TreeEntry>,
): string[] {
  const problems: string[] = [];
  const paths = [...new Set([...upgraded.keys(), ...fresh.keys()])].sort();
  for (const allowance of CONVERGENCE_ALLOWANCES) {
    if (!paths.includes(allowance.path)) {
      problems.push(`${allowance.path}: allowance names an absent file`);
    }
  }
  for (const path of paths) {
    const left = upgraded.get(path);
    const right = fresh.get(path);
    if (left === undefined || right === undefined) {
      problems.push(
        `${path}: only in the ${
          left === undefined ? "fresh" : "upgraded"
        } installation`,
      );
      continue;
    }
    if (left.executable !== right.executable) {
      problems.push(`${path}: executable bit differs`);
    }
    const allowance = CONVERGENCE_ALLOWANCES.find((entry) =>
      entry.path === path
    );
    const texts = allowance === undefined
      ? { upgraded: left.text, fresh: right.text }
      : allowance.normalize(fixture, left.text, right.text);
    if (texts.upgraded !== texts.fresh) {
      problems.push(
        `${path}: differs at ${firstDifference(texts.upgraded, texts.fresh)}`,
      );
    }
  }
  return problems;
}

/** Restore a fixture's captured installation into a committed Git repository named like the capture. */
async function restoreFixture(
  fixture: InstallFixture,
  temp: string,
): Promise<string> {
  const root = join(temp, fixture.manifest.project_directory);
  await Deno.mkdir(root);
  for (const [rel, text] of Object.entries(fixture.manifest.seed)) {
    await Deno.mkdir(dirname(join(root, rel)), { recursive: true });
    await Deno.writeTextFile(join(root, rel), text);
  }
  await gitInit(root);
  for (const rel of Object.keys(fixture.manifest.files)) {
    const text = await Deno.readTextFile(join(fixture.projectDir, rel));
    await Deno.mkdir(dirname(join(root, rel)), { recursive: true });
    await Deno.writeTextFile(join(root, rel), text);
  }
  await git(root, "add", "-A");
  await git(root, "commit", "-q", "-m", "install discern", "--no-gpg-sign");
  return root;
}

Deno.test("SCHEMA_VERSION cannot advance past the newest captured schema plus one", async () => {
  const fixtures = await installFixtures();
  const schemas = fixtures.map((fixture) => fixture.manifest.schema);
  assertEquals(
    schemas,
    schemas.map((_, index) => index + 1),
    "every schema that was ever current keeps its captured installation",
  );
  const newest = schemas.at(-1);
  assertExists(newest, "the corpus starts at schema 1");
  assert(
    SCHEMA_VERSION <= newest + 1,
    `SCHEMA_VERSION is ${SCHEMA_VERSION} but the newest captured installation is schema ${newest}; capture schema ${
      SCHEMA_VERSION - 1
    } with \`${CAPTURE_COMMAND}\` before raising the schema again`,
  );
});

Deno.test("every captured installation is frozen by its manifest", async () => {
  const fixtures = await installFixtures();
  const listed = await structuralGuardScope({
    guard: "tests/install_corpus_test.ts#frozen-fixture-members",
    universe: {
      kind: "specialized",
      name: "text including install fixtures",
      text: true,
      reason:
        "Captured installations are inert fixture data outside the authored-text universe.",
    },
    narrow: {
      reason:
        "The corpus holds only manifests and captured installation files.",
      include: (rel) => rel.startsWith(`${INSTALL_CORPUS_REL}/schema-`),
    },
  });
  const expected: string[] = [];
  for (const fixture of fixtures) {
    expected.push(`${fixture.rel}/${FIXTURE_MANIFEST}`);
    assertEquals(fixture.manifest.reproduce, CAPTURE_COMMAND);
    for (const [rel, hash] of Object.entries(fixture.manifest.files)) {
      expected.push(`${fixture.rel}/${FIXTURE_PROJECT_DIR}/${rel}`);
      const text = await Deno.readTextFile(join(fixture.projectDir, rel));
      assertEquals(await sha256Hex(text), hash, `frozen input changed: ${rel}`);
    }
    const config = await Deno.readTextFile(
      join(fixture.projectDir, "discern.toml"),
    );
    assertMatch(
      config,
      new RegExp(`^\\s*schema_version = ${fixture.manifest.schema}$`, "mu"),
    );
    assertEquals(
      config.match(PROVENANCE_HEADER)?.[1],
      fixture.manifest.discern_version,
    );
  }
  assertEquals(listed, expected.sort());
});

Deno.test("every captured installation upgraded by this build converges with a fresh installation", async () => {
  for (const fixture of await installFixtures()) {
    await withTempDir(async (upgradeTemp) => {
      await withTempDir(async (freshTemp) => {
        const upgraded = await restoreFixture(fixture, upgradeTemp);
        const upgrade = await runAgent(upgraded, ["upgrade", "--json"]);
        assertEquals(upgrade.code, 0, upgrade.output);
        const result = decodeCliResult(upgrade.stdout, "upgrade");
        assertResultDataKey(result, "migrations_applied");
        assertEquals(result.data.schema, {
          from: fixture.manifest.schema,
          current: SCHEMA_VERSION,
        });
        const applied = result.data.migrations_applied;
        assertExists(applied);
        assertEquals(applied.length, SCHEMA_VERSION - fixture.manifest.schema);

        const fresh = join(freshTemp, fixture.manifest.project_directory);
        const setup = await freshInstall(
          fresh,
          fixture.manifest.seed,
          fixture.manifest.setup_args,
        );
        assertEquals(setup.code, 0, setup.output);
        const converged = await snapshotTree(upgraded);
        const problems = convergenceProblems(
          fixture,
          converged,
          await snapshotTree(fresh),
        );
        assertEquals(
          problems,
          [],
          `${fixture.rel} did not converge with a fresh installation:\n  ${
            problems.join("\n  ")
          }`,
        );

        // A reviewed upgrade is committed before the next one runs; the
        // second upgrade then finds nothing to change.
        await git(upgraded, "add", "-A");
        await git(
          upgraded,
          "commit",
          "-q",
          "-m",
          "upgrade discern",
          "--no-gpg-sign",
        );
        const again = await runAgent(upgraded, ["upgrade", "--json"]);
        assertEquals(again.code, 0, again.output);
        assertEquals(
          await snapshotTree(upgraded),
          converged,
          "a second upgrade changes nothing",
        );
      });
    });
  }
});
