/** Browser-facing checks for the built design-system demo artifact. */

import {
  assert,
  assertEquals,
  assertMatch,
  assertStringIncludes,
} from "@std/assert";
import { fromFileUrl, join, relative } from "@std/path";
import type { RuntimeManifest } from "discern-design-system/manifest";
import { GENERATED_SITE_OUTPUTS } from "../site/build.ts";
import { renderContentDesignDemo } from "../site/page-src/content-design-demo.tsx";
import { renderDesignSystemDemo } from "../site/page-src/design-system-demo.tsx";
import { formatGeneratedText } from "../site/page-src/format-generated.ts";
import { runtimeAssetReferences } from "./runtime_asset_references.ts";
import { handler } from "../site/serve.ts";

const ROOT = fromFileUrl(new URL("../", import.meta.url));
const PUBLIC_ROOT = join(ROOT, "site", "pages", "assets", "design-system");

const BROWSER = {
  accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
  "user-agent": "Mozilla/5.0 Safari/605.1.15",
};

Deno.test("the design-system demo routes serve generated static editions", async () => {
  for (
    const [route, marker] of [
      [
        "/design-system-demo",
        "typed React at build time · static HTML at runtime",
      ],
      ["/content-design-demo", "editorial engineering · static by design"],
    ] as const
  ) {
    const response = await handler(
      new Request(`https://discern.sh${route}`, { headers: BROWSER }),
    );
    assertEquals(response.status, 200);
    assertStringIncludes(
      response.headers.get("content-type") ?? "",
      "text/html",
    );
    const html = await response.text();
    assertStringIncludes(html, "data-discern-root");
    assertStringIncludes(html, marker);

    const runtimeRefs = runtimeAssetReferences(html);
    assert(
      runtimeRefs.every((value) => value.startsWith("/")),
      `${route} remote runtime references: ${runtimeRefs.join(", ")}`,
    );
    assertEquals(
      runtimeRefs.filter((value) => value.endsWith(".js")),
      ["/assets/design-system/demo.js"],
    );
  }
});

async function git(args: string[]): Promise<Deno.CommandOutput> {
  return await new Deno.Command("git", {
    args,
    cwd: ROOT,
    stdout: "piped",
    stderr: "piped",
  }).output();
}

async function walk(directory: string): Promise<string[]> {
  const files: string[] = [];
  for await (const entry of Deno.readDir(directory)) {
    const path = join(directory, entry.name);
    if (entry.isDirectory) files.push(...await walk(path));
    else files.push(path);
  }
  return files;
}

async function manifest(): Promise<RuntimeManifest> {
  return JSON.parse(
    await Deno.readTextFile(join(PUBLIC_ROOT, "manifest.json")),
  ) as RuntimeManifest;
}

function componentOwnedSelectors(
  source: string,
  ownedClasses: ReadonlySet<string>,
): string[] {
  const selectors = new Set<string>();
  for (const rule of source.matchAll(/([^{}]+)\{/g)) {
    const prelude = (rule[1] ?? "").trim();
    for (const match of prelude.matchAll(/\.([_a-zA-Z0-9-]+)/g)) {
      if (ownedClasses.has(match[1] ?? "")) selectors.add(prelude);
    }
  }
  return [...selectors].toSorted();
}

Deno.test("generated site output is ignored and reproducible from selected package output", async () => {
  const repoPaths = GENERATED_SITE_OUTPUTS.map((output) =>
    join("site", output)
  );
  const tracked = await git(["ls-files", "--", ...repoPaths]);
  assertEquals(tracked.code, 0);
  assertEquals(new TextDecoder().decode(tracked.stdout).trim(), "");
  for (const path of repoPaths) {
    const ignored = await git(["check-ignore", "--quiet", "--no-index", path]);
    assertEquals(ignored.code, 0, `${path} must be ignored`);
  }

  const runtime = await manifest();
  assertEquals(runtime.selection.all, false);
  assertEquals(runtime.selection.requestedGroups, ["Marketing", "Editorial"]);
  assertEquals(runtime.selection.resolvedComponents.length, 35);
  assertEquals(runtime.selection.assets, ["fonts", "grain"]);
  const stats = {
    components: runtime.components.length,
    tokens: runtime.publicTokenNames.length,
  };
  assertEquals(
    await Deno.readTextFile(
      join(ROOT, "site", "pages", "design-system-demo.html"),
    ),
    await formatGeneratedText(renderDesignSystemDemo(stats), "html"),
  );
  assertEquals(
    await Deno.readTextFile(
      join(ROOT, "site", "pages", "content-design-demo.html"),
    ),
    await formatGeneratedText(renderContentDesignDemo(stats), "html"),
  );

  for (
    const [source, output] of [
      ["design-system-demo.css", "demo.css"],
      ["content-design-demo.css", "content-demo.css"],
      ["design-system-demo.js", "demo.js"],
    ] as const
  ) {
    assertEquals(
      await Deno.readTextFile(join(PUBLIC_ROOT, output)),
      `/* Generated by site/build.ts from site/page-src/${source}. Do not edit. */\n${await Deno
        .readTextFile(join(ROOT, "site", "page-src", source))}`,
    );
  }
});

Deno.test("each product demo covers its selected canonical component group", async () => {
  const runtime = await manifest();
  const pages = new Map([
    [
      "Marketing",
      await Deno.readTextFile(
        join(ROOT, "site", "pages", "design-system-demo.html"),
      ),
    ],
    [
      "Editorial",
      await Deno.readTextFile(
        join(ROOT, "site", "pages", "content-design-demo.html"),
      ),
    ],
  ]);
  for (const [group, html] of pages) {
    const identity = runtime.groups.find((candidate) =>
      candidate.name === group
    );
    assert(identity !== undefined);
    for (const id of identity.components) {
      assertMatch(
        html,
        new RegExp(`class="[^"]*\\bdiscern-${id}\\b`),
        `${group} demo does not render ${id}`,
      );
    }
  }
  const selected = new Set(runtime.selection.resolvedComponents);
  for (const group of runtime.groups) {
    if (["Forms", "Feedback", "Navigation"].includes(group.name)) {
      assert(
        group.components.every((component) => !selected.has(component)),
        `${group.name} leaked into the site selection`,
      );
    }
  }
});

Deno.test("consumer CSS never overrides a manifest-owned component class", async () => {
  const runtime = await manifest();
  const owned = new Set(
    runtime.components.flatMap((component) => component.ownedClasses),
  );
  assert(owned.size > 0);
  const violations: string[] = [];
  for (
    const path of (await walk(join(ROOT, "site"))).filter((candidate) => {
      const repoPath = relative(ROOT, candidate);
      return candidate.endsWith(".css") &&
        !repoPath.startsWith("site/design-system/") &&
        !repoPath.startsWith("site/pages/");
    })
  ) {
    for (
      const selector of componentOwnedSelectors(
        await Deno.readTextFile(path),
        owned,
      )
    ) {
      violations.push(`${relative(ROOT, path)}: ${selector}`);
    }
  }
  assertEquals(violations, []);
});

Deno.test("every referenced design-system asset is served with its browser type", async () => {
  const expected = new Map([
    ["/assets/design-system/discern.css", "text/css"],
    ["/assets/design-system/demo.css", "text/css"],
    ["/assets/design-system/content-demo.css", "text/css"],
    ["/assets/design-system/fonts.css", "text/css"],
    ["/assets/design-system/grain.css", "text/css"],
    ["/assets/design-system/demo.js", "text/javascript"],
    ["/assets/design-system/manifest.json", "application/json"],
    ["/assets/design-system/textures/grain.png", "image/png"],
    ["/assets/design-system/fonts/crimson-pro-roman.woff2", "font/woff2"],
    ["/assets/design-system/fonts/crimson-pro-italic.woff2", "font/woff2"],
    ["/assets/design-system/fonts/inter.woff2", "font/woff2"],
    ["/assets/design-system/fonts/jetbrains-mono.woff2", "font/woff2"],
  ]);

  for (const [path, contentType] of expected) {
    const response = await handler(
      new Request(`https://discern.sh${path}`, { headers: BROWSER }),
    );
    assertEquals(response.status, 200, path);
    assertStringIncludes(
      response.headers.get("content-type") ?? "",
      contentType,
      path,
    );
    const bytes = new Uint8Array(await response.arrayBuffer());
    assert(bytes.length > 0, `${path} is empty`);
  }
});
