/**
 * The committed internal tip inventory stays in lockstep with TIPS. A new
 * entry auto-enrols in both the page and this guard; hand edits drift at once.
 */

import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { renderTipInventoryDoc } from "../src/shared/tip_inventory_codegen.ts";
import {
  renderTipCli,
  TIP_COVERAGE_DELIBERATELY_ABSENT,
  TIP_RENDERED_LENGTH_LIMIT,
  TIPS,
} from "../src/shared/tips.ts";
import { REPO_AUTHORED_PATHS } from "./repo_authored_paths.ts";
import { canonicalGeneratedMarkdown } from "./tidy_helpers.ts";

const rendered = renderTipInventoryDoc();

/** Return the committed inventory. */
async function committedInventory(): Promise<string> {
  return await Deno.readTextFile(
    `${REPO_AUTHORED_PATHS.map}/_internal/tip-inventory.md`,
  );
}

Deno.test("the configured map's tip inventory matches the generator (run `deno task codegen`)", async () => {
  const path = `${REPO_AUTHORED_PATHS.map}/_internal/tip-inventory.md`;
  assertEquals(
    await committedInventory(),
    await canonicalGeneratedMarkdown(path, rendered),
    `${REPO_AUTHORED_PATHS.mapRel}/_internal/tip-inventory.md is stale — run \`deno task codegen\``,
  );
});

Deno.test("the tip inventory is total over TIPS, in curriculum order", () => {
  const headings = [...rendered.matchAll(/^## `([^`]+)`$/gm)];
  assertEquals(
    headings.map((match) => match[1] ?? ""),
    TIPS.map((tip) => tip.id),
    "the generated inventory must list every tip in authored order — the order is the curriculum",
  );

  const byId = new Map(TIPS.map((tip) => [tip.id, tip]));
  for (const [index, heading] of headings.entries()) {
    const id = heading[1] ?? "";
    const tip = byId.get(id);
    assert(tip !== undefined, `inventory contains unknown tip ${id}`);
    const when = tip.when.trim();
    assert(when !== "", `${tip.id} needs a when value`);
    assert(!/[\r\n]/.test(when), `${tip.id}.when must stay on one line`);
    const start = heading.index ?? 0;
    const end = headings[index + 1]?.index ?? rendered.length;
    const section = rendered.slice(start, end);
    assertStringIncludes(section, `- Relevance: ${when}`);
    assertStringIncludes(
      section,
      `- Predicate: ${
        tip.predicate === undefined ? "—" : `\`${tip.predicate.kind}\``
      }`,
    );
    assertStringIncludes(
      section,
      `- Since: ${tip.since === undefined ? "—" : `\`${tip.since}\``}`,
    );
    for (const feature of tip.features) {
      assertStringIncludes(section, `\`${feature}\``);
    }
    assertStringIncludes(section, renderTipCli(tip));
  }
});

Deno.test("the committed tip inventory declares its generated provenance", async () => {
  assertStringIncludes(
    await committedInventory(),
    "GENERATED by `deno task codegen`",
    "the committed tip inventory lost its generated banner",
  );
});

Deno.test("the generated inventory explains the curriculum and its guardrails", () => {
  assertStringIncludes(rendered, "a guided onboarding path");
  assertStringIncludes(
    rendered,
    "place a new tip at its learning moment instead of appending it by default",
  );
  assertStringIncludes(
    rendered,
    `no more than ${TIP_RENDERED_LENGTH_LIMIT} characters`,
  );
  assertStringIncludes(rendered, "There is no reading-grade ceiling");
});

Deno.test("the generated inventory renders every deliberate absence", () => {
  for (
    const [member, reason] of Object.entries(
      TIP_COVERAGE_DELIBERATELY_ABSENT,
    )
  ) {
    assertStringIncludes(rendered, `\`${member}\``);
    assertStringIncludes(rendered, reason);
  }
});
