/**
 * Guard against duplicating the package version in source. `deno.json` is the
 * single source; code imports `KIT_VERSION` from `src/lib/version.ts`. The ban
 * covers every authored TypeScript tree: a hardcoded version in a test pins an
 * assertion that breaks on the next release, and one in `scripts/` codegen
 * writes the stale number into committed artifacts.
 */

import { assertEquals } from "@std/assert";
import { join } from "@std/path";
import { KIT_VERSION } from "../src/lib/version.ts";
import { REPO_ROOT } from "./repo_authored_paths.ts";
import { structuralGuardScope } from "./structural_guard_scope.ts";
import { gitInit } from "./engine_helpers.ts";
import { runCli, withTempDir } from "./helpers.ts";

/** Every listed TypeScript source quoting `version` verbatim, minus `allowed`. */
async function hardcodedVersionSites(
  root: string,
  files: string[],
  version: string,
  allowed: readonly string[],
): Promise<string[]> {
  const quotes = [`"${version}"`, `'${version}'`, `\`${version}\``];
  const offenders: string[] = [];
  for (const rel of files) {
    if (allowed.includes(rel)) continue;
    const text = await Deno.readTextFile(join(root, rel));
    if (quotes.some((quote) => text.includes(quote))) {
      offenders.push(rel);
    }
  }
  return offenders.sort();
}

// The single source itself — the one place the semver may appear quoted.
const ALLOWED = ["src/lib/version.ts"];

/** Resolve the repository-wide version-literal universe for any Git fixture. */
function versionGuardFiles(root: string): Promise<string[]> {
  return structuralGuardScope({
    guard: "tests/version_literal_test.ts#hardcoded-package-version",
    universe: "authored-ts",
  }, root);
}

Deno.test("authored TypeScript never hardcodes the package semver", async () => {
  assertEquals(
    await hardcodedVersionSites(
      REPO_ROOT,
      await versionGuardFiles(REPO_ROOT),
      KIT_VERSION,
      ALLOWED,
    ),
    [],
    `import KIT_VERSION instead of hardcoding ${KIT_VERSION}; sample semvers ` +
      `in fixtures must not collide with the current package version`,
  );
});

Deno.test("the version guard enrolls a fresh literal in any authored tree", async () => {
  await withTempDir(async (dir) => {
    await Deno.writeTextFile(join(dir, "seed.txt"), "seed\n");
    await gitInit(dir);
    await Deno.mkdir(join(dir, "scripts"), { recursive: true });
    await Deno.writeTextFile(
      join(dir, "scripts", "emit_release.ts"),
      `export const banner = "unrelated v3.2.1";\n`,
    );
    assertEquals(
      await hardcodedVersionSites(
        dir,
        await versionGuardFiles(dir),
        "3.2.1",
        [],
      ),
      [],
      "a version inside a longer string is not a quoted literal",
    );
    await Deno.writeTextFile(
      join(dir, "scripts", "emit_release.ts"),
      `export const version = "3.2.1";\n`,
    );
    assertEquals(
      await hardcodedVersionSites(
        dir,
        await versionGuardFiles(dir),
        "3.2.1",
        [],
      ),
      ["scripts/emit_release.ts"],
    );
  });
});

// The behavioral half of the guard: static absence of the literal proves
// nothing about what the surfaces actually print, so scaffold an install and
// hold every version-reporting surface to the imported KIT_VERSION.
Deno.test("every version-reporting surface derives from KIT_VERSION", async () => {
  await withTempDir(async (dir) => {
    const setup = await runCli(
      ["setup", "--confirmed", "--yes", "--slug", "version-probe"],
      dir,
    );
    assertEquals(setup.code, 0, "setup should scaffold a healthy install");

    const cliVersion = await runCli(["--version"], dir);
    const doctorJson = JSON.parse(
      (await runCli(["doctor", "--json"], dir)).stdout,
    );
    const doctorHuman = await runCli(["doctor"], dir);
    const stampedConfig = await Deno.readTextFile(join(dir, "discern.toml"));

    const surfaces: ReadonlyArray<[string, string | undefined]> = [
      [
        "cli --version",
        cliVersion.stdout.trim().match(/^discern (\S+)$/)?.[1],
      ],
      ["doctor --json data.kit_version", doctorJson.data.kit_version],
      [
        "doctor --json data.environment.discern",
        doctorJson.data.environment.discern,
      ],
      [
        "doctor human environment banner",
        doctorHuman.stderr.match(/discern (\S+) ·/)?.[1],
      ],
      [
        "scaffolded config provenance banner ({{kit_version}})",
        stampedConfig.match(/^# Generated by discern (\S+) /m)?.[1],
      ],
    ];
    for (const [surface, reported] of surfaces) {
      assertEquals(
        reported,
        KIT_VERSION,
        `${surface} must report the package version`,
      );
    }
  });
});
