/**
 * Guard against duplicating the package version. `deno.json` is the single
 * source; code imports `KIT_VERSION` from `src/lib/version.ts`, and tests
 * assert against that import rather than pinning the literal. A pinned test
 * masks exactly the drift it appears to prevent: after a version bump, a
 * surface that hardcoded the old version keeps its stale pin green.
 */

import { assert, assertEquals } from "@std/assert";
import { join, relative } from "@std/path";
import { KIT_VERSION } from "../src/lib/version.ts";
import { runCli, withTempDir } from "./helpers.ts";

const REPO = new URL("../", import.meta.url).pathname;
const SRC = new URL("../src/", import.meta.url).pathname;
const TESTS = new URL("./", import.meta.url).pathname;

async function* tsFiles(dir: string): AsyncGenerator<string> {
  for await (const entry of Deno.readDir(dir)) {
    const path = join(dir, entry.name);
    if (entry.isDirectory) {
      yield* tsFiles(path);
    } else if (entry.isFile && entry.name.endsWith(".ts")) {
      yield path;
    }
  }
}

/** True when `text` carries the current package version as a quoted literal. */
function pinsCurrentVersion(text: string): boolean {
  return [
    `"${KIT_VERSION}"`,
    `'${KIT_VERSION}'`,
    `\`${KIT_VERSION}\``,
  ].some((quoted) => text.includes(quoted));
}

Deno.test("src does not hardcode the current package semver outside version.ts", async () => {
  const offenders: string[] = [];
  for await (const path of tsFiles(SRC)) {
    const rel = relative(REPO, path);
    if (rel === "src/lib/version.ts") {
      continue;
    }
    if (pinsCurrentVersion(await Deno.readTextFile(path))) {
      offenders.push(rel);
    }
  }
  assert(
    offenders.length === 0,
    `source files must import KIT_VERSION instead of hardcoding ${KIT_VERSION}: ${
      offenders.join(", ")
    }`,
  );
});

// The same mechanism on the test side: a test that pins the current version as
// a literal stops checking derivation — after a bump it either gets hand-edited
// (an honest pin) or stays green against a stale surface (a masking pin). Every
// new test file auto-enrols via the directory walk.
Deno.test("tests do not pin the current package semver as a literal", async () => {
  const offenders: string[] = [];
  for await (const path of tsFiles(TESTS)) {
    if (pinsCurrentVersion(await Deno.readTextFile(path))) {
      offenders.push(relative(REPO, path));
    }
  }
  assert(
    offenders.length === 0,
    "tests must interpolate KIT_VERSION when asserting a version-reporting " +
      "surface, and use a clearly-fake semver (e.g. \"9.9.9\") for fixture " +
      `data — never the current literal ${KIT_VERSION}: ${offenders.join(", ")}`,
  );
});

// Positive control: the detector rejects a fresh-name pin (built dynamically so
// this file never carries the literal itself).
Deno.test("the version-pin detector catches an unrelated fresh literal", () => {
  assert(pinsCurrentVersion(`const anyNewName = "${KIT_VERSION}";`));
  assert(!pinsCurrentVersion('const fixtureSemver = "9.9.9";'));
});

// The class, end to end: every surface that REPORTS the kit version must derive
// it from KIT_VERSION. One install, each reporting surface read for real.
Deno.test("every version-reporting surface derives from KIT_VERSION", async () => {
  await withTempDir(async (dir) => {
    const setup = await runCli(
      ["setup", "--confirmed", "--yes", "--slug", "version-probe"],
      dir,
    );
    assertEquals(setup.code, 0, "setup should scaffold a healthy install");

    const cliVersion = await runCli(["--version"], dir);
    const doctorJson = JSON.parse((await runCli(["doctor", "--json"], dir)).stdout);
    const doctorHuman = await runCli(["doctor"], dir);
    const stampedConfig = await Deno.readTextFile(join(dir, "discern.toml"));

    const surfaces: ReadonlyArray<[string, string | undefined]> = [
      [
        "cli --version",
        cliVersion.stdout.trim().match(/^discern (\S+)$/)?.[1],
      ],
      ["doctor --json data.kit_version", doctorJson.data.kit_version],
      [
        "doctor --json data.environment.discern",
        doctorJson.data.environment.discern,
      ],
      [
        "doctor human environment banner",
        doctorHuman.stderr.match(/discern (\S+) ·/)?.[1],
      ],
      [
        "scaffolded config provenance banner ({{kit_version}})",
        stampedConfig.match(/^# Generated by discern (\S+) /m)?.[1],
      ],
    ];
    for (const [surface, reported] of surfaces) {
      assertEquals(
        reported,
        KIT_VERSION,
        `${surface} must report the package version`,
      );
    }
  });
});
