/**
 * Build discern.sh's generated design-system surface.
 *
 * React is an authoring adapter only: this script renders the homepage and
 * shared brand to static HTML, writes deterministic CSS/assets, and ships no
 * React runtime.
 */

import {
  type BuildSummary,
  emitDesignSystemRuntime,
} from "discern-design-system/runtime";
import {
  DESIGN_SYSTEM_BUNDLES,
  type DesignSystemBundleName,
} from "./design_system.ts";
import { renderDiscernBrand } from "./page-src/branding.tsx";
import { formatGeneratedText } from "./page-src/format-generated.ts";
import { renderLanding } from "./page-src/landing.tsx";

const SITE_ROOT = new URL("./", import.meta.url);
const SOURCE_ROOT = new URL("page-src/", SITE_ROOT);

/** Public files produced by the site build and therefore forbidden from Git. */
export const GENERATED_SITE_OUTPUTS = [
  "pages/index.html",
  "pages/assets/design-system/",
  "pages/fragments/",
] as const;

/** Page-owned assets copied verbatim into the compositions bundle. */
export const COPIED_PAGE_ASSETS = [
  "landing.css",
] as const;

/** Old generated pages removed on every build so local previews cannot retain them. */
export const RETIRED_SITE_OUTPUTS = [
  "pages/design-system-demo.html",
  "pages/content-design-demo.html",
  "pages/v2.html",
] as const;

const HOME_PAGE_OUTPUT = new URL(GENERATED_SITE_OUTPUTS[0], SITE_ROOT);
const ASSET_ROOT = new URL(GENERATED_SITE_OUTPUTS[1], SITE_ROOT);
const FRAGMENT_ROOT = new URL(GENERATED_SITE_OUTPUTS[2], SITE_ROOT);
const BRAND_FRAGMENT_OUTPUT = new URL("brand.html", FRAGMENT_ROOT);
const COMPOSITION_ASSET_ROOT = new URL(
  DESIGN_SYSTEM_BUNDLES.compositions.output,
  SITE_ROOT,
);

/** Remove the if present. */
async function removeIfPresent(url: URL): Promise<void> {
  try {
    await Deno.remove(url, { recursive: true });
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
}

/** Write the generated copy. */
async function writeGeneratedCopy(
  source: string,
  destination: string,
): Promise<void> {
  const body = await Deno.readTextFile(new URL(source, SOURCE_ROOT));
  await Deno.writeTextFile(
    new URL(destination, COMPOSITION_ASSET_ROOT),
    `/* Generated by site/build.ts from site/page-src/${source}. Do not edit. */\n${body}`,
  );
}

/** Emit the bundle. */
async function emitBundle(name: DesignSystemBundleName): Promise<BuildSummary> {
  const selection = DESIGN_SYSTEM_BUNDLES[name];
  return await emitDesignSystemRuntime({
    outputRoot: new URL(selection.output, SITE_ROOT),
    components: selection.components,
    groups: selection.groups,
    assets: selection.assets,
    theme: selection.theme,
  });
}

/** Rebuild the complete ignored public design-system surface from source. */
export async function buildSite(): Promise<void> {
  for (const output of [...GENERATED_SITE_OUTPUTS, ...RETIRED_SITE_OUTPUTS]) {
    await removeIfPresent(new URL(output, SITE_ROOT));
  }

  await Deno.mkdir(ASSET_ROOT, { recursive: true });
  await Deno.mkdir(FRAGMENT_ROOT, { recursive: true });
  await emitBundle("docs");
  const summary = await emitBundle("compositions");
  for (const asset of COPIED_PAGE_ASSETS) {
    await writeGeneratedCopy(asset, asset);
  }
  await Deno.writeTextFile(
    HOME_PAGE_OUTPUT,
    await formatGeneratedText(renderLanding(), "html"),
  );
  await Deno.writeTextFile(BRAND_FRAGMENT_OUTPUT, renderDiscernBrand());

  console.log(
    `Built the shared Brand fragment, homepage, and design-system bundles from ${summary.components} components and ${summary.tokens} tokens.`,
  );
}

if (import.meta.main) await buildSite();
