/**
 * Build discern.sh's generated design-system surface.
 *
 * React is an authoring adapter only: this script renders the demo to static
 * HTML, writes deterministic CSS/assets, and ships no React runtime.
 */

import { buildDesignSystemRuntime } from "./design-system/scripts/build.ts";
import { renderDesignSystemDemo } from "./page-src/design-system-demo.tsx";
import { formatGeneratedText } from "./page-src/format-generated.ts";

const SITE_ROOT = new URL("./", import.meta.url);
const SOURCE_ROOT = new URL("page-src/", SITE_ROOT);

/** Public files produced by the site build and therefore forbidden from Git. */
export const GENERATED_SITE_OUTPUTS = [
  "pages/design-system-demo.html",
  "pages/assets/design-system/",
] as const;

const PAGE_OUTPUT = new URL(GENERATED_SITE_OUTPUTS[0], SITE_ROOT);
const ASSET_ROOT = new URL(GENERATED_SITE_OUTPUTS[1], SITE_ROOT);

async function removeIfPresent(url: URL): Promise<void> {
  try {
    await Deno.remove(url, { recursive: true });
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
}

async function writeGeneratedCopy(
  source: string,
  destination: string,
): Promise<void> {
  const body = await Deno.readTextFile(new URL(source, SOURCE_ROOT));
  await Deno.writeTextFile(
    new URL(destination, ASSET_ROOT),
    `/* Generated by site/build.ts from site/page-src/${source}. Do not edit. */\n${body}`,
  );
}

/** Rebuild the complete ignored public design-system surface from source. */
export async function buildSite(): Promise<void> {
  for (const output of GENERATED_SITE_OUTPUTS) {
    await removeIfPresent(new URL(output, SITE_ROOT));
  }

  await Deno.mkdir(ASSET_ROOT, { recursive: true });
  const summary = await buildDesignSystemRuntime(ASSET_ROOT);
  await writeGeneratedCopy("design-system-demo.css", "demo.css");
  await writeGeneratedCopy("design-system-demo.js", "demo.js");
  await Deno.writeTextFile(
    PAGE_OUTPUT,
    await formatGeneratedText(renderDesignSystemDemo(summary), "html"),
  );

  console.log(
    `Built the static design-system demo from ${summary.components} components and ${summary.tokens} tokens.`,
  );
}

if (import.meta.main) await buildSite();
