/**
 * Build discern.sh's generated design-system surface.
 *
 * React is an authoring adapter only: this script renders the demo to static
 * HTML, writes deterministic CSS/assets, and ships no React runtime.
 */

import { buildDesignSystemRuntime } from "./design-system/scripts/build.ts";
import { renderDesignSystemDemo } from "./page-src/design-system-demo.tsx";

const SITE_ROOT = new URL("./", import.meta.url);
const PAGE_ROOT = new URL("pages/", SITE_ROOT);
const ASSET_ROOT = new URL("pages/assets/design-system/", SITE_ROOT);
const SOURCE_ROOT = new URL("page-src/", SITE_ROOT);

async function writeGeneratedCopy(
  source: string,
  destination: string,
): Promise<void> {
  const body = await Deno.readTextFile(new URL(source, SOURCE_ROOT));
  await Deno.writeTextFile(
    new URL(destination, ASSET_ROOT),
    `/* Generated by site/build.ts from site/page-src/${source}. Do not edit. */\n${body}`,
  );
}

await Deno.mkdir(ASSET_ROOT, { recursive: true });
const summary = await buildDesignSystemRuntime(ASSET_ROOT);
await writeGeneratedCopy("design-system-demo.css", "demo.css");
await writeGeneratedCopy("design-system-demo.js", "demo.js");
await writeGeneratedCopy("design-system-fonts.css", "fonts.css");
await Deno.writeTextFile(
  new URL("design-system-demo.html", PAGE_ROOT),
  renderDesignSystemDemo(summary),
);

console.log(
  `Built the static design-system demo from ${summary.components} components and ${summary.tokens} tokens.`,
);
