// GENERATED by `deno task codegen` from src/shared/result_contracts.ts and src/shared/result_schemas.ts. Do NOT edit by hand.

export type DiscernSetupResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup";
  data?: {
    phase?: "fresh" | "in_progress" | "done";
    complete?: boolean;
    next_action?: string;
    agent_guidance?: string;
    human_framing?: string;
    progress?: {
      pending_markers: Array<string>;
      capabilities: Array<{
        name: string;
        wired: boolean;
      }>;
    };
    already_set_up?: boolean;
    message?: string;
    project?: {
      slug: string;
      agents: Array<string>;
    };
    plan?: Array<{
      path: string;
      action: "create" | "skip" | "merge" | "append";
      note?: string;
    }>;
    guidance?: string;
    command?: string;
    bootstrapped?: boolean;
    branch?: string | null;
    machinery_committed?: boolean;
    kit_version?: string;
    written?: Array<string>;
    compiled?: Array<string>;
    mcp_wired?: Array<string>;
    hooks_wired?: Array<string>;
    worktree_app_wired?: Array<string>;
    project_rules_wired?: Array<string>;
    guidelines_compiled?: boolean;
    guidelines_errors?: Array<string>;
    skeletons?: Array<string>;
    skipped?: Array<string>;
    instructions?: string;
    page?: {
      step: number;
      title: string;
      spine: {
        intent: string;
        files_to_read: Array<string>;
        must_do: Array<string>;
        what_not_to_do: Array<string>;
        completion_check: string;
        next_action: string;
      };
      guidance: string;
    } | null;
    changes?: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSetupVerifyResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup verify";
  data?: {
    phase: "fresh" | "in_progress" | "done";
    next_action: string;
    ready?: boolean;
    findings?: {
      git: {
        repo: boolean;
        clean: boolean;
        uncommitted: number;
      };
      docs: {
        exists: boolean;
      };
      existing_instructions: Array<string>;
      agents_detected: Array<string>;
      agents_effective: Array<string>;
      worktree_path: string;
    };
    conflicts?: Array<{
      kind: "existing_instructions" | "dirty_tree" | "not_a_repo";
      detail: string;
    }>;
    guidance?: string;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSetupStepResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup step";
  data?: {
    step: number;
    title: string;
    spine: {
      intent: string;
      files_to_read: Array<string>;
      must_do: Array<string>;
      what_not_to_do: Array<string>;
      completion_check: string;
      next_action: string;
    };
    guidance: string;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSetupDoneResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup done";
  data?: {
    bootstrapped: true;
    forced: boolean;
    gate_proven: boolean;
    worktree_proven: boolean;
    marker_committed: boolean;
    leftover: Array<string>;
    assurance: {
      capabilities: Array<{
        name: string;
        state: "enforced" | "deferred" | "absent";
        reason?: string;
      }>;
      enforced: number;
      total: number;
      verdict: "full" | "partial" | "minimal";
    };
    landing: {
      in_repo: boolean;
      branch: string;
      target: string;
      on_target: boolean;
      command: string;
    };
    reactivation: {
      summary: string;
      per_agent: Array<{
        agent: string;
        label: string;
        step: string;
      }>;
    };
    coach: {
      verb: string;
      command: string;
    };
    guidance: string;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSetupLandResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup land";
  data?: {
    landed: boolean;
    branch: string;
    target: string;
    fast_forward: boolean;
    branch_deleted: boolean;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernUpgradeResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "upgrade";
  data?: {
    check?: boolean;
    schema?: {
      recorded?: number;
      from?: number;
      current: number;
    };
    pending_migrations?: Array<{
      from: number;
      to: number;
      describe: string;
    }>;
    pending_reconciliation?: Array<{
      kind: "section" | "key";
      path: string;
    }>;
    config_template_available?: boolean;
    pending_gitignore_reconciliation?: Array<{
      kind: "create-block" | "replace-block";
      path: string;
    }>;
    gitignore_template_available?: boolean;
    changes?: Array<string>;
    issues?: Array<{
      path: string;
      message: string;
    }>;
    kit_version?: string;
    migrations_applied?: Array<{
      from: number;
      to: number;
      describe: string;
    }>;
    config_reconciled?: Array<{
      kind: "section" | "key";
      path: string;
    }>;
    gitignore_reconciled?: Array<{
      kind: "create-block" | "replace-block";
      path: string;
    }>;
    skills?: {
      copied: number;
      linked: number;
      pruned: number;
    } | null;
    agents_written?: Array<string>;
    mcp_wired?: Array<string>;
    hooks_wired?: Array<string>;
    worktree_app_wired?: Array<string>;
    project_rules_wired?: Array<string>;
    guidelines_compiled?: boolean;
    guidelines_errors?: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernDoctorResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "doctor";
  data?: {
    kit_version: string;
    environment: {
      discern: string;
      platform: string;
      git?: string;
    };
    checks: Array<{
      name: string;
      status: "ok" | "warn" | "fail";
      ok: boolean;
      detail: string;
      fix?: string;
      warn?: boolean;
    }>;
    execution_model?: Array<{
      verb: string;
      when: string;
      steps: Array<{
        kind:
          | "job"
          | "scope-gate"
          | "merge-check"
          | "tracked-artifacts-check"
          | "guidance-check"
          | "skills-check"
          | "resource-create"
          | "resource-destroy"
          | "git"
          | "setup-step"
          | "setup-ensure"
          | "env"
          | "refresh"
          | "ratchet";
        label: string;
        actor: "project" | "discern";
        note?: string;
        hint?: string;
        condition?: string;
      }>;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernPresetResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "preset";
  data?: {
    preset?: string;
    available?: Array<string>;
    plan?: Array<{
      path: string;
      action: "create" | "skip" | "merge" | "append";
      note?: string;
    }>;
    config_fills?: boolean;
    written?: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernDocsResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "docs";
  data?: {
    docs_dir?: string;
    count?: number;
    docs?: Array<{
      path: string;
      section: string;
      slug: string;
      title: string;
    }>;
    doc?: {
      path: string;
      section: string;
      slug: string;
      title: string;
      content: string;
    };
    candidates?: Array<string>;
    suggestions?: Array<{
      path: string;
      section: string;
      slug: string;
      title: string;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernHelpResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "help";
  data?: {
    docs_dir?: string;
    count?: number;
    docs?: Array<{
      path: string;
      section: string;
      slug: string;
      title: string;
    }>;
    doc?: {
      path: string;
      section: string;
      slug: string;
      title: string;
      content: string;
    };
    candidates?: Array<string>;
    suggestions?: Array<{
      path: string;
      section: string;
      slug: string;
      title: string;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernConfigResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "config";
  data?: {
    file: string;
    edits: Array<{
      key: string;
      literal: string;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernFinishResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "finish";
  data?: {
    failed_stage:
      | "fix"
      | "build"
      | "check"
      | "test"
      | "check/test"
      | "scope_gates"
      | "fix_drift"
      | "tracked_artifacts"
      | "guidance"
      | "skills"
      | "merge"
      | null;
    scopes_changed: Array<string>;
    gate_receipt?: {
      status:
        | "recorded"
        | "skipped_dirty"
        | "unavailable"
        | "record_failed"
        | "cleared"
        | "clear_failed";
      path?: string;
      reason?: string;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernPrepareResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "prepare";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernTestResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "test";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernImproveResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "improve";
  data?: {
    score: number;
    weak: number;
    open_reviews: number;
    next_action: {
      kind: "fix" | "review";
      category: string;
      id: string;
      title: string;
      action: string;
      why: string;
    };
    categories: Array<{
      name: string;
      title: string;
      score: number;
      weight: number;
      weak: number;
      rules: Array<{
        id: string;
        title: string;
        status: "pass" | "partial" | "fail";
        weight: number;
        detail: string;
        fix?: string;
        teach: string;
      }>;
      reviews: Array<{
        id: string;
        title: string;
        ask: string;
        teach: string;
        against?: {
          source: string;
          excerpt: string;
        };
      }>;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernRatchetsResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "ratchets";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernRefreshResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "refresh";
  data?: {
    agents_written: Array<string>;
    mcp_wired: Array<string>;
    hooks_wired: Array<string>;
    worktree_app_wired: Array<string>;
    project_rules_wired: Array<string>;
    skills: {
      copied: number;
      linked: number;
      pruned: number;
    };
    errors: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernScopesResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "scopes";
  data?: {
    scopes: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernCouplingResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "coupling";
  data?: {
    mode: "diff" | "query" | "evidence";
    changed?: Array<string>;
    target?: string;
    partners: Array<{
      path: string;
      from: string;
      cochanges: number;
      of: number;
      confidence: number;
      lift: number;
    }>;
    a?: string;
    b?: string;
    together?: number;
    of_a?: number;
    of_b?: number;
    commits?: Array<{
      sha: string;
      date: string;
      subject: string;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernStatusResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "status";
  data?: {
    location: "main" | "worktree";
    root: string;
    worktree: {
      id: string;
      branch: string;
      site: string;
      port: number;
      db: string;
      resources: {
        [key: string]: string;
      };
    } | null;
    git: {
      branch: string;
      integration_branch: string;
      clean: boolean;
      changed_files: number;
      behind_integration: number | null;
      ahead_integration: number;
      incoming_overlap?: Array<string>;
    } | null;
    scopes?: Array<string>;
    gate?: {
      capabilities: Array<string>;
      checks: Array<string>;
      scope_gates: Array<string>;
    };
    features: {
      worktrees: boolean;
      ratchets: boolean;
      guidance: boolean;
      skills: boolean;
      docs: boolean;
      coupling: boolean;
    };
    ratchets: Array<string>;
    gate_receipt?: {
      status:
        | "honored"
        | "missing"
        | "stale"
        | "dirty"
        | "unavailable"
        | "read_failed";
      path?: string;
      recorded?: string;
      head?: string;
      reason?: string;
    };
    stale_generated?: Array<string>;
    stale_materialized?: Array<string>;
    stale_integrations?: Array<string>;
    tracked_ignored_artifacts?: Array<string>;
    setup_unfinished?: {
      pending_markers: Array<string>;
      capabilities: Array<{
        name: string;
        wired: boolean;
      }>;
    };
    fleet?: Array<{
      path: string;
      is_main: boolean;
      is_current: boolean;
      branch: string;
      clean: boolean;
      changed_files: number;
      ahead: number;
      behind: number;
      last_activity?: string;
      id?: string;
      port?: number;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernStartResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "start";
  data?: {
    id: string;
    branch: string;
    path: string;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernGraduateResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "graduate";
  data?: {
    root: string;
    gate_validation?: {
      mode: "receipt" | "rerun";
      receipt: {
        status:
          | "honored"
          | "missing"
          | "stale"
          | "dirty"
          | "unavailable"
          | "read_failed";
        path?: string;
        recorded?: string;
        head?: string;
        reason?: string;
      };
    };
    ignored_file_changes?: {
      status:
        | "disabled"
        | "baseline_missing"
        | "unavailable"
        | "unchanged"
        | "changed";
      changed_roots: Array<string>;
      changed_total: number;
      truncated: boolean;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernIntegrateResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "integrate";
  data?: {
    behind: number;
    fast_forward: boolean;
    commits: Array<{
      sha: string;
      subject: string;
    }>;
    commits_total: number;
    commits_truncated: boolean;
    files: Array<{
      path: string;
      status: string;
      added: number | null;
      removed: number | null;
    }>;
    files_total: number;
    files_truncated: boolean;
    overlap: Array<string>;
    overlap_total: number;
    scopes_incoming: Array<string>;
    range: {
      base: string;
      before: string;
      main: string;
      after?: string;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernWorktreeSetupResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "worktree setup";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernWorktreeTeardownResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "worktree teardown";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernWorktreePruneResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "worktree prune";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSkillsListResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "skills list";
  data?: {
    skills: Array<{
      name: string;
      source: "authored" | "bundled";
      overridesBundled: boolean;
      hasBundled: boolean;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSkillsEjectResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "ratchet";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "ratchet";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "skills eject";
  data?: {
    name: string;
    dest_abs: string;
    dest_rel: string;
    skills_dir_persisted: boolean;
    materialized: {
      copied: number;
      linked: number;
      pruned: number;
      errors: Array<string>;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernCliJsonResult =
  | DiscernSetupResult
  | DiscernSetupVerifyResult
  | DiscernSetupStepResult
  | DiscernSetupDoneResult
  | DiscernSetupLandResult
  | DiscernUpgradeResult
  | DiscernDoctorResult
  | DiscernPresetResult
  | DiscernDocsResult
  | DiscernHelpResult
  | DiscernConfigResult
  | DiscernFinishResult
  | DiscernPrepareResult
  | DiscernTestResult
  | DiscernImproveResult
  | DiscernRatchetsResult
  | DiscernRefreshResult
  | DiscernScopesResult
  | DiscernCouplingResult
  | DiscernStatusResult
  | DiscernStartResult
  | DiscernGraduateResult
  | DiscernIntegrateResult
  | DiscernWorktreeSetupResult
  | DiscernWorktreeTeardownResult
  | DiscernWorktreePruneResult
  | DiscernSkillsListResult
  | DiscernSkillsEjectResult;

export interface DiscernResultByVerb {
  setup: DiscernSetupResult;
  "setup verify": DiscernSetupVerifyResult;
  "setup step": DiscernSetupStepResult;
  "setup done": DiscernSetupDoneResult;
  "setup land": DiscernSetupLandResult;
  upgrade: DiscernUpgradeResult;
  doctor: DiscernDoctorResult;
  preset: DiscernPresetResult;
  docs: DiscernDocsResult;
  help: DiscernHelpResult;
  config: DiscernConfigResult;
  finish: DiscernFinishResult;
  prepare: DiscernPrepareResult;
  test: DiscernTestResult;
  improve: DiscernImproveResult;
  ratchets: DiscernRatchetsResult;
  refresh: DiscernRefreshResult;
  scopes: DiscernScopesResult;
  coupling: DiscernCouplingResult;
  status: DiscernStatusResult;
  start: DiscernStartResult;
  graduate: DiscernGraduateResult;
  integrate: DiscernIntegrateResult;
  "worktree setup": DiscernWorktreeSetupResult;
  "worktree teardown": DiscernWorktreeTeardownResult;
  "worktree prune": DiscernWorktreePruneResult;
  "skills list": DiscernSkillsListResult;
  "skills eject": DiscernSkillsEjectResult;
}

export interface DiscernResultByCommand {
  setup: DiscernSetupResult;
  "setup begin": DiscernSetupResult;
  "setup verify": DiscernSetupVerifyResult;
  "setup step": DiscernSetupStepResult;
  "setup done": DiscernSetupDoneResult;
  "setup land": DiscernSetupLandResult;
  upgrade: DiscernUpgradeResult;
  doctor: DiscernDoctorResult;
  preset: DiscernPresetResult;
  docs: DiscernDocsResult;
  help: DiscernHelpResult;
  "config set-capability": DiscernConfigResult;
  "config set-check": DiscernConfigResult;
  "config set-scope": DiscernConfigResult;
  "config set-ratchet": DiscernConfigResult;
  "config set": DiscernConfigResult;
  finish: DiscernFinishResult;
  prepare: DiscernPrepareResult;
  test: DiscernTestResult;
  improve: DiscernImproveResult;
  ratchets: DiscernRatchetsResult;
  refresh: DiscernRefreshResult;
  scopes: DiscernScopesResult;
  coupling: DiscernCouplingResult;
  status: DiscernStatusResult;
  start: DiscernStartResult;
  graduate: DiscernGraduateResult;
  integrate: DiscernIntegrateResult;
  "worktree setup": DiscernWorktreeSetupResult;
  "worktree teardown": DiscernWorktreeTeardownResult;
  "worktree prune": DiscernWorktreePruneResult;
  "skills list": DiscernSkillsListResult;
  "skills eject": DiscernSkillsEjectResult;
}

export interface DiscernMcpTextContent {
  type: "text";
  text: string;
}

export interface DiscernMcpToolResult<TStructuredContent> {
  content: DiscernMcpTextContent[];
  structuredContent: TStructuredContent;
  isError: boolean;
}

export interface DiscernMcpStructuredContentByTool {
  discern_doctor: DiscernDoctorResult;
  discern_docs: DiscernDocsResult;
  discern_help: DiscernHelpResult;
  discern_finish: DiscernFinishResult;
  discern_prepare: DiscernPrepareResult;
  discern_test: DiscernTestResult;
  discern_improve: DiscernImproveResult;
  discern_ratchets: DiscernRatchetsResult;
  discern_refresh: DiscernRefreshResult;
  discern_scopes: DiscernScopesResult;
  discern_coupling: DiscernCouplingResult;
  discern_status: DiscernStatusResult;
  discern_start: DiscernStartResult;
  discern_graduate: DiscernGraduateResult;
  discern_integrate: DiscernIntegrateResult;
}

export interface DiscernMcpToolResultByTool {
  discern_doctor: DiscernMcpToolResult<DiscernDoctorResult>;
  discern_docs: DiscernMcpToolResult<DiscernDocsResult>;
  discern_help: DiscernMcpToolResult<DiscernHelpResult>;
  discern_finish: DiscernMcpToolResult<DiscernFinishResult>;
  discern_prepare: DiscernMcpToolResult<DiscernPrepareResult>;
  discern_test: DiscernMcpToolResult<DiscernTestResult>;
  discern_improve: DiscernMcpToolResult<DiscernImproveResult>;
  discern_ratchets: DiscernMcpToolResult<DiscernRatchetsResult>;
  discern_refresh: DiscernMcpToolResult<DiscernRefreshResult>;
  discern_scopes: DiscernMcpToolResult<DiscernScopesResult>;
  discern_coupling: DiscernMcpToolResult<DiscernCouplingResult>;
  discern_status: DiscernMcpToolResult<DiscernStatusResult>;
  discern_start: DiscernMcpToolResult<DiscernStartResult>;
  discern_graduate: DiscernMcpToolResult<DiscernGraduateResult>;
  discern_integrate: DiscernMcpToolResult<DiscernIntegrateResult>;
}

export type DiscernMcpStructuredContent =
  | DiscernDoctorResult
  | DiscernDocsResult
  | DiscernHelpResult
  | DiscernFinishResult
  | DiscernPrepareResult
  | DiscernTestResult
  | DiscernImproveResult
  | DiscernRatchetsResult
  | DiscernRefreshResult
  | DiscernScopesResult
  | DiscernCouplingResult
  | DiscernStatusResult
  | DiscernStartResult
  | DiscernGraduateResult
  | DiscernIntegrateResult;

export type DiscernMcpJsonResult =
  | DiscernDoctorMcpToolResult
  | DiscernDocsMcpToolResult
  | DiscernHelpMcpToolResult
  | DiscernFinishMcpToolResult
  | DiscernPrepareMcpToolResult
  | DiscernTestMcpToolResult
  | DiscernImproveMcpToolResult
  | DiscernRatchetsMcpToolResult
  | DiscernRefreshMcpToolResult
  | DiscernScopesMcpToolResult
  | DiscernCouplingMcpToolResult
  | DiscernStatusMcpToolResult
  | DiscernStartMcpToolResult
  | DiscernGraduateMcpToolResult
  | DiscernIntegrateMcpToolResult;

export type DiscernDoctorMcpToolResult = DiscernMcpToolResult<
  DiscernDoctorResult
>;

export type DiscernDocsMcpToolResult = DiscernMcpToolResult<DiscernDocsResult>;

export type DiscernHelpMcpToolResult = DiscernMcpToolResult<DiscernHelpResult>;

export type DiscernFinishMcpToolResult = DiscernMcpToolResult<
  DiscernFinishResult
>;

export type DiscernPrepareMcpToolResult = DiscernMcpToolResult<
  DiscernPrepareResult
>;

export type DiscernTestMcpToolResult = DiscernMcpToolResult<DiscernTestResult>;

export type DiscernImproveMcpToolResult = DiscernMcpToolResult<
  DiscernImproveResult
>;

export type DiscernRatchetsMcpToolResult = DiscernMcpToolResult<
  DiscernRatchetsResult
>;

export type DiscernRefreshMcpToolResult = DiscernMcpToolResult<
  DiscernRefreshResult
>;

export type DiscernScopesMcpToolResult = DiscernMcpToolResult<
  DiscernScopesResult
>;

export type DiscernCouplingMcpToolResult = DiscernMcpToolResult<
  DiscernCouplingResult
>;

export type DiscernStatusMcpToolResult = DiscernMcpToolResult<
  DiscernStatusResult
>;

export type DiscernStartMcpToolResult = DiscernMcpToolResult<
  DiscernStartResult
>;

export type DiscernGraduateMcpToolResult = DiscernMcpToolResult<
  DiscernGraduateResult
>;

export type DiscernIntegrateMcpToolResult = DiscernMcpToolResult<
  DiscernIntegrateResult
>;
