// GENERATED by `deno task codegen` from src/shared/result_contracts.ts and src/shared/result_schemas.ts. Do NOT edit by hand.

export type DiscernSetupResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup";
  data?: {
    phase?: "fresh" | "in_progress" | "done";
    complete?: boolean;
    next_action?: string;
    agent_guidance?: string;
    human_framing?: string;
    progress?: {
      pending_markers: Array<string>;
      known_jobs: Array<{
        name: string;
        wired: boolean;
      }>;
    };
    already_set_up?: boolean;
    message?: string;
    project?: {
      slug: string;
      agents: Array<string>;
    };
    plan?: Array<{
      path: string;
      action: "create" | "skip" | "merge" | "append";
      note?: string;
    }>;
    guidance?: string;
    command?: string;
    bootstrapped?: boolean;
    branch?: string | null;
    machinery_committed?: boolean;
    machinery_commit_error?: string;
    kit_version?: string;
    written?: Array<string>;
    compiled?: Array<string>;
    mcp_wired?: Array<string>;
    hooks_wired?: Array<string>;
    worktree_app_wired?: Array<string>;
    project_rules_wired?: Array<string>;
    guidelines_compiled?: boolean;
    guidelines_errors?: Array<string>;
    skeletons?: Array<string>;
    skipped?: Array<string>;
    instructions?: string;
    page?: {
      step: number;
      title: string;
      spine: {
        intent: string;
        files_to_read: Array<string>;
        must_do: Array<string>;
        what_not_to_do: Array<string>;
        completion_check: string;
        next_action: string;
      };
      guidance: string;
    } | null;
    changes?: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSetupVerifyResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup verify";
  data?: {
    phase: "fresh" | "in_progress" | "done";
    next_action: string;
    ready?: boolean;
    findings?: {
      git: {
        repo: boolean;
        clean: boolean;
        uncommitted: number;
        identity: boolean;
      };
      docs: {
        exists: boolean;
      };
      existing_instructions: Array<string>;
      agents_detected: Array<string>;
      agents_effective: Array<string>;
      worktree_path: string;
    };
    conflicts?: Array<{
      kind:
        | "existing_instructions"
        | "dirty_tree"
        | "not_a_repo"
        | "missing_git_identity";
      detail: string;
    }>;
    guidance?: string;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSetupStepResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup step";
  data?: {
    step: number;
    title: string;
    spine: {
      intent: string;
      files_to_read: Array<string>;
      must_do: Array<string>;
      what_not_to_do: Array<string>;
      completion_check: string;
      next_action: string;
    };
    guidance: string;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSetupDoneResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup done";
  data?: {
    bootstrapped: true;
    forced: boolean;
    gate_proven: boolean;
    worktree_proven: boolean;
    marker_committed: boolean;
    marker_commit_error?: string;
    leftover: Array<string>;
    assurance: {
      known_jobs: Array<{
        name: string;
        state: "enforced" | "deferred" | "absent";
        reason?: string;
      }>;
      enforced: number;
      total: number;
      verdict: "full" | "partial" | "minimal";
    };
    landing: {
      in_repo: boolean;
      branch: string;
      target: string;
      on_target: boolean;
      on_setup_branch: boolean;
      command: string;
    };
    reactivation: {
      summary: string;
      per_agent: Array<{
        agent: string;
        label: string;
        step: string;
      }>;
    };
    coach: {
      verb: string;
      command: string;
    };
    guidance: string;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSetupAcceptResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "setup accept";
  data?: {
    landed: boolean;
    branch: string;
    target: string;
    fast_forward: boolean;
    branch_deleted: boolean;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernUpgradeResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "upgrade";
  data?: {
    check?: boolean;
    schema?: {
      recorded?: number;
      from?: number;
      current: number;
    };
    pending_migrations?: Array<{
      from: number;
      to: number;
      describe: string;
    }>;
    pending_reconciliation?: Array<{
      kind: "section" | "key" | "banner";
      path: string;
    }>;
    config_template_available?: boolean;
    pending_gitignore_reconciliation?: Array<{
      kind: "create-block" | "replace-block";
      path: string;
    }>;
    gitignore_template_available?: boolean;
    changes?: Array<string>;
    issues?: Array<{
      path: string;
      message: string;
    }>;
    kit_version?: string;
    migrations_applied?: Array<{
      from: number;
      to: number;
      describe: string;
    }>;
    config_reconciled?: Array<{
      kind: "section" | "key" | "banner";
      path: string;
    }>;
    gitignore_reconciled?: Array<{
      kind: "create-block" | "replace-block";
      path: string;
    }>;
    skills?: {
      copied: number;
      linked: number;
      pruned: number;
    } | null;
    agents_written?: Array<string>;
    mcp_wired?: Array<string>;
    hooks_wired?: Array<string>;
    worktree_app_wired?: Array<string>;
    project_rules_wired?: Array<string>;
    guidelines_compiled?: boolean;
    guidelines_errors?: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernUninstallResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "uninstall";
  data?: {
    removed?: Array<string>;
    stripped?: Array<string>;
    kept?: Array<string>;
    binary_hint?: string;
    worktrees?: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernDoctorResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "doctor";
  data?: {
    kit_version: string;
    environment: {
      discern: string;
      platform: string;
      git?: string;
      desk_session?: true;
    };
    checks: Array<{
      name: string;
      status: "ok" | "warn" | "fail";
      ok: boolean;
      detail: string;
      fix?: string;
      warn?: boolean;
    }>;
    execution_model?: Array<{
      verb: string;
      when: string;
      steps: Array<{
        kind:
          | "job"
          | "scope-gate"
          | "merge-check"
          | "standards-limits-check"
          | "tracked-artifacts-check"
          | "guidance-check"
          | "skills-check"
          | "resource-create"
          | "resource-destroy"
          | "git"
          | "setup-step"
          | "repository-ensure"
          | "checkout-clean-check"
          | "setup-ensure"
          | "env"
          | "refresh"
          | "tidy"
          | "standard";
        label: string;
        actor: "project" | "discern";
        note?: string;
        hint?: string;
        condition?: string;
      }>;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernPresetResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "preset";
  data?: {
    preset?: string;
    available?: Array<string>;
    plan?: Array<{
      path: string;
      action: "create" | "skip" | "merge" | "append";
      note?: string;
    }>;
    config_fills?: boolean;
    config_fills_applied?: Array<string>;
    config_fills_skipped?: Array<string>;
    written?: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernMapResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "map";
  data?: {
    map_dir?: string;
    count?: number;
    docs?: Array<{
      path: string;
      section: string;
      slug: string;
      title: string;
      description: string;
      publish?: boolean;
      order?: number;
      aliases?: Array<string>;
    }>;
    regions?: Array<{
      name: string;
      title: string;
      description: string;
      page_count: number;
      pages_changed_at?: string;
      code_changes_since?: number;
    }>;
    doc?: {
      path: string;
      section: string;
      slug: string;
      title: string;
      description: string;
      publish?: boolean;
      order?: number;
      aliases?: Array<string>;
      content: string;
      cited_adrs?: Array<{
        number: string;
        slug: string;
        path: string;
      }>;
    };
    candidates?: Array<string>;
    suggestions?: Array<{
      path: string;
      section: string;
      slug: string;
      title: string;
      description: string;
      publish?: boolean;
      order?: number;
      aliases?: Array<string>;
    }>;
    query?: string;
    scope?: string;
    results?: Array<{
      target: string;
      path: string;
      section: string;
      title: string;
      description: string;
      match: "complete" | "partial" | "metadata";
      heading?: string;
      snippet: string;
    }>;
    truncated?: boolean;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernHelpResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "help";
  data?: {
    map_dir?: string;
    count?: number;
    docs?: Array<{
      path: string;
      section: string;
      slug: string;
      title: string;
      description: string;
      publish?: boolean;
      order?: number;
      aliases?: Array<string>;
    }>;
    regions?: Array<{
      name: string;
      title: string;
      description: string;
      page_count: number;
      pages_changed_at?: string;
      code_changes_since?: number;
    }>;
    doc?: {
      path: string;
      section: string;
      slug: string;
      title: string;
      description: string;
      publish?: boolean;
      order?: number;
      aliases?: Array<string>;
      content: string;
      cited_adrs?: Array<{
        number: string;
        slug: string;
        path: string;
      }>;
    };
    candidates?: Array<string>;
    suggestions?: Array<{
      path: string;
      section: string;
      slug: string;
      title: string;
      description: string;
      publish?: boolean;
      order?: number;
      aliases?: Array<string>;
    }>;
    query?: string;
    scope?: string;
    results?: Array<{
      target: string;
      path: string;
      section: string;
      title: string;
      description: string;
      match: "complete" | "partial" | "metadata";
      heading?: string;
      snippet: string;
    }>;
    truncated?: boolean;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernConfigResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "config";
  data?: {
    file: string;
    edits: Array<{
      key: string;
      literal: string;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernDoneResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "done";
  data?: {
    failed_stage:
      | "fix"
      | "build"
      | "check"
      | "test"
      | "check/test"
      | "scope_gates"
      | "tree_drift"
      | "tracked_artifacts"
      | "guidance"
      | "skills"
      | "skill_frontmatter"
      | "adr_numbers"
      | "merge"
      | "standards"
      | "write_access"
      | null;
    scopes_changed: Array<string>;
    standards?: Array<{
      name: string;
      direction: "up" | "down";
      limit: number;
      measurement: "measured" | "replayed" | "deferred" | "skipped";
      value?: number;
      verdict?: "improved" | "held" | "regressed";
      duration_s?: number;
      replayed_from?: string;
    }>;
    standards_limits?: {
      status: "verified" | "loosened" | "unverified" | "parse_failed";
      trunk: string;
      reason?: string;
    };
    receipt?: {
      branch: string;
      trunk: string;
      commits: Array<{
        sha: string;
        subject: string;
      }>;
      commits_total: number;
      files: Array<{
        path: string;
        status: string;
        added: number | null;
        removed: number | null;
      }>;
      files_total: number;
      insertions: number;
      deletions: number;
      markdown: string;
    };
    gate_receipt?: {
      status:
        | "recorded"
        | "skipped_dirty"
        | "skipped_head_moved"
        | "unavailable"
        | "record_failed"
        | "cleared"
        | "clear_failed";
      path?: string;
      reason?: string;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernPrepareResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "prepare";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernTestResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "test";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernImprovementResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "improvement";
  data?: {
    score: number;
    weak: number;
    open_reviews: number;
    next_action: {
      kind: "fix" | "review";
      category: string;
      id: string;
      title: string;
      action: string;
      why: string;
      against?: {
        source: string;
        excerpt: string;
      };
    };
    categories: Array<{
      name: string;
      title: string;
      score: number;
      weight: number;
      weak: number;
      rules: Array<{
        id: string;
        title: string;
        status: "pass" | "partial" | "fail";
        weight: number;
        detail: string;
        fix?: string;
        teach: string;
      }>;
      reviews: Array<{
        id: string;
        title: string;
        ask: string;
        teach: string;
        against?: {
          source: string;
          excerpt: string;
        };
      }>;
    }>;
    history: {
      findings: Array<{
        detector: string;
        family: "behaviour" | "gate-fit" | "funnel" | "trajectory";
        scope: "branch" | "session" | "project";
        subject?: string;
        observed: string;
        evidence: {
          [key: string]: number;
        };
        strength: number;
        next_step: string;
      }>;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernStandardsResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "standards";
  data?: {
    standards?: Array<{
      name: string;
      direction: "up" | "down";
      limit: number;
      measurement: "measured" | "replayed" | "deferred" | "skipped";
      value?: number;
      verdict?: "improved" | "held" | "regressed";
      duration_s?: number;
      replayed_from?: string;
    }>;
    pinned?: Array<{
      name: string;
      from: number;
      to: number;
      measured: number;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernRefreshResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "refresh";
  data?: {
    agents_written: Array<string>;
    mcp_wired: Array<string>;
    hooks_wired: Array<string>;
    worktree_app_wired: Array<string>;
    project_rules_wired: Array<string>;
    skills: {
      copied: number;
      linked: number;
      pruned: number;
    };
    errors: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernTidyResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "tidy";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernImpactResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "impact";
  data?: {
    scopes: Array<string>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernCouplingResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "coupling";
  data?: {
    mode: "diff" | "query" | "evidence";
    changed?: Array<string>;
    target?: string;
    partners: Array<{
      path: string;
      from: string;
      cochanges: number;
      of: number;
      confidence: number;
      lift: number;
    }>;
    a?: string;
    b?: string;
    together?: number;
    of_a?: number;
    of_b?: number;
    commits?: Array<{
      sha: string;
      date: string;
      subject: string;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernPatternsResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "patterns";
  data?: {
    logbook: {
      events: number;
      unparsed: number;
      months: number;
      first_at?: string;
      last_at?: string;
      branches: number;
      recording: boolean;
    };
    population: {
      analyzed: number;
      agent: number;
      human: number;
      unknown: number;
      identities: Array<{
        agent: string;
        label: string;
        runs: number;
      }>;
    };
    findings: Array<{
      detector: string;
      family: "behaviour" | "gate-fit" | "funnel" | "trajectory";
      scope: "branch" | "session" | "project";
      subject?: string;
      observed: string;
      evidence: {
        [key: string]: number;
      };
      strength: number;
      next_step: string;
    }>;
    detectors: Array<{
      id: string;
      title: string;
      family: "behaviour" | "gate-fit" | "funnel" | "trajectory";
      scope: "branch" | "session" | "project";
      tier: "inline" | "batch";
      status: "fired" | "quiet" | "insufficient-evidence";
      considered: number;
      threshold: number;
      findings: number;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernPatternsResetResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "patterns reset";
  data?: {
    dir: string;
    removed: Array<{
      file: string;
      bytes: number;
    }>;
    bytes: number;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernStatusResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "status";
  data?: {
    location: "main" | "worktree";
    root: string;
    worktree: {
      id: string;
      branch: string;
      site: string;
      port: number;
      db: string;
      resources: {
        [key: string]: string;
      };
    } | null;
    git: {
      branch: string;
      integration_branch: string;
      clean: boolean;
      changed_files: number;
      behind_integration: number | null;
      ahead_integration: number | null;
      incoming_overlap?: Array<string>;
    } | null;
    scopes?: Array<string>;
    gate?: {
      jobs: Array<string>;
      scope_gates: Array<string>;
    };
    standards: Array<string>;
    gate_receipt?: {
      status:
        | "honored"
        | "missing"
        | "stale"
        | "dirty"
        | "unavailable"
        | "read_failed";
      path?: string;
      recorded?: string;
      head?: string;
      reason?: string;
      receipt?: string;
    };
    stale_generated?: Array<string>;
    stale_materialized?: Array<string>;
    stale_integrations?: Array<string>;
    tracked_ignored_artifacts?: Array<string>;
    setup_unfinished?: {
      pending_markers: Array<string>;
      known_jobs: Array<{
        name: string;
        wired: boolean;
      }>;
    };
    unlanded_branches?: Array<string>;
    fleet?: Array<{
      path: string;
      is_main: boolean;
      is_current: boolean;
      branch: string;
      clean?: boolean;
      changed_files?: number;
      ahead?: number;
      behind?: number;
      last_activity?: string;
      git_unavailable?: boolean;
      id?: string;
      port?: number;
      broken?: boolean;
    }>;
    fleet_collisions?: Array<{
      branches: unknown;
      overlap: Array<string>;
      total: number;
    }>;
    adr_collisions?: Array<{
      number: string;
      branches: Array<string>;
      paths: Array<string>;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernStartResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "start";
  data?: {
    id: string;
    branch: string;
    path: string;
    from: string;
    name_note?: string;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernAcceptResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "accept";
  data?: {
    root: string;
    gate_validation?: {
      mode: "receipt" | "rerun";
      receipt: {
        status:
          | "honored"
          | "missing"
          | "stale"
          | "dirty"
          | "unavailable"
          | "read_failed";
        path?: string;
        recorded?: string;
        head?: string;
        reason?: string;
        receipt?: string;
      };
    };
    receipt?: string;
    ignored_file_changes?: {
      status:
        | "disabled"
        | "baseline_missing"
        | "unavailable"
        | "unchanged"
        | "changed";
      changed_roots: Array<string>;
      changed_total: number;
      truncated: boolean;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernUpdateResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "update";
  data?: {
    behind: number;
    fast_forward: boolean;
    commits: Array<{
      sha: string;
      subject: string;
    }>;
    commits_total: number;
    commits_truncated: boolean;
    files: Array<{
      path: string;
      status: string;
      added: number | null;
      removed: number | null;
    }>;
    files_total: number;
    files_truncated: boolean;
    overlap: Array<string>;
    overlap_total: number;
    scopes_incoming: Array<string>;
    range: {
      base: string;
      before: string;
      main: string;
      after?: string;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernWorktreeSetupResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "worktree setup";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernWorktreeTeardownResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "worktree teardown";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernWorktreeDropResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "worktree drop";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernWorktreePruneResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "worktree prune";
  data?: {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSkillsListResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "skills list";
  data?: {
    skills: Array<{
      name: string;
      source: "authored" | "bundled";
      overridesBundled: boolean;
      hasBundled: boolean;
      excluded: boolean;
    }>;
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernSkillsEjectResult = {
  ok: boolean;
  dry_run?: boolean;
  plan?: {
    title: string;
    details: Array<string>;
    steps: Array<{
      kind:
        | "job"
        | "scope-gate"
        | "merge-check"
        | "standards-limits-check"
        | "tracked-artifacts-check"
        | "guidance-check"
        | "skills-check"
        | "resource-create"
        | "resource-destroy"
        | "git"
        | "setup-step"
        | "repository-ensure"
        | "checkout-clean-check"
        | "setup-ensure"
        | "env"
        | "refresh"
        | "tidy"
        | "standard";
      label: string;
      disposition: "run" | "skip" | "gate";
      note?: string;
      group?: string;
    }>;
  };
  steps?: Array<{
    kind:
      | "job"
      | "scope-gate"
      | "merge-check"
      | "standards-limits-check"
      | "tracked-artifacts-check"
      | "guidance-check"
      | "skills-check"
      | "resource-create"
      | "resource-destroy"
      | "git"
      | "setup-step"
      | "repository-ensure"
      | "checkout-clean-check"
      | "setup-ensure"
      | "env"
      | "refresh"
      | "tidy"
      | "standard";
    label: string;
    disposition: "run" | "skip" | "gate";
    note?: string;
    group?: string;
    outcome: "ok" | "failed" | "skipped";
    duration_s?: number;
    output_path?: string;
    output_lines?: number;
    error_like_lines?: number;
  }>;
  diagnostics?: Array<{
    tool: string;
    severity: "error" | "warning";
    message: string;
    reproduce_cmd: string;
    output?: string;
    truncated?: boolean;
    output_path?: string;
    file?: string;
    line?: number;
    col?: number;
    rule?: string;
    fix_available?: boolean;
  }>;
  hints?: Array<string>;
  error?: string;
  message?: string;
  verb: "skills eject";
  data?: {
    name: string;
    dest_abs: string;
    dest_rel: string;
    skills_dir_persisted: boolean;
    materialized: {
      copied: number;
      linked: number;
      pruned: number;
      errors: Array<string>;
    };
  } | {
    issues: Array<{
      path: string;
      message: string;
    }>;
  };
};

export type DiscernCliJsonResult =
  | DiscernSetupResult
  | DiscernSetupVerifyResult
  | DiscernSetupStepResult
  | DiscernSetupDoneResult
  | DiscernSetupAcceptResult
  | DiscernUpgradeResult
  | DiscernUninstallResult
  | DiscernDoctorResult
  | DiscernPresetResult
  | DiscernMapResult
  | DiscernHelpResult
  | DiscernConfigResult
  | DiscernDoneResult
  | DiscernPrepareResult
  | DiscernTestResult
  | DiscernImprovementResult
  | DiscernStandardsResult
  | DiscernRefreshResult
  | DiscernTidyResult
  | DiscernImpactResult
  | DiscernCouplingResult
  | DiscernPatternsResult
  | DiscernPatternsResetResult
  | DiscernStatusResult
  | DiscernStartResult
  | DiscernAcceptResult
  | DiscernUpdateResult
  | DiscernWorktreeSetupResult
  | DiscernWorktreeTeardownResult
  | DiscernWorktreeDropResult
  | DiscernWorktreePruneResult
  | DiscernSkillsListResult
  | DiscernSkillsEjectResult;

export interface DiscernResultByVerb {
  setup: DiscernSetupResult;
  "setup verify": DiscernSetupVerifyResult;
  "setup step": DiscernSetupStepResult;
  "setup done": DiscernSetupDoneResult;
  "setup accept": DiscernSetupAcceptResult;
  upgrade: DiscernUpgradeResult;
  uninstall: DiscernUninstallResult;
  doctor: DiscernDoctorResult;
  preset: DiscernPresetResult;
  map: DiscernMapResult;
  help: DiscernHelpResult;
  config: DiscernConfigResult;
  done: DiscernDoneResult;
  prepare: DiscernPrepareResult;
  test: DiscernTestResult;
  improvement: DiscernImprovementResult;
  standards: DiscernStandardsResult;
  refresh: DiscernRefreshResult;
  tidy: DiscernTidyResult;
  impact: DiscernImpactResult;
  coupling: DiscernCouplingResult;
  patterns: DiscernPatternsResult;
  "patterns reset": DiscernPatternsResetResult;
  status: DiscernStatusResult;
  start: DiscernStartResult;
  accept: DiscernAcceptResult;
  update: DiscernUpdateResult;
  "worktree setup": DiscernWorktreeSetupResult;
  "worktree teardown": DiscernWorktreeTeardownResult;
  "worktree drop": DiscernWorktreeDropResult;
  "worktree prune": DiscernWorktreePruneResult;
  "skills list": DiscernSkillsListResult;
  "skills eject": DiscernSkillsEjectResult;
}

export interface DiscernResultByCommand {
  setup: DiscernSetupResult;
  "setup begin": DiscernSetupResult;
  "setup verify": DiscernSetupVerifyResult;
  "setup step": DiscernSetupStepResult;
  "setup done": DiscernSetupDoneResult;
  "setup accept": DiscernSetupAcceptResult;
  upgrade: DiscernUpgradeResult;
  uninstall: DiscernUninstallResult;
  doctor: DiscernDoctorResult;
  preset: DiscernPresetResult;
  map: DiscernMapResult;
  help: DiscernHelpResult;
  "config set-job": DiscernConfigResult;
  "config set-scope": DiscernConfigResult;
  "config set-standard": DiscernConfigResult;
  "config set": DiscernConfigResult;
  done: DiscernDoneResult;
  prepare: DiscernPrepareResult;
  test: DiscernTestResult;
  improvement: DiscernImprovementResult;
  standards: DiscernStandardsResult;
  refresh: DiscernRefreshResult;
  tidy: DiscernTidyResult;
  impact: DiscernImpactResult;
  coupling: DiscernCouplingResult;
  patterns: DiscernPatternsResult;
  "patterns reset": DiscernPatternsResetResult;
  status: DiscernStatusResult;
  start: DiscernStartResult;
  accept: DiscernAcceptResult;
  update: DiscernUpdateResult;
  "worktree setup": DiscernWorktreeSetupResult;
  "worktree teardown": DiscernWorktreeTeardownResult;
  "worktree drop": DiscernWorktreeDropResult;
  "worktree prune": DiscernWorktreePruneResult;
  "skills list": DiscernSkillsListResult;
  "skills eject": DiscernSkillsEjectResult;
}

export interface DiscernMcpTextContent {
  type: "text";
  text: string;
}

export interface DiscernMcpToolResult<TStructuredContent> {
  content: DiscernMcpTextContent[];
  structuredContent: TStructuredContent;
  isError: boolean;
}

export interface DiscernMcpStructuredContentByTool {
  discern_doctor: DiscernDoctorResult;
  discern_map: DiscernMapResult;
  discern_help: DiscernHelpResult;
  discern_done: DiscernDoneResult;
  discern_prepare: DiscernPrepareResult;
  discern_test: DiscernTestResult;
  discern_improvement: DiscernImprovementResult;
  discern_standards: DiscernStandardsResult;
  discern_refresh: DiscernRefreshResult;
  discern_impact: DiscernImpactResult;
  discern_coupling: DiscernCouplingResult;
  discern_patterns: DiscernPatternsResult;
  discern_status: DiscernStatusResult;
  discern_start: DiscernStartResult;
  discern_accept: DiscernAcceptResult;
  discern_update: DiscernUpdateResult;
}

export interface DiscernMcpToolResultByTool {
  discern_doctor: DiscernMcpToolResult<DiscernDoctorResult>;
  discern_map: DiscernMcpToolResult<DiscernMapResult>;
  discern_help: DiscernMcpToolResult<DiscernHelpResult>;
  discern_done: DiscernMcpToolResult<DiscernDoneResult>;
  discern_prepare: DiscernMcpToolResult<DiscernPrepareResult>;
  discern_test: DiscernMcpToolResult<DiscernTestResult>;
  discern_improvement: DiscernMcpToolResult<DiscernImprovementResult>;
  discern_standards: DiscernMcpToolResult<DiscernStandardsResult>;
  discern_refresh: DiscernMcpToolResult<DiscernRefreshResult>;
  discern_impact: DiscernMcpToolResult<DiscernImpactResult>;
  discern_coupling: DiscernMcpToolResult<DiscernCouplingResult>;
  discern_patterns: DiscernMcpToolResult<DiscernPatternsResult>;
  discern_status: DiscernMcpToolResult<DiscernStatusResult>;
  discern_start: DiscernMcpToolResult<DiscernStartResult>;
  discern_accept: DiscernMcpToolResult<DiscernAcceptResult>;
  discern_update: DiscernMcpToolResult<DiscernUpdateResult>;
}

export type DiscernMcpStructuredContent =
  | DiscernDoctorResult
  | DiscernMapResult
  | DiscernHelpResult
  | DiscernDoneResult
  | DiscernPrepareResult
  | DiscernTestResult
  | DiscernImprovementResult
  | DiscernStandardsResult
  | DiscernRefreshResult
  | DiscernImpactResult
  | DiscernCouplingResult
  | DiscernPatternsResult
  | DiscernStatusResult
  | DiscernStartResult
  | DiscernAcceptResult
  | DiscernUpdateResult;

export type DiscernMcpJsonResult =
  | DiscernDoctorMcpToolResult
  | DiscernMapMcpToolResult
  | DiscernHelpMcpToolResult
  | DiscernDoneMcpToolResult
  | DiscernPrepareMcpToolResult
  | DiscernTestMcpToolResult
  | DiscernImprovementMcpToolResult
  | DiscernStandardsMcpToolResult
  | DiscernRefreshMcpToolResult
  | DiscernImpactMcpToolResult
  | DiscernCouplingMcpToolResult
  | DiscernPatternsMcpToolResult
  | DiscernStatusMcpToolResult
  | DiscernStartMcpToolResult
  | DiscernAcceptMcpToolResult
  | DiscernUpdateMcpToolResult;

export type DiscernDoctorMcpToolResult = DiscernMcpToolResult<
  DiscernDoctorResult
>;

export type DiscernMapMcpToolResult = DiscernMcpToolResult<DiscernMapResult>;

export type DiscernHelpMcpToolResult = DiscernMcpToolResult<DiscernHelpResult>;

export type DiscernDoneMcpToolResult = DiscernMcpToolResult<DiscernDoneResult>;

export type DiscernPrepareMcpToolResult = DiscernMcpToolResult<
  DiscernPrepareResult
>;

export type DiscernTestMcpToolResult = DiscernMcpToolResult<DiscernTestResult>;

export type DiscernImprovementMcpToolResult = DiscernMcpToolResult<
  DiscernImprovementResult
>;

export type DiscernStandardsMcpToolResult = DiscernMcpToolResult<
  DiscernStandardsResult
>;

export type DiscernRefreshMcpToolResult = DiscernMcpToolResult<
  DiscernRefreshResult
>;

export type DiscernImpactMcpToolResult = DiscernMcpToolResult<
  DiscernImpactResult
>;

export type DiscernCouplingMcpToolResult = DiscernMcpToolResult<
  DiscernCouplingResult
>;

export type DiscernPatternsMcpToolResult = DiscernMcpToolResult<
  DiscernPatternsResult
>;

export type DiscernStatusMcpToolResult = DiscernMcpToolResult<
  DiscernStatusResult
>;

export type DiscernStartMcpToolResult = DiscernMcpToolResult<
  DiscernStartResult
>;

export type DiscernAcceptMcpToolResult = DiscernMcpToolResult<
  DiscernAcceptResult
>;

export type DiscernUpdateMcpToolResult = DiscernMcpToolResult<
  DiscernUpdateResult
>;
