import type { BuildSummary } from "../src/runtime.ts";
import type { ComponentMeta } from "../src/types/component-meta.ts";
import { writeGeneratedSources } from "./generate.ts";

const ROOT = new URL("../", import.meta.url);
const COMPONENT_ROOT = new URL("../src/components/", import.meta.url);
export const DESIGN_SYSTEM_BUILD_OUTPUTS = {
  runtime: "dist/",
  catalogueRegistry: "styleguide/generated/",
} as const;
const GENERATED_ROOT = new URL(
  `../${DESIGN_SYSTEM_BUILD_OUTPUTS.catalogueRegistry}`,
  import.meta.url,
);
const DIST_ROOT = new URL(
  `../${DESIGN_SYSTEM_BUILD_OUTPUTS.runtime}`,
  import.meta.url,
);

interface ComponentSource {
  readonly metaUrl: URL;
  readonly examplesUrl: URL;
}

async function walk(directory: URL): Promise<URL[]> {
  const files: URL[] = [];
  for await (const entry of Deno.readDir(directory)) {
    const url = new URL(entry.name + (entry.isDirectory ? "/" : ""), directory);
    if (entry.isDirectory) files.push(...await walk(url));
    else files.push(url);
  }
  return files;
}

function relativeImport(fromDirectory: URL, target: URL): string {
  const fromParts = decodeURIComponent(fromDirectory.pathname).split("/")
    .filter(Boolean);
  const toParts = decodeURIComponent(target.pathname).split("/").filter(
    Boolean,
  );
  while (fromParts[0] === toParts[0]) {
    fromParts.shift();
    toParts.shift();
  }
  return `${"../".repeat(fromParts.length)}${toParts.join("/")}`;
}

async function discoverComponents(): Promise<ComponentSource[]> {
  const files = await walk(COMPONENT_ROOT);
  const metaFiles = files.filter((url) => url.pathname.endsWith(".meta.ts"))
    .sort((a, b) => a.pathname.localeCompare(b.pathname));
  return metaFiles.map((metaUrl) => {
    const examplesUrl = new URL(
      metaUrl.pathname.replace(/\.meta\.ts$/, ".examples.tsx"),
      metaUrl,
    );
    if (!files.some((file) => file.pathname === examplesUrl.pathname)) {
      throw new Error(`Missing examples for ${metaUrl.pathname}`);
    }
    return { metaUrl, examplesUrl };
  });
}

async function generateRegistry(
  sources: readonly ComponentSource[],
): Promise<void> {
  const imports: string[] = [];
  const entries: string[] = [];
  for (const [index, source] of sources.entries()) {
    imports.push(
      `import meta${index} from ${
        JSON.stringify(relativeImport(GENERATED_ROOT, source.metaUrl))
      };`,
      `import Examples${index} from ${
        JSON.stringify(relativeImport(GENERATED_ROOT, source.examplesUrl))
      };`,
    );
    entries.push(`  { meta: meta${index}, Examples: Examples${index} },`);
  }
  const registry =
    `/* Generated by scripts/build.ts. Do not edit. */\nimport type { ComponentType } from "react";\nimport type { ComponentMeta } from "../../src/types/component-meta.ts";\n${
      imports.join("\n")
    }\n\nexport interface RegistryEntry { readonly meta: ComponentMeta; readonly Examples: ComponentType; }\nexport const registry: readonly RegistryEntry[] = [\n${
      entries.join("\n")
    }\n];\n`;
  await Deno.mkdir(GENERATED_ROOT, { recursive: true });
  await Deno.writeTextFile(new URL("registry.ts", GENERATED_ROOT), registry);
}

async function componentCount(
  sources: readonly ComponentSource[],
): Promise<number> {
  const metadata: ComponentMeta[] = [];
  for (const source of sources) {
    const module = await import(source.metaUrl.href) as {
      default: ComponentMeta;
    };
    metadata.push(module.default);
  }
  return metadata.length;
}

async function bundleStyleguide(): Promise<void> {
  const command = new Deno.Command(Deno.execPath(), {
    cwd: decodeURIComponent(ROOT.pathname),
    args: [
      "bundle",
      "--platform=browser",
      "--format=esm",
      "--sourcemap=linked",
      "styleguide/app.tsx",
      "--output=dist/styleguide.js",
    ],
    stdout: "inherit",
    stderr: "inherit",
  });
  const result = await command.output();
  if (!result.success) {
    throw new Error(`Styleguide bundle failed with exit code ${result.code}`);
  }
}

/** Build the React catalogue and its explicit all-component runtime. */
export async function buildDesignSystem(): Promise<BuildSummary> {
  await writeGeneratedSources();
  const sources = await discoverComponents();
  await generateRegistry(sources);
  const { emitDesignSystemRuntime } = await import("../src/runtime.ts");
  const summary = await emitDesignSystemRuntime({
    outputRoot: DIST_ROOT,
    all: true,
    assets: ["fonts", "grain"],
  });
  if (summary.components !== await componentCount(sources)) {
    throw new Error("Catalogue and runtime component discovery disagree");
  }
  await bundleStyleguide();
  return summary;
}

if (import.meta.main) {
  const summary = await buildDesignSystem();
  console.log(
    `Built ${summary.components} components and ${summary.tokens} tokens.`,
  );
}
