import { allTokens, designTokens, themeTokens } from "../src/tokens/tokens.ts";
import type { ComponentMeta } from "../src/types/component-meta.ts";

const ROOT = new URL("../", import.meta.url);
const COMPONENT_ROOT = new URL("../src/components/", import.meta.url);
const GENERATED_ROOT = new URL("../styleguide/generated/", import.meta.url);
const DIST_ROOT = new URL("../dist/", import.meta.url);

interface ComponentSource {
  readonly metaUrl: URL;
  readonly examplesUrl: URL;
  readonly cssUrl: URL | null;
}

export interface BuildSummary {
  readonly components: number;
  readonly tokens: number;
}

async function walk(directory: URL): Promise<URL[]> {
  const files: URL[] = [];
  for await (const entry of Deno.readDir(directory)) {
    const url = new URL(entry.name + (entry.isDirectory ? "/" : ""), directory);
    if (entry.isDirectory) files.push(...await walk(url));
    else files.push(url);
  }
  return files;
}

function relativeImport(fromDirectory: URL, target: URL): string {
  const from = decodeURIComponent(fromDirectory.pathname);
  const to = decodeURIComponent(target.pathname);
  const fromParts = from.split("/").filter(Boolean);
  const toParts = to.split("/").filter(Boolean);
  while (fromParts[0] === toParts[0]) {
    fromParts.shift();
    toParts.shift();
  }
  return `${"../".repeat(fromParts.length)}${toParts.join("/")}`;
}

async function discoverComponents(): Promise<ComponentSource[]> {
  const files = await walk(COMPONENT_ROOT);
  const metaFiles = files.filter((url) => url.pathname.endsWith(".meta.ts"))
    .sort((a, b) => a.pathname.localeCompare(b.pathname));
  return metaFiles.map((metaUrl) => {
    const examplesUrl = new URL(
      metaUrl.pathname.replace(/\.meta\.ts$/, ".examples.tsx"),
      metaUrl,
    );
    const cssCandidate = new URL(
      metaUrl.pathname.replace(/\.meta\.ts$/, ".css"),
      metaUrl,
    );
    const hasExamples = files.some((file) =>
      file.pathname === examplesUrl.pathname
    );
    if (!hasExamples) {
      throw new Error(`Missing examples for ${metaUrl.pathname}`);
    }
    return {
      metaUrl,
      examplesUrl,
      cssUrl: files.some((file) => file.pathname === cssCandidate.pathname)
        ? cssCandidate
        : null,
    };
  });
}

function generateTokenCss(): string {
  const primitiveLines = designTokens.map(({ name, value }) =>
    `    ${name}: ${value};`
  ).join("\n");
  const lightLines = themeTokens.map(({ name, light }) =>
    `    ${name}: ${light};`
  ).join("\n");
  const darkLines = themeTokens.map(({ name, dark }) => `    ${name}: ${dark};`)
    .join("\n");
  return `/* Generated from src/tokens/tokens.ts. Do not edit. */\n@layer discern.tokens {\n  :root {\n${primitiveLines}\n${lightLines}\n  }\n\n  [data-ds-theme="dark"] {\n${darkLines}\n  }\n}\n`;
}

async function componentMetadata(
  sources: readonly ComponentSource[],
): Promise<ComponentMeta[]> {
  const metadata: ComponentMeta[] = [];
  for (const source of sources) {
    const module = await import(source.metaUrl.href) as {
      default: ComponentMeta;
    };
    metadata.push(module.default);
  }
  return metadata.sort((a, b) =>
    a.group.localeCompare(b.group) || a.order - b.order
  );
}

async function generateRegistry(
  sources: readonly ComponentSource[],
): Promise<void> {
  const imports: string[] = [];
  const entries: string[] = [];
  for (const [index, source] of sources.entries()) {
    const metaSpecifier = relativeImport(GENERATED_ROOT, source.metaUrl);
    const examplesSpecifier = relativeImport(
      GENERATED_ROOT,
      source.examplesUrl,
    );
    imports.push(`import meta${index} from "${metaSpecifier}";`);
    imports.push(`import Examples${index} from "${examplesSpecifier}";`);
    entries.push(`  { meta: meta${index}, Examples: Examples${index} },`);
  }
  const registry =
    `/* Generated by scripts/build.ts. Do not edit. */\nimport type { ComponentType } from "react";\nimport type { ComponentMeta } from "../../src/types/component-meta.ts";\n${
      imports.join("\n")
    }\n\nexport interface RegistryEntry { readonly meta: ComponentMeta; readonly Examples: ComponentType; }\nexport const registry: readonly RegistryEntry[] = [\n${
      entries.join("\n")
    }\n];\n`;
  await Deno.writeTextFile(new URL("registry.ts", GENERATED_ROOT), registry);
}

async function generateCss(
  sources: readonly ComponentSource[],
  outputRoot: URL,
): Promise<void> {
  const sourceStyles = [
    new URL("../src/styles/foundation.css", import.meta.url),
    new URL("../src/styles/utilities.css", import.meta.url),
    ...sources.flatMap((source) => source.cssUrl ? [source.cssUrl] : []),
  ];
  const sections = [generateTokenCss()];
  for (const url of sourceStyles) sections.push(await Deno.readTextFile(url));
  await Deno.writeTextFile(
    new URL("discern.css", outputRoot),
    sections.join("\n\n"),
  );
}

async function writeManifest(
  outputRoot: URL,
  components: readonly ComponentMeta[],
): Promise<void> {
  await Deno.writeTextFile(
    new URL("manifest.json", outputRoot),
    JSON.stringify({ version: 1, components, tokens: allTokens }, null, 2) +
      "\n",
  );
}

async function copyRuntimeAssets(outputRoot: URL): Promise<void> {
  const textureRoot = new URL("textures/", outputRoot);
  await Deno.mkdir(textureRoot, { recursive: true });
  await Deno.copyFile(
    new URL("../assets/textures/grain.png", import.meta.url),
    new URL("grain.png", textureRoot),
  );
}

async function bundleStyleguide(): Promise<void> {
  const command = new Deno.Command(Deno.execPath(), {
    cwd: decodeURIComponent(ROOT.pathname),
    args: [
      "bundle",
      "--platform=browser",
      "--format=esm",
      "--sourcemap=linked",
      "styleguide/app.tsx",
      "--output=dist/styleguide.js",
    ],
    stdout: "inherit",
    stderr: "inherit",
  });
  const result = await command.output();
  if (!result.success) {
    throw new Error(`Styleguide bundle failed with exit code ${result.code}`);
  }
}

/** Build the deterministic, framework-neutral runtime into a chosen directory. */
export async function buildDesignSystemRuntime(
  outputRoot: URL,
): Promise<BuildSummary> {
  await Deno.mkdir(outputRoot, { recursive: true });
  const sources = await discoverComponents();
  const components = await componentMetadata(sources);
  await generateCss(sources, outputRoot);
  await writeManifest(outputRoot, components);
  await copyRuntimeAssets(outputRoot);
  return { components: components.length, tokens: allTokens.length };
}

/** Build the local React catalogue as well as the framework-neutral runtime. */
export async function buildDesignSystem(): Promise<BuildSummary> {
  await Deno.mkdir(GENERATED_ROOT, { recursive: true });
  await Deno.mkdir(DIST_ROOT, { recursive: true });
  const sources = await discoverComponents();
  await generateRegistry(sources);
  const summary = await buildDesignSystemRuntime(DIST_ROOT);
  await bundleStyleguide();
  return summary;
}

if (import.meta.main) {
  const summary = await buildDesignSystem();
  console.log(
    `Built ${summary.components} components and ${summary.tokens} tokens.`,
  );
}
