/**
 * The guideline compiler (ADR 0020): assemble icculus's **bundled, feature-aware
 * built-in harness guidance** plus the project's **own config-pointed sources**
 * into the generated per-provider agent files (CLAUDE.md, AGENTS.md, GEMINI.md, …).
 *
 * The compiled body is, in order:
 *   1. icculus's built-in base guidance (always),
 *   2. a built-in section for each ENABLED feature (a disabled feature's guidance
 *      is omitted automatically — that is the mechanism behind feature toggles),
 *   3. the user's `[guidance].sources` (default `guidance.md`, globs allowed),
 *      appended so they extend the built-ins.
 *
 * It writes each provider file named in `[guidance].agents` (falling back to the
 * pre-migration `[project].agents`). Every output carries a generated banner —
 * `AGENTS.md` is the one tracked agent file (so guidance changes show in review);
 * every other mirror is gitignored. Nothing is hand-edited: edit your sources,
 * or icculus's built-ins, and recompile.
 *
 * Two independent jobs, each gated on its feature and safe to run from anywhere:
 *   - `features.skills`  → materialize skills into `.claude/skills/` (see lib/skills.ts);
 *   - `features.guidance`→ compile the agent files described above.
 * The skills job runs even when guidance is off, so skills stay discoverable.
 */

import { ensureDir } from "@std/fs";
import { dirname, join } from "@std/path";
import { Config } from "../shared/config_read.ts";
import { type Feature, isFeatureEnabled } from "../shared/features.ts";
import { resolveGuidanceSources, resolveTemplatesDir } from "../lib/paths.ts";
import { materializeSkills } from "../lib/skills.ts";
import { Logger } from "../lib/log.ts";

/** What a single `compileGuidelines` run accomplished. */
export interface GuidelinesResult {
  /** Output paths (relative to `root`) written, in agent-config order. */
  agentsWritten: string[];
  /** Bundled skills copied into `.claude/skills/`. */
  skillsCopied: number;
  /** Authored skills symlinked into `.claude/skills/`. */
  skillsLinked: number;
  /** Stale managed skill entries pruned from `.claude/skills/`. */
  skillsPruned: number;
}

/**
 * Map a `[guidance].agents` entry to the file path (relative to the project root)
 * `compileGuidelines` writes for it, and whether that file is tracked in git.
 * This is the one table to extend when teaching the harness a new provider. An
 * unknown agent yields `undefined` and is warned about and skipped, never guessed.
 *
 * Rule: `AGENTS.md` (codex) is the single tracked agent file; every other mirror
 * is gitignored (see the .gitignore fragment).
 */
const AGENT_OUTPUT: Readonly<
  Record<string, { path: string; tracked: boolean }>
> = {
  codex: { path: "AGENTS.md", tracked: true },
  claude_code: { path: "CLAUDE.md", tracked: false },
  gemini: { path: "GEMINI.md", tracked: false },
};

/** The output path for an agent name, or undefined when unmapped. */
function agentOutputPath(agent: string): string | undefined {
  return Object.hasOwn(AGENT_OUTPUT, agent)
    ? AGENT_OUTPUT[agent]!.path
    : undefined;
}

/** Default providers to emit when neither `[guidance].agents` nor the legacy
 * `[project].agents` is set. */
const DEFAULT_AGENTS: readonly string[] = ["claude_code", "codex"];

/**
 * The built-in guidance sections, in compile order. The base section is always
 * included; every other section is gated on its feature, so disabling a feature
 * drops its guidance from the compiled output automatically.
 */
const BUILTIN_SECTIONS: ReadonlyArray<{ file: string; feature?: Feature }> = [
  { file: "base.md" },
  { file: "worktrees.md", feature: "worktrees" },
  { file: "ratchets.md", feature: "ratchets" },
  { file: "skills.md", feature: "skills" },
  { file: "docs.md", feature: "docs" },
];

/** The generated-file banner prepended to every compiled provider file. */
function banner(): string {
  return [
    "<!-- GENERATED by `icculus guidelines` — do NOT edit this file.",
    "     It is compiled from icculus's built-in harness guidance plus your",
    "     [guidance].sources. Edit those (or icculus's built-ins) and recompile. -->",
    "",
    "",
  ].join("\n");
}

/** The providers to emit: `[guidance].agents`, else the legacy `[project].agents`,
 * else the default pair. */
function guidanceAgents(config: Config): string[] {
  const guidance = config.array("guidance.agents");
  if (guidance.length > 0) {
    return guidance;
  }
  const legacy = config.array("project.agents");
  return legacy.length > 0 ? legacy : [...DEFAULT_AGENTS];
}

/**
 * Read and concatenate icculus's built-in guidance sections for the enabled
 * features, in {@link BUILTIN_SECTIONS} order. A missing section file is skipped
 * defensively (the distribution ships them, but a custom templates tree might not).
 */
async function builtinGuidance(config: Config): Promise<string> {
  const dir = join(await resolveTemplatesDir(), "guidance");
  let out = "";
  for (const section of BUILTIN_SECTIONS) {
    if (section.feature && !isFeatureEnabled(config, section.feature)) {
      continue;
    }
    let text: string;
    try {
      text = await Deno.readTextFile(join(dir, section.file));
    } catch (err) {
      if (err instanceof Deno.errors.NotFound) {
        continue;
      }
      throw err;
    }
    out += text;
    if (!out.endsWith("\n")) {
      out += "\n";
    }
    out += "\n";
  }
  return out;
}

/**
 * Compile the agent files from the built-in guidance + the project's sources, and
 * materialize skills. Each job is gated on its feature. Resolves to a summary of
 * what changed. The worktree lifecycle and `upgrade` call this with the discovered
 * project `root`; the name and signature are a cross-module contract.
 */
export async function compileGuidelines(
  root: string,
  logger?: Logger,
): Promise<GuidelinesResult> {
  // info/ok → stdout (matching the shell `output.sh`), UNLESS the caller passes
  // its own logger to control the stream — e.g. `upgrade --json` passes its
  // json-mode logger so this narration is suppressed and the JSON object stays
  // the only thing on stdout.
  const log = logger ??
    new Logger({ json: false, noColor: false, humanStream: "stdout" });

  const config = await Config.load(root);

  // --- job 1: materialize skills into .claude/skills/ (gated) ----------------
  let skills = { copied: 0, linked: 0, pruned: 0 };
  if (isFeatureEnabled(config, "skills")) {
    skills = await materializeSkills(root, config, log);
  }

  // --- job 2: compile the agent files (gated) --------------------------------
  const agentsWritten: string[] = [];
  if (!isFeatureEnabled(config, "guidance")) {
    log.info("guidance feature is off — no agent files compiled.");
    return summarize(agentsWritten, skills);
  }

  let body = await builtinGuidance(config);
  const sources = await resolveGuidanceSources(root, config);
  for (const src of sources) {
    body += await Deno.readTextFile(src);
    body += "\n";
  }
  const compiled = banner() + body;

  for (const agent of guidanceAgents(config)) {
    const rel = agentOutputPath(agent);
    if (rel === undefined) {
      log.warn(
        `guidelines: unknown agent '${agent}' in [guidance].agents — skipping (no output mapping).`,
      );
      continue;
    }
    const out = join(root, rel);
    await ensureDir(dirname(out));
    await Deno.writeTextFile(out, compiled);
    // A generated file should be readable like any other source (mode 0644).
    await Deno.chmod(out, 0o644);
    agentsWritten.push(rel);
  }

  if (agentsWritten.length === 0) {
    log.warn(
      'guidelines: no known providers in [guidance].agents — compiled nothing. Set agents = ["claude_code", …].',
    );
  } else {
    log.ok(
      `guidelines: compiled ${sources.length} source(s) + built-in guidance into ${agentsWritten.length} agent file(s): ${
        agentsWritten.join(",")
      }`,
    );
  }
  return summarize(agentsWritten, skills);
}

/** Build the result. The skills narration is emitted once by `materializeSkills`,
 * so this does not repeat it. */
function summarize(
  agentsWritten: string[],
  skills: { copied: number; linked: number; pruned: number },
): GuidelinesResult {
  return {
    agentsWritten,
    skillsCopied: skills.copied,
    skillsLinked: skills.linked,
    skillsPruned: skills.pruned,
  };
}
