/**
 * The CLI command model and the generated CLI reference — both read off the LIVE
 * command registry (`buildCli`'s Cliffy tree), never a hand-copied list, so the
 * documented surface and the real one are a single source (the same discipline as
 * `config_codegen.ts`, ADR 0026).
 *
 * Two consumers:
 *  - `scripts/codegen.ts` renders {@link renderCliReferenceDoc} into the map's
 *    committed CLI reference; a sync test asserts the committed file equals the
 *    generator output, so a verb or flag change that isn't regenerated fails the
 *    gate.
 *  - the docs-integrity guard validates every fenced `discern …` example in the
 *    map against {@link cliCommandModel}, so an example quoting a renamed verb or
 *    a removed flag fails the docs, not the user.
 *
 * The walker reads Cliffy's public introspection surface through a narrow
 * structural view ({@link CommandView}) — the generic `Command` type is
 * impractical to thread here, and the view names exactly the methods used.
 * These functions stay OUT of the engine's hot path — they are dev/codegen tools.
 */

import { COMMAND_GROUPS } from "../cli_help.ts";

/** One positional argument a command declares. */
export interface CliArg {
  name: string;
  optional: boolean;
  variadic: boolean;
}

/** One flag a command accepts, as declared (every spelling in `flags`). */
export interface CliOption {
  /** All spellings, e.g. `["-y", "--yes"]`. */
  flags: string[];
  description: string;
  /** Cliffy's value spec (`"<name:string>"`), `""` for a boolean flag. */
  typeDefinition: string;
  hidden: boolean;
  /** True for a root `globalOption` inherited by every command. */
  global: boolean;
}

/** One command in the live tree, with its full subcommand subtree. */
export interface CliCommand {
  /** Command words below `discern`, e.g. `["worktree", "create"]`. */
  path: string[];
  description: string;
  aliases: string[];
  hidden: boolean;
  args: CliArg[];
  /** Own + inherited-global options, exactly as Cliffy resolves them. */
  options: CliOption[];
  children: CliCommand[];
}

/** Flags Cliffy accepts on every command without declaring them as options. */
export const IMPLICIT_COMMAND_FLAGS: readonly string[] = ["-h", "--help"];

/** Flags Cliffy accepts on the root command only (from `.version()`). */
export const IMPLICIT_ROOT_FLAGS: readonly string[] = ["-V", "--version"];

/** The narrow structural view of a Cliffy command this module reads. */
interface CommandView {
  getName(): string;
  getDescription(): string;
  getAliases(): string[];
  getArguments(): ReadonlyArray<{
    name: string;
    optional: boolean;
    variadic: boolean;
  }>;
  getOptions(hidden?: boolean): ReadonlyArray<{
    name: string;
    flags: string[];
    description: string;
    typeDefinition?: string;
    hidden?: boolean;
    global?: boolean;
  }>;
  getCommands(hidden?: boolean): CommandView[];
}

/** Walk one command into the plain model, `path` naming its position. */
function walkCommand(
  cmd: CommandView,
  path: string[],
  hidden: boolean,
): CliCommand {
  const visibleChildren = new Set(
    cmd.getCommands(false).map((c) => c.getName()),
  );
  return {
    path,
    description: cmd.getDescription(),
    aliases: cmd.getAliases(),
    hidden,
    args: cmd.getArguments().map((a) => ({
      name: a.name,
      optional: a.optional,
      variadic: a.variadic,
    })),
    options: cmd.getOptions(true).map((o) => ({
      flags: [...o.flags],
      description: o.description,
      typeDefinition: o.typeDefinition ?? "",
      hidden: o.hidden === true,
      global: o.global === true,
    })),
    children: cmd.getCommands(true).map((c) =>
      walkCommand(
        c,
        [...path, c.getName()],
        hidden || !visibleChildren.has(c.getName()),
      )
    ),
  };
}

/**
 * The live command tree as plain data. Pass the fully-built root (`buildCli`) —
 * taking it as a parameter keeps this module free of the CLI's own wiring, and
 * makes the model trivially testable against a synthetic tree. The root node's
 * `path` is `[]`; its `options` are the global flags.
 */
export function cliCommandModel(root: unknown): CliCommand {
  return walkCommand(root as CommandView, [], false);
}

/** Depth-first walk over `node` and every descendant. */
export function* walkCliCommands(node: CliCommand): Generator<CliCommand> {
  yield node;
  for (const child of node.children) {
    yield* walkCliCommands(child);
  }
}

// ── the generated CLI reference ────────────────────────────────────────────────

/** The banner stamped atop the generated reference page. */
const DOCS_BANNER =
  "<!-- GENERATED by `deno task codegen` from the live command registry (src/main.ts) — do NOT edit by hand. Change a command's declaration and regenerate. -->";

/** Escape a cell value for a Markdown table (pipes would split the row). */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

/** One argument rendered for a usage line: `<name>`, `[name]`, `[name...]`. */
function argLabel(arg: CliArg): string {
  const dots = arg.variadic ? "..." : "";
  return arg.optional ? `[${arg.name}${dots}]` : `<${arg.name}${dots}>`;
}

/**
 * A help-only command GROUP: subcommands, no positionals, and nothing of its
 * own to invoke. The prelaunch vocabulary retired presenting a bare group as a
 * command — docs teach `discern worktree <subcommand>`, never `discern
 * worktree` — so the reference renders groups in that canonical shape.
 */
export function isHelpOnlyGroup(node: CliCommand): boolean {
  return node.children.length > 0 && node.args.length === 0 &&
    node.options.every((o) => o.hidden || o.global);
}

/** The backticked label a command's heading and usage carry: the full path,
 * with `<subcommand>` appended for a help-only group. */
export function commandHeadingLabel(node: CliCommand): string {
  const words = ["discern", ...node.path];
  if (isHelpOnlyGroup(node)) words.push("<subcommand>");
  return words.join(" ");
}

/** A flag's value spec with Cliffy's `:type` annotations dropped:
 * `<name:string>` → `<name>`. */
function valueSpec(typeDefinition: string): string {
  return typeDefinition.replace(/:[a-zA-Z]+([>\]])/g, "$1");
}

/** The full usage line for one command, e.g. `discern map [target] [options]`. */
function usageLine(node: CliCommand): string {
  if (isHelpOnlyGroup(node)) return commandHeadingLabel(node);
  const words = ["discern", ...node.path, ...node.args.map(argLabel)];
  if (node.options.some((o) => !o.hidden)) {
    words.push("[options]");
  }
  return words.join(" ");
}

/** The `| Option | Description |` table for a command's own visible flags.
 * Inherited globals are excluded — they render once, in their own section. */
function optionsTable(node: CliCommand): string {
  const rows = node.options
    .filter((o) => !o.hidden && !o.global)
    .map((o) => {
      const spec = valueSpec(o.typeDefinition);
      const label = o.flags.join(", ") + (spec === "" ? "" : ` ${spec}`);
      return `| \`${cell(label)}\` | ${cell(o.description)} |`;
    });
  if (rows.length === 0) return "";
  return ["| Option | Description |", "| --- | --- |", ...rows].join("\n");
}

/** The heading + body for one command (and, recursively, its visible
 * subcommands one heading level down). */
function commandSection(node: CliCommand, depth: number): string {
  const heading = "#".repeat(depth);
  const parts: string[] = [
    `${heading} \`${commandHeadingLabel(node)}\``,
    "",
    node.description,
    "",
    `Usage: \`${usageLine(node)}\``,
  ];
  const table = optionsTable(node);
  if (table !== "") {
    parts.push("", table);
  }
  for (const child of node.children) {
    if (child.hidden) continue;
    parts.push("", commandSection(child, Math.min(depth + 1, 6)));
  }
  return parts.join("\n");
}

/**
 * Render the map's CLI reference page from the live command tree. Every visible
 * command appears under its `COMMAND_GROUPS` group (the same grouping — and the
 * same guarded SSOT — as `discern --help`), with its flags and subcommands read
 * straight off the registry. Search aliases are derived from the same tree,
 * so every visible command path is searchable without a second list to maintain.
 */
export function renderCliReferenceDoc(root: unknown): string {
  const model = cliCommandModel(root);
  const byName = new Map(model.children.map((c) => [c.path[0] ?? "", c]));
  const aliases = [...walkCliCommands(model)]
    .filter((command) => command.path.length > 0 && !command.hidden)
    .map((command) => `discern ${command.path.join(" ")}`);

  const groups = COMMAND_GROUPS.map((group) => {
    const members = group.commands
      .map((name) => byName.get(name))
      .filter((c): c is CliCommand => c !== undefined && !c.hidden);
    if (members.length === 0) return "";
    return [
      `## ${group.name}`,
      "",
      `${group.note.charAt(0).toUpperCase()}${group.note.slice(1)}.`,
      "",
      members.map((m) => commandSection(m, 3)).join("\n\n"),
    ].join("\n");
  }).filter((s) => s !== "");

  const globalRows = model.options
    .filter((o) => !o.hidden)
    .map((o) => {
      const spec = valueSpec(o.typeDefinition);
      const label = o.flags.join(", ") + (spec === "" ? "" : ` ${spec}`);
      return `| \`${cell(label)}\` | ${cell(o.description)} |`;
    });

  return [
    "---",
    "title: CLI reference",
    "description: Every discern command and flag, generated from the live command registry.",
    "order: 10",
    "publish: true",
    "aliases:",
    ...aliases.map((alias) => `  - ${alias}`),
    "---",
    "",
    DOCS_BANNER,
    "",
    "# CLI reference",
    "",
    "Use this page to look up the exact syntax and flags for every visible `discern` command. The entries are generated from the command registry the binary dispatches on. `discern <command> --help` prints the same declarations in the terminal.",
    "",
    "## Global options",
    "",
    "Accepted by every command.",
    "",
    "| Option | Description |",
    "| --- | --- |",
    ...globalRows,
    "",
    groups.join("\n\n"),
    "",
  ].join("\n");
}
