/**
 * The CLI command model and the generated CLI reference — both read off the LIVE
 * command registry (`buildCli`'s Cliffy tree), never a hand-copied list, so the
 * documented surface and the real one are a single source (the same discipline as
 * `config_codegen.ts`, ADR 0026).
 *
 * Two consumers:
 *  - `scripts/codegen.ts` renders {@link renderCliReferenceDoc} into the map's
 *    committed CLI reference; a sync test asserts the committed file equals the
 *    generator output, so a verb or flag change that isn't regenerated fails the
 *    gate.
 *  - the docs-integrity guard validates every fenced `discern …` example in the
 *    map against {@link cliCommandModel}, so an example quoting a renamed verb or
 *    a removed flag fails the docs, not the user.
 *
 * The walker reads Cliffy's public introspection surface through a narrow
 * structural view ({@link CommandView}) — the generic `Command` type is
 * impractical to thread here, and the view names exactly the methods used.
 * These functions stay OUT of the engine's hot path — they are dev/codegen tools.
 */

import { COMMAND_GROUPS } from "../cli_help.ts";

/** One positional argument a command declares. */
export interface CliArg {
  name: string;
  optional: boolean;
  variadic: boolean;
}

/** One flag a command accepts, as declared (every spelling in `flags`). */
export interface CliOption {
  /** All spellings, e.g. `["-y", "--yes"]`. */
  flags: string[];
  description: string;
  /** Cliffy's value spec (`"<name:string>"`), `""` for a boolean flag. */
  typeDefinition: string;
  hidden: boolean;
  /** True for a root `globalOption` inherited by every command. */
  global: boolean;
}

/** One command in the live tree, with its full subcommand subtree. */
export interface CliCommand {
  /** Command words below `discern`, e.g. `["worktree", "create"]`. */
  path: string[];
  description: string;
  aliases: string[];
  hidden: boolean;
  args: CliArg[];
  /** An explicit Cliffy usage suffix, or an empty string for derived usage. */
  usage: string;
  /** Own + inherited-global options, exactly as Cliffy resolves them. */
  options: CliOption[];
  children: CliCommand[];
}

/** Entry-point-owned projection of the fully attached live command tree. */
export type CliModelProvider = () => CliCommand;

/** Flags Cliffy accepts on every command without declaring them as options. */
export const IMPLICIT_COMMAND_FLAGS: readonly string[] = ["-h", "--help"];

/** Flags Cliffy accepts on the root command only (from `.version()`). */
export const IMPLICIT_ROOT_FLAGS: readonly string[] = ["-V", "--version"];

/** The narrow structural view of a Cliffy command this module reads. */
interface CommandView {
  getName(): string;
  getDescription(): string;
  getAliases(): string[];
  getUsage(): string;
  getArguments(): ReadonlyArray<{
    name: string;
    optional: boolean;
    variadic: boolean;
  }>;
  getOptions(hidden?: boolean): ReadonlyArray<{
    name: string;
    flags: string[];
    description: string;
    typeDefinition?: string;
    hidden?: boolean;
    global?: boolean;
  }>;
  getCommands(hidden?: boolean): CommandView[];
}

/** Walk one command into the plain model, `path` naming its position. */
function walkCommand(
  cmd: CommandView,
  path: string[],
  hidden: boolean,
): CliCommand {
  const args = cmd.getArguments();
  const visibleChildren = new Set(
    cmd.getCommands(false).map((c) => c.getName()),
  );
  return {
    path,
    description: cmd.getDescription(),
    aliases: cmd.getAliases(),
    hidden,
    usage: args.length === 0 ? cmd.getUsage() : "",
    args: args.map((a) => ({
      name: a.name,
      optional: a.optional,
      variadic: a.variadic,
    })),
    options: cmd.getOptions(true).map((o) => ({
      flags: [...o.flags],
      description: o.description,
      typeDefinition: o.typeDefinition ?? "",
      hidden: o.hidden === true,
      global: o.global === true,
    })),
    children: cmd.getCommands(true).map((c) =>
      walkCommand(
        c,
        [...path, c.getName()],
        hidden || !visibleChildren.has(c.getName()),
      )
    ),
  };
}

/**
 * The live command tree as plain data. Pass the fully-built root (`buildCli`) —
 * taking it as a parameter keeps this module free of the CLI's own wiring, and
 * makes the model trivially testable against a synthetic tree. The root node's
 * `path` is `[]`; its `options` are the global flags.
 */
export function cliCommandModel(root: unknown): CliCommand {
  return walkCommand(root as CommandView, [], false);
}

/** Depth-first walk over `node` and every descendant. */
export function* walkCliCommands(node: CliCommand): Generator<CliCommand> {
  yield node;
  for (const child of node.children) {
    yield* walkCliCommands(child);
  }
}

// ── the generated CLI reference ────────────────────────────────────────────────

/** The banner stamped atop the generated reference page. */
const DOCS_BANNER =
  "<!-- GENERATED by `deno task codegen` from the live command registry (src/main.ts) — do NOT edit by hand. Change a command's declaration and regenerate. -->";

/** Escape a cell value for a Markdown table (pipes would split the row). */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

/** One argument rendered for a usage line: `<name>`, `[name]`, `[name...]`. */
function argLabel(arg: CliArg): string {
  const dots = arg.variadic ? "..." : "";
  return arg.optional ? `[${arg.name}${dots}]` : `<${arg.name}${dots}>`;
}

/**
 * A help-only command GROUP: subcommands, no positionals, and nothing of its
 * own to invoke. The prelaunch vocabulary retired presenting a bare group as a
 * command — docs teach `discern worktree <subcommand>`, never `discern
 * worktree` — so the reference renders groups in that canonical shape.
 */
export function isHelpOnlyGroup(node: CliCommand): boolean {
  return node.children.length > 0 && node.args.length === 0 &&
    node.options.every((o) => o.hidden || o.global);
}

/** The backticked label a command's heading and usage carry: the full path,
 * with `<subcommand>` appended for a help-only group. */
export function commandHeadingLabel(node: CliCommand): string {
  const words = ["discern", ...node.path];
  if (isHelpOnlyGroup(node)) words.push("<subcommand>");
  return words.join(" ");
}

/** A flag's value spec with Cliffy's `:type` annotations dropped:
 * `<name:string>` → `<name>`. */
function valueSpec(typeDefinition: string): string {
  return typeDefinition.replace(/:[a-zA-Z]+([>\]])/g, "$1");
}

/** The full usage line for one command, e.g. `discern map [target] [options]`. */
function usageLine(node: CliCommand): string {
  if (isHelpOnlyGroup(node)) return commandHeadingLabel(node);
  if (node.usage !== "") {
    return ["discern", ...node.path, node.usage].join(" ");
  }
  const words = ["discern", ...node.path, ...node.args.map(argLabel)];
  if (node.options.some((o) => !o.hidden)) {
    words.push("[options]");
  }
  return words.join(" ");
}

/** The `| Option | Description |` table for a command's own visible flags.
 * Inherited globals are excluded — they render once, in their own section. */
function optionsTable(node: CliCommand): string {
  const rows = node.options
    .filter((o) => !o.hidden && !o.global)
    .map((o) => {
      const spec = valueSpec(o.typeDefinition);
      const label = o.flags.join(", ") + (spec === "" ? "" : ` ${spec}`);
      return `| \`${cell(label)}\` | ${cell(o.description)} |`;
    });
  if (rows.length === 0) return "";
  return ["| Option | Description |", "| --- | --- |", ...rows].join("\n");
}

/** The heading + body for one command (and, recursively, its visible
 * subcommands one heading level down). */
function commandSection(
  node: CliCommand,
  depth: number,
  includeAliases = false,
): string {
  const heading = "#".repeat(depth);
  const parts: string[] = [
    `${heading} \`${commandHeadingLabel(node)}\``,
    "",
    node.description,
    "",
    `Usage: \`${usageLine(node)}\``,
  ];
  if (includeAliases && node.aliases.length > 0) {
    const parent = node.path.slice(0, -1);
    const aliases = node.aliases.map((alias) =>
      `\`discern ${[...parent, alias].join(" ")}\``
    );
    parts.push("", `Aliases: ${aliases.join(", ")}.`);
  }
  const table = optionsTable(node);
  if (table !== "") {
    parts.push("", table);
  }
  for (const child of node.children) {
    if (child.hidden) continue;
    parts.push(
      "",
      commandSection(child, Math.min(depth + 1, 6), includeAliases),
    );
  }
  return parts.join("\n");
}

/**
 * Render the map's CLI reference page from the live command tree. Every visible
 * command appears under its `COMMAND_GROUPS` group (the same grouping — and the
 * same guarded SSOT — as `discern --help`), with its flags and subcommands read
 * straight off the registry. Search aliases are derived from the same tree,
 * so every visible command path is searchable without a second list to maintain.
 */
export function renderCliReferenceModel(
  model: CliCommand,
  manual: boolean,
): string {
  const byName = new Map(model.children.map((c) => [c.path[0] ?? "", c]));
  const commands = [...walkCliCommands(model)]
    .filter((command) => command.path.length > 0 && !command.hidden);
  const aliases = commands.flatMap((command) => {
    const canonical = `discern ${command.path.join(" ")}`;
    if (!manual) return [canonical];
    const parent = command.path.slice(0, -1);
    return [
      canonical,
      ...command.aliases.map((alias) =>
        `discern ${[...parent, alias].join(" ")}`
      ),
    ];
  });
  const manualAliases = manual
    ? [
      "interactive documentation reader",
      "terminal reader controls",
      "Tab picker",
      "Press Enter to continue",
      "$PAGER",
    ]
    : [];

  const groups = COMMAND_GROUPS.map((group) => {
    const members = group.commands
      .map((name) => byName.get(name))
      .filter((c): c is CliCommand => c !== undefined && !c.hidden);
    if (members.length === 0) return "";
    return [
      `## ${group.name}`,
      "",
      `${group.note.charAt(0).toUpperCase()}${group.note.slice(1)}.`,
      "",
      members.map((m) => commandSection(m, 3, manual)).join("\n\n"),
    ].join("\n");
  }).filter((s) => s !== "");

  const globalRows = model.options
    .filter((o) => !o.hidden)
    .map((o) => {
      const spec = valueSpec(o.typeDefinition);
      const label = o.flags.join(", ") + (spec === "" ? "" : ` ${spec}`);
      return `| \`${cell(label)}\` | ${cell(o.description)} |`;
    });

  const manualContract = manual
    ? [
      "## Help, version, and parser-owned flags",
      "",
      "No project setup is required to read help or the version. Cliffy, the live command parser, owns command usage, argument validation, aliases, and option help. `discern <command> --help` and `discern help <command>` read the same attached command tree as this page.",
      "",
      "| Spelling | Scope | Meaning |",
      "| --- | --- | --- |",
      `| \`${
        IMPLICIT_COMMAND_FLAGS.join("\`, \`")
      }\` | Every command | Show command help and exit without running the command. |`,
      `| \`${
        IMPLICIT_ROOT_FLAGS.join("\`, \`")
      }\` | Root only | Show the installed discern version and exit. |`,
      "",
      "`--md` is not supported. Use `--markdown`. Options after an exec-style boundary, including `discern queue --` and a Project Script name, belong to the child command rather than discern.",
      "",
      "## Interactive documentation reader",
      "",
      "Bare `discern docs` on an interactive terminal opens the grouped documentation reader. The picker searches document titles and paths. `discern map` uses the same reader for the configured project Map.",
      "",
      "| Context | Input | Contract |",
      "| --- | --- | --- |",
      "| Picker | Type text | Filter the grouped document titles and paths. |",
      "| Picker | `Up`, `Down`, `Ctrl-P`, `Ctrl-N` | Move one selectable entry. With no document open, `Tab` and `Shift-Tab` also move one entry. |",
      "| Picker | `Page Up`, `Page Down` | Move by one visible picker page. |",
      "| Picker | `Home`, `End` | Move to the first or last selectable entry. |",
      "| Picker | `Enter` | Open the selected document or run the selected action. |",
      "| Picker | `Escape`, `Ctrl-C`, end of input | Leave the reader without changing project state. |",
      "| Open document | `Tab`, `Shift-Tab` | Move focus between the picker and document panes. |",
      "| Open document | `Up`, `Down`, `Ctrl-P`, `Ctrl-N` | Scroll the document by one rendered row. |",
      "| Open document | `Page Up`, `Page Down` | Scroll by one visible document page. |",
      "| Open document | `Home`, `End` | Jump to the start or end of the document. |",
      "| Open document | `[`, `]` | Focus the previous or next addressable link. |",
      "| Focused link | `Enter` | Follow the link. `Escape` clears link focus and returns to scrolling. |",
      "| Open document | `Escape`, `q` | Close the document and retain the picker query and selection. |",
      "",
      "Admitted relative-document links and heading fragments stay inside the reader. Absolute `http://` and `https://` destinations open in the system browser only after discern restores the terminal. Other external schemes are not supported.",
      "",
      "With mouse tracking available, the wheel moves three picker entries or three document rows under the pointer. A left click focuses a pane and selects a picker entry; clicking a link follows it. Other mouse buttons and releases have no product action. Use the terminal application's own selection modifier to select terminal text while tracking is active; discern does not define that modifier.",
      "",
      "The rich reader requires ANSI terminal control and at least 32 columns. With the default three chrome rows, the picker-only layout needs 10 total rows, document-only needs 11, and the split layout begins at 18. Between those bounds, the focused pane occupies all usable rows.",
      "",
      "If the rich reader cannot start because ANSI control is unavailable or the terminal is too small, discern uses the sequential picker. An internally rendered document then waits at the exact prompt `Press Enter to continue.` and the next picker restores the remembered document selection. `--pager` selects this sequential flow and hands each document to `$PAGER`, or `less -R` when `$PAGER` is unset, when the pager succeeds.",
      "",
      "A direct `discern docs <target>` renders and exits without waiting. Bare `discern docs` off a terminal prints the table of contents and never requests input. `--list`, `--json`, and `--raw` never enter the reader; `--search` prints matches. Export writes or returns one Markdown stream, except `--export select` can request a selection on an interactive terminal.",
      "",
      "The implementation and real-terminal contract are public in [`src/commands/docs.ts`](https://github.com/jackwh/discern/blob/main/src/commands/docs.ts) and [`tests/docs_test.ts`](https://github.com/jackwh/discern/blob/main/tests/docs_test.ts).",
      "",
      "## Exit behavior",
      "",
      "| Exit status | Contract |",
      "| --- | --- |",
      "| `0` | The command completed successfully. A bare predicate exits `0` when true. |",
      "| `1` | A controlled failure or refusal, a false bare predicate, or an unmet enforcement threshold. |",
      "| `124` | `discern await` reached its call budget before the watched condition held. Its result includes the `resume` handle. |",
      "| `70` | discern crashed on an unexpected internal error. |",
      "| Child status | `discern queue -- <command>` and `discern scripts <name>` preserve the child command's exit status. |",
      "| Signal status | An interrupted run preserves the conventional signal status, such as `130` for SIGINT or `143` for SIGTERM. |",
      "",
      "Quiet JSON and Markdown results evaluate their completion policy before choosing the controlled exit status. Predicate result modes exit `0` and place the boolean in `data`; bare predicates use `0` or `1`.",
      "",
    ]
    : [];

  return [
    "---",
    "title: CLI reference",
    manual
      ? "description: Every public discern command, subcommand, argument, flag, alias, help boundary, exit contract, and terminal documentation-reader behavior."
      : "description: Every discern command and flag, generated from the live command registry.",
    "order: 10",
    "publish: true",
    "aliases:",
    ...[...aliases, ...manualAliases].map((alias) => `  - ${alias}`),
    "---",
    "",
    DOCS_BANNER,
    "",
    "# CLI reference",
    "",
    manual
      ? "Look up the exact syntax, arguments, flags, aliases, help ownership, exit behavior, and terminal documentation-reader contract for public `discern` commands. Command entries are generated from the command tree the installed binary dispatches; the reader contract is checked against the real-terminal implementation."
      : "Use this page to look up the exact syntax and flags for every visible `discern` command. The entries are generated from the command registry the binary dispatches on. `discern <command> --help` prints the same declarations in the terminal.",
    ...(manual
      ? [
        "",
        "Prerequisite: none for syntax lookup. Commands that require a configured project return `not_set_up` until setup is complete.",
      ]
      : []),
    "",
    "## Global options",
    "",
    "These options are inherited unless a command's entry says otherwise. Tokens beyond an exec-style child boundary are never discern options.",
    "",
    "| Option | Description |",
    "| --- | --- |",
    ...globalRows,
    "",
    ...manualContract,
    groups.join("\n\n"),
    ...(manual
      ? [
        "",
        "For result-envelope fields and Model Context Protocol delivery, see [MCP and results](mcp-and-results.md). For symptom-led recovery, see [Troubleshooting](../40-troubleshooting/README.md).",
      ]
      : []),
    "",
  ].join("\n");
}

/** Render the Map projection without changing its established bytes. */
export function renderCliReferenceDoc(root: unknown): string {
  return renderCliReferenceModel(cliCommandModel(root), false);
}

/** Render the complete public-manual projection from the same live tree. */
export function renderManualCliReferenceDoc(root: unknown): string {
  return renderCliReferenceModel(cliCommandModel(root), true);
}
