/**
 * Generators that derive the shipped, committed artifacts from the canonical Zod
 * schema (ADR 0026) — the editor JSON Schema and the docs config-reference both
 * render from one source and can never drift from what the engine enforces. (The
 * `discern.toml` template stays hand-authored to preserve its curated, legible
 * comments — ADR 0005 — and is bound to the schema by drift-guard tests instead,
 * not regenerated here.)
 *
 * Run by `deno task codegen`; a sync test asserts each committed artifact equals
 * its generator output, so a schema change that isn't regenerated fails the gate.
 * These functions stay OUT of the engine's hot path — they are dev/codegen tools.
 */

import { z } from "@zod/zod";
import { configDocSchema, configSchema } from "./config_schema.ts";

/** Published `$id` for the editor JSON Schema (matches the repo's raw URL). */
const SCHEMA_ID =
  "https://raw.githubusercontent.com/jackwh/discern/main/schema/discern-config.schema.json";

/** Human title for the editor JSON Schema. */
const SCHEMA_TITLE = "discern config document";

/** A non-null, non-array object. */
function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/**
 * Build the editor JSON Schema for the config *document* from {@link
 * configDocSchema}. Uses the `input` view (defaults/optionals are NOT required,
 * matching what a human writes) and prepends the published `$id` + `title` that
 * Zod doesn't emit. Because it is generated, the historical staleness bugs — the
 * `.discern/config.toml` path text and the gemini-less `agents` enum — cannot
 * recur: both now follow from the schema.
 */
export function buildConfigDocJsonSchema(): Record<string, unknown> {
  const generated = z.toJSONSchema(configDocSchema, { io: "input" }) as Record<
    string,
    unknown
  >;
  // Order: $schema, $id, title, then the schema body Zod produced (description,
  // type, properties, additionalProperties…).
  const { $schema, ...body } = generated;
  return {
    $schema: $schema ?? "https://json-schema.org/draft/2020-12/schema",
    $id: SCHEMA_ID,
    title: SCHEMA_TITLE,
    ...body,
  };
}

/** The editor JSON Schema rendered as the committed file's exact text (2-space
 * indent, trailing newline — matching `deno fmt`'s JSON style, so the file is
 * stable under the gate's fix stage). */
export function renderConfigDocSchemaJson(): string {
  return `${JSON.stringify(buildConfigDocJsonSchema(), null, 2)}\n`;
}

// Re-export the object guard for tests that introspect the generated shape.
export { isObject as isJsonObject };

// ── docs config-reference (generated from the LIVE config schema) ──────────────

/** The banner stamped atop the generated docs page (and the template). */
const DOCS_BANNER =
  "<!-- GENERATED by `deno task codegen` from src/shared/config_schema.ts — do NOT edit by hand. Edit the schema and regenerate. -->";

/** Escape a cell value for a Markdown table (pipes would split the row). */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

/** A human type label for a JSON-schema node: `string`, `boolean`, `number`,
 * `string[]`, a `\|`-joined enum, or a `\|`-joined union (command-or-list). */
function typeLabel(schema: Record<string, unknown>): string {
  if (Array.isArray(schema.enum)) {
    return schema.enum.map((v) => `\`${String(v)}\``).join(" \\| ");
  }
  if (Array.isArray(schema.anyOf)) {
    return schema.anyOf.filter(isObject).map(typeLabel).join(" \\| ");
  }
  const t = schema.type;
  if (t === "array") {
    const items = isObject(schema.items) ? typeLabel(schema.items) : "any";
    return `${items}[]`;
  }
  if (t === "integer") return "number";
  return typeof t === "string" ? t : "object";
}

/** The default-value label for a key: a code-fenced literal, or `—` when none. */
function defaultLabel(schema: Record<string, unknown>): string {
  return Object.hasOwn(schema, "default")
    ? `\`${JSON.stringify(schema.default)}\``
    : "—";
}

/** True for a nested container key (a sub-table or a `<name>` record), as opposed
 * to a scalar/array/enum leaf key. */
function isContainer(schema: Record<string, unknown>): boolean {
  return schema.type === "object" &&
    (isObject(schema.properties) || isObject(schema.additionalProperties));
}

/** A `| key | type | default | description |` table for the leaf keys of an object. */
function keyTable(properties: Record<string, unknown>): string {
  const rows = Object.entries(properties)
    .filter(([, v]) => isObject(v) && !isContainer(v))
    .map(([name, v]) => {
      const s = v as Record<string, unknown>;
      const desc = typeof s.description === "string" ? cell(s.description) : "";
      return `| \`${name}\` | ${typeLabel(s)} | ${defaultLabel(s)} | ${desc} |`;
    });
  if (rows.length === 0) return "";
  return [
    "| Key | Type | Default | Description |",
    "| --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

/** Render one section (and any nested sub-sections) as Markdown. `path` is the
 * dotted, bracket-free section path (e.g. `worktree.setup`); `level` the heading
 * depth. A record section's header gains a `.<name>` to signal it is repeatable. */
function renderSection(
  path: string,
  schema: Record<string, unknown>,
  level: number,
): string {
  const props = isObject(schema.properties) ? schema.properties : undefined;
  const valueShape = isObject(schema.additionalProperties)
    ? schema.additionalProperties
    : undefined;
  const isRecord = props === undefined && valueShape !== undefined;

  const header = isRecord ? `[${path}.<name>]` : `[${path}]`;
  const out: string[] = [`${"#".repeat(level)} \`${header}\``];
  if (typeof schema.description === "string") {
    out.push("", schema.description);
  }

  if (isRecord) {
    // A repeatable named table: document its value shape's leaf keys.
    const inner = isObject(valueShape.properties) ? valueShape.properties : {};
    const table = keyTable(inner);
    if (table !== "") out.push("", table);
  } else if (props !== undefined) {
    // An object section: a table of its leaf keys, then a sub-section per nested
    // container (a `[worktree.setup]` object, a `[worktree.resources.<name>]` record).
    const table = keyTable(props);
    if (table !== "") out.push("", table);
    for (const [key, child] of Object.entries(props)) {
      if (isObject(child) && isContainer(child)) {
        out.push("", renderSection(`${path}.${key}`, child, level + 1));
      }
    }
  }
  return out.join("\n");
}

/**
 * Render the docs config-reference page from the LIVE `discern.toml` schema:
 * every section, key, type, default, and description, straight from the canonical
 * `.describe(...)` annotations. Replaces a hand-maintained reference that would
 * drift from what the engine enforces.
 */
export function renderConfigReferenceDoc(): string {
  const root = z.toJSONSchema(configSchema, { io: "input" }) as Record<
    string,
    unknown
  >;
  const props = isObject(root.properties) ? root.properties : {};
  const out: string[] = [
    DOCS_BANNER,
    "",
    "# `discern.toml` — config reference",
    "",
    typeof root.description === "string"
      ? root.description
      : "The one file that configures a discern install.",
    "",
    "Every section, key, type, and default below is generated from the canonical schema (`src/shared/config_schema.ts`). A **Default** is the value discern uses when the key is absent; the gate, worktree workflow, and ratchets all read this shape through one typed loader, so what is documented here is exactly what the engine enforces.",
    "",
    "The named-table sections (`[checks.<name>]`, `[scopes.<name>]`, `[ratchets.<name>]`, `[worktree.resources.<name>]`) are repeatable: declare as many as you like, each with its own `<name>`.",
  ];
  for (const [section, schema] of Object.entries(props)) {
    if (isObject(schema)) {
      out.push("", renderSection(section, schema, 2));
    }
  }
  return `${out.join("\n")}\n`;
}

/** The live config's top-level section names, in schema order — used by the
 * template drift-guard test (every section must appear in `discern.toml.tmpl`). */
export function configSectionNames(): string[] {
  const root = z.toJSONSchema(configSchema, { io: "input" }) as Record<
    string,
    unknown
  >;
  return isObject(root.properties) ? Object.keys(root.properties) : [];
}
