/**
 * First-party legal-package generator.
 *
 * The authored files named by `license_registry.ts` stay the legal sources.
 * Codegen embeds their exact text in a compressed module so an installed,
 * standalone binary can print the complete package without a checkout.
 */

import { gunzipSync, gzipSync } from "zlib";
import { decodeBase64, encodeBase64 } from "@std/encoding/base64";
import { join } from "@std/path";
import {
  FIRST_PARTY_LEGAL_DOCUMENTS,
  type FirstPartyLegalDocumentDeclaration,
} from "./license_registry.ts";
import {
  type FirstPartyLegalDocument,
  type FirstPartyLicenseBundle,
  firstPartyLicenseBundleSchema,
} from "./license_bundle_schemas.ts";
import { decodeJson } from "./runtime_decode.ts";

export type { FirstPartyLegalDocument, FirstPartyLicenseBundle };

/** The committed module generated from the authored legal package. */
export const FIRST_PARTY_LICENSE_ARTIFACT_PATHS = {
  bundle: "src/lib/first_party_license_bundle.ts",
} as const;

/** Options for {@link generateFirstPartyLicenseBundle}. */
export interface GenerateFirstPartyLicenseOptions {
  readonly repoRoot: string;
  /** Test seam proving a future registry member auto-enrols in generation. */
  readonly documents?: readonly FirstPartyLegalDocumentDeclaration[];
}

/** Read every declared source and build the canonical in-memory bundle. */
export async function generateFirstPartyLicenseBundle(
  options: GenerateFirstPartyLicenseOptions,
): Promise<FirstPartyLicenseBundle> {
  const declarations = options.documents ?? FIRST_PARTY_LEGAL_DOCUMENTS;
  const documents: FirstPartyLegalDocument[] = [];
  for (const declaration of declarations) {
    const text = await Deno.readTextFile(
      join(options.repoRoot, declaration.path),
    );
    if (text.trim().length === 0) {
      throw new Error(`${declaration.path} is empty`);
    }
    if (!text.includes(declaration.smokeMarker)) {
      throw new Error(
        `${declaration.path} does not contain its registered smoke marker: ` +
          declaration.smokeMarker,
      );
    }
    documents.push({ ...declaration, text });
  }
  return { documents };
}

const BUNDLE_EXPORT_RE =
  /^\/\/ GENERATED by `deno task codegen` from the first-party legal documents — do not edit\.\n\/\/ See src\/shared\/first_party_license_codegen\.ts for how and why\.\n\n\/\*\* The first-party legal-document bundle: gzipped JSON in base64\. \*\/\nexport const FIRST_PARTY_LICENSE_BUNDLE_B64 =\n {2}"([^"]+)";\n$/;

/** Decode a generated module to its canonical, uncompressed JSON bytes. */
export function firstPartyLicenseBundlePayload(
  moduleText: string,
): Uint8Array {
  const encoded = moduleText.match(BUNDLE_EXPORT_RE)?.[1];
  if (encoded === undefined) {
    throw new Error(
      "generated first-party bundle has no canonical " +
        "FIRST_PARTY_LICENSE_BUNDLE_B64 export",
    );
  }
  try {
    return new Uint8Array(gunzipSync(decodeBase64(encoded)));
  } catch (error) {
    throw new Error("generated first-party bundle is not valid gzip", {
      cause: error,
    });
  }
}

/** Parse the canonical payload represented by a generated module. */
export function readFirstPartyLicenseBundle(
  moduleText: string,
): FirstPartyLicenseBundle {
  return decodeJson(
    firstPartyLicenseBundleSchema,
    new TextDecoder().decode(firstPartyLicenseBundlePayload(moduleText)),
    "generated first-party license bundle payload",
  );
}

/** Whether two canonical generated modules carry identical JSON bytes. */
export function sameFirstPartyLicenseBundlePayload(
  left: string,
  right: string,
): boolean {
  try {
    const a = firstPartyLicenseBundlePayload(left);
    const b = firstPartyLicenseBundlePayload(right);
    return a.length === b.length && a.every((byte, index) => byte === b[index]);
  } catch {
    return false;
  }
}

/** Render the generated module embedded by the standalone binary. */
export function renderFirstPartyLicenseBundleModule(
  bundle: FirstPartyLicenseBundle,
): string {
  const encoded = encodeBase64(
    new Uint8Array(gzipSync(JSON.stringify(bundle), { level: 9 })),
  );
  return [
    "// GENERATED by `deno task codegen` from the first-party legal documents — do not edit.",
    "// See src/shared/first_party_license_codegen.ts for how and why.",
    "",
    "/** The first-party legal-document bundle: gzipped JSON in base64. */",
    "export const FIRST_PARTY_LICENSE_BUNDLE_B64 =",
    `  "${encoded}";`,
    "",
  ].join("\n");
}
