/**
 * Render the internal hint inventory from the live registry. The committed page
 * is a generated audit surface; it has no hand-maintained entry list.
 */

import { type HintDef, HINTS } from "./hints.ts";

/** The banner stamped atop the generated inventory page. */
const DOCS_BANNER =
  "<!-- GENERATED by `deno task codegen` from HINTS (src/shared/hints.ts) — do NOT edit by hand. Change the registry and regenerate. -->";

/** Render one registry entry with its registered example parameters. */
function renderEntry(def: HintDef<unknown>): string {
  const when = def.when?.trim();
  if (when === undefined || when === "") {
    throw new Error(`hint ${def.id} has no emitting context`);
  }
  if (/\r|\n/.test(when)) {
    throw new Error(`hint ${def.id} has a multi-line emitting context`);
  }
  const example = def.template(def.example);
  let fence = "```";
  while (example.includes(fence)) fence += "`";
  return [
    `## \`${def.id}\``,
    "",
    `- Category: \`${def.category}\``,
    `- Audience: \`${def.audience}\``,
    `- Family: ${def.family === undefined ? "—" : `\`${def.family}\``}`,
    `- Emitting context: ${when}`,
    "",
    "Rendered example:",
    "",
    `${fence}text`,
    example,
    fence,
  ].join("\n");
}

/** Render the complete, id-sorted internal hint inventory. */
export function renderHintInventoryDoc(): string {
  const defs = Object.values(HINTS) as unknown as readonly HintDef<unknown>[];
  const entries = [...defs].sort((a, b) =>
    a.id < b.id ? -1 : a.id > b.id ? 1 : 0
  );
  return [
    DOCS_BANNER,
    "",
    "# Hint inventory",
    "",
    "_Every advisory hint, generated from the live registry._",
    "",
    "Entries follow id order. Emitting context states when an entry fires. Each example renders the template with its registered example parameters.",
    "",
    entries.map(renderEntry).join("\n\n"),
    "",
  ].join("\n");
}
