/** Public schema identities and the root generated artifacts served at them. */

export const CONFIG_SCHEMA_ID =
  "https://discern.sh/schema/v1/discern-config.schema.json";

export const RESULT_SCHEMA_ID =
  "https://discern.sh/schema/v1/discern-results.schema.json";

export interface PublicSchemaPublication {
  readonly id: `https://discern.sh/schema/${string}`;
  readonly artifactPath: `schema/${string}.json`;
  readonly label: string;
  readonly contract: string;
}

export const PUBLIC_SCHEMA_PUBLICATIONS = [
  {
    id: CONFIG_SCHEMA_ID,
    artifactPath: "schema/discern-config.schema.json",
    label: "`discern.toml` configuration",
    contract: "Configuration file structure, keys, and value types.",
  },
  {
    id: RESULT_SCHEMA_ID,
    artifactPath: "schema/discern-results.schema.json",
    label: "CLI and MCP results",
    contract: "CLI result envelopes and MCP tool-result wrappers.",
  },
] as const satisfies readonly PublicSchemaPublication[];

export const PUBLIC_SCHEMA_REFERENCE_START =
  "<!-- BEGIN GENERATED: public schema publications -->";
export const PUBLIC_SCHEMA_REFERENCE_END =
  "<!-- END GENERATED: public schema publications -->";

/** Render the public schema registry as a reference-table block. */
export function renderPublicSchemaReference(): string {
  return [
    PUBLIC_SCHEMA_REFERENCE_START,
    "<!-- Generated by `deno task codegen` from `PUBLIC_SCHEMA_PUBLICATIONS`. -->",
    "",
    "| Schema | Public `$id` | Repository artifact | Contract |",
    "| --- | --- | --- | --- |",
    ...PUBLIC_SCHEMA_PUBLICATIONS.map((publication) =>
      `| ${publication.label} | <${publication.id}> | ` +
      `[\`${publication.artifactPath}\`](../../../${publication.artifactPath}) | ` +
      `${publication.contract} |`
    ),
    "",
    PUBLIC_SCHEMA_REFERENCE_END,
  ].join("\n");
}

/** Replace the registry-derived schema block without changing authored prose. */
export function replacePublicSchemaReference(
  document: string,
  reference: string,
): string {
  const start = document.indexOf(PUBLIC_SCHEMA_REFERENCE_START);
  const end = document.indexOf(PUBLIC_SCHEMA_REFERENCE_END);
  if (start < 0 || end < start) {
    throw new Error(
      "mcp-and-results.md is missing the public schema publication markers",
    );
  }
  const after = end + PUBLIC_SCHEMA_REFERENCE_END.length;
  return `${document.slice(0, start)}${reference}${document.slice(after)}`;
}
