/**
 * Render the internal tip inventory from the live registry. The committed page
 * is a generated audit surface; it has no hand-maintained entry list.
 *
 * Unlike the hint inventory's id-sorted sections, entries here follow the
 * registry's authored order: that order is the desk's teaching curriculum
 * (ADR 0234), and the inventory exists partly so a curriculum review can read
 * it as the desk will teach it.
 */

import { type RegisteredTip, renderTipCli, TIPS } from "./tips.ts";

/** The banner stamped atop the generated inventory page. */
const DOCS_BANNER =
  "<!-- GENERATED by `deno task codegen` from TIPS (src/shared/tips.ts) — do NOT edit by hand. Change the registry and regenerate. -->";

/** Render one registry entry with its registered example parameters. */
function renderEntry(tip: RegisteredTip): string {
  const when = tip.when.trim();
  if (when === "") {
    throw new Error(`tip ${tip.id} has no relevance context`);
  }
  if (/\r|\n/.test(when)) {
    throw new Error(`tip ${tip.id} has a multi-line relevance context`);
  }
  // The inventory shows the line exactly as the desk delivers it: command
  // references in their CLI spelling, at full width.
  const line = renderTipCli(tip);
  let fence = "```";
  while (line.includes(fence)) fence += "`";
  const features = tip.features.map((id) => `\`${id}\``).join(", ");
  const followThrough = tip.followThrough === undefined
    ? "—"
    : `\`${tip.followThrough.kind}\` (${
      tip.followThrough.verbs.map((verb) => `\`${verb}\``).join(", ")
    })`;
  return [
    `## \`${tip.id}\``,
    "",
    `- Relevance: ${when}`,
    `- Predicate: ${
      tip.predicate === undefined ? "—" : `\`${tip.predicate.kind}\``
    }`,
    `- Since: ${tip.since === undefined ? "—" : `\`${tip.since}\``}`,
    `- Teaches: ${features}`,
    `- Follow-through: ${followThrough}`,
    "",
    "Rendered line:",
    "",
    `${fence}text`,
    line,
    fence,
  ].join("\n");
}

/** Render the complete tip inventory, in curriculum (authored) order. */
export function renderTipInventoryDoc(): string {
  return [
    DOCS_BANNER,
    "",
    "# Tip inventory",
    "",
    "_Every desk tip, generated from the live registry._",
    "",
    "Entries follow the authored order — the curriculum the desk walks unseen tips through. Relevance states when an entry is contextually timely; a predicate makes it so, a since tag surfaces it after the upgrade that brought it, and each rendered line reads as the desk shows it.",
    "",
    TIPS.map(renderEntry).join("\n\n"),
    "",
  ].join("\n");
}
