/**
 * Render the internal tip inventory from the live registry. The committed page
 * is a generated audit surface; it has no hand-maintained entry list.
 *
 * Unlike the hint inventory's id-sorted sections, entries here follow the
 * registry's authored order: that order is the desk's teaching curriculum
 * (ADR 0234), and the inventory exists partly so a curriculum review can read
 * it as the desk will teach it.
 */

import {
  type RegisteredTip,
  renderTipCli,
  TIP_COVERAGE_DELIBERATELY_ABSENT,
  TIP_RENDERED_LENGTH_LIMIT,
  TIPS,
} from "./tips.ts";

/** The banner stamped atop the generated inventory page. */
const DOCS_BANNER =
  "<!-- GENERATED by `deno task codegen` from TIPS (src/shared/tips.ts) — do NOT edit by hand. Change the registry and regenerate. -->";

/** Render one registry entry with its registered example parameters. */
function renderEntry(tip: RegisteredTip): string {
  const when = tip.when.trim();
  if (when === "") {
    throw new Error(`tip ${tip.id} has no relevance context`);
  }
  if (/\r|\n/.test(when)) {
    throw new Error(`tip ${tip.id} has a multi-line relevance context`);
  }
  // The inventory shows the line exactly as the desk delivers it: command
  // references in their CLI spelling, at full width.
  const line = renderTipCli(tip);
  let fence = "```";
  while (line.includes(fence)) fence += "`";
  const features = tip.features.map((id) => `\`${id}\``).join(", ");
  const followThrough = tip.followThrough === undefined
    ? "—"
    : `\`${tip.followThrough.kind}\` (${
      tip.followThrough.verbs.map((verb) => `\`${verb}\``).join(", ")
    })`;
  return [
    `## \`${tip.id}\``,
    "",
    `- Relevance: ${when}`,
    `- Predicate: ${
      tip.predicate === undefined ? "—" : `\`${tip.predicate.kind}\``
    }`,
    `- Since: ${tip.since === undefined ? "—" : `\`${tip.since}\``}`,
    `- Teaches: ${features}`,
    `- Follow-through: ${followThrough}`,
    "",
    "Rendered line:",
    "",
    `${fence}text`,
    line,
    fence,
  ].join("\n");
}

/** Render the feature-and-verb members deliberately left out of the tips. */
function renderAbsenceLedger(): string {
  const rows = Object.entries(TIP_COVERAGE_DELIBERATELY_ABSENT)
    .toSorted(([left], [right]) => left.localeCompare(right))
    .map(([member, reason]) =>
      `| \`${member}\` | ${reason.replaceAll("|", "\\|")} |`
    );
  return [
    "## Coverage absences",
    "",
    "The enrolment guard derives every feature node and top-level verb from its live registry. A member without a tip appears here with the reason. An unexplained member fails the gate.",
    "",
    "| Member | Why it has no tip |",
    "| ------ | ----------------- |",
    ...rows,
  ].join("\n");
}

/** Render the complete tip inventory, in curriculum (authored) order. */
export function renderTipInventoryDoc(): string {
  return [
    DOCS_BANNER,
    "",
    "# Tip inventory",
    "",
    "_Every desk tip, generated from the live registry._",
    "",
    "Entries follow the authored order. The order is a guided onboarding path. It starts with the desk, orientation, a separate working copy, and the daily loop. It then teaches human supervision, practice health, quality rules, project upkeep, reusable agent guides, and power tools. Contextual lessons can step ahead when the current state makes them timely. Authors place a new tip at its learning moment instead of appending it by default.",
    "",
    `Every rendered line is one or two short sentences and no more than ${TIP_RENDERED_LENGTH_LIMIT} characters, a two-to-three-line wrap at ordinary desk widths. Commands come from typed references. The register guard reuses the plain-language jargon scan and permits only reasoned terms that the desk already shows.`,
    "",
    "There is no reading-grade ceiling: on samples this short, command names and placeholders move the score sharply, while an aggregate can hide one dense line. The per-tip jargon, sentence, and length checks hold the intended failure directly.",
    "",
    TIPS.map(renderEntry).join("\n\n"),
    "",
    renderAbsenceLedger(),
    "",
  ].join("\n");
}
