/**
 * Framing authority for committed generated inventories. Member wording stays
 * with the member registry unless a policy says otherwise; titles, banners,
 * explanatory framing, renderer identity, documentation exposure, and guard
 * tests live here so a generator cannot invent its own account.
 */

/** How one inventory obtains the wording for each generated member. */
export type InventoryMemberWordingAuthority =
  | {
    readonly kind: "co-located";
    readonly module: string;
    readonly exportName: string;
  }
  | {
    readonly kind: "shared-policy";
    readonly module: string;
    readonly exportName: string;
  };

/** One inventory's complete projection declaration. */
export interface GeneratedInventoryPolicy {
  readonly artifactPath: string;
  readonly banner: string;
  readonly title: string;
  readonly subtitle: string;
  readonly framing: readonly string[];
  readonly memberWording: InventoryMemberWordingAuthority;
  readonly renderer: {
    readonly module: string;
    readonly exportName: string;
  };
  readonly documentation: string;
  readonly tests: readonly string[];
}

/** Every repository inventory framing policy, keyed by its canonical-set id. */
export const GENERATED_INVENTORY_POLICIES = {
  hints: {
    artifactPath: "project/map/_internal/hint-inventory.md",
    banner:
      "<!-- GENERATED by `deno task codegen` from HINTS (src/shared/hints.ts) — do NOT edit by hand. Change the registry and regenerate. -->",
    title: "Hint inventory",
    subtitle: "Every advisory hint, generated from the live registry.",
    framing: [
      "Entries follow id order. Emitting context states when an entry fires. Each example renders the template with its registered example parameters. An interactive example appears when the terminal uses different wording for the same facts.",
      "Audience `all` renders on every surface. Audience `agent` marks an instruction only an agent can execute: the interactive terminal presentation drops it, while JSON, Markdown, and Model Context Protocol (MCP) results always carry it.",
    ],
    memberWording: {
      kind: "co-located",
      module: "src/shared/hints.ts",
      exportName: "HINTS",
    },
    renderer: {
      module: "src/shared/hint_inventory_codegen.ts",
      exportName: "renderHintInventoryDoc",
    },
    documentation: "project/map/_internal/hint-inventory.md",
    tests: ["tests/hint_inventory_codegen_test.ts"],
  },
  tips: {
    artifactPath: "project/map/_internal/tip-inventory.md",
    banner:
      "<!-- GENERATED by `deno task codegen` from TIPS (src/shared/tips.ts) — do NOT edit by hand. Change the registry and regenerate. -->",
    title: "Tip inventory",
    subtitle: "Every desk tip, generated from the live registry.",
    framing: [
      "Entries follow the authored order, which defines the onboarding sequence. The sequence starts with the desk, orientation, an isolated working copy, and the daily loop. It then covers human supervision, practice health, quality rules, project upkeep, reusable agent guides, and power tools. Contextual lessons may appear earlier when live state makes them relevant. Place each new tip at its intended learning point.",
      "Every rendered line is one or two short sentences and no more than {{TIP_RENDERED_LENGTH_LIMIT}} characters, a two-to-three-line wrap at ordinary desk widths. Commands come from typed references. The register guard applies the plain-language jargon scan and permits only terms listed with a reason in its desk allowlist.",
      "The guard omits a reading-grade ceiling because command names and placeholders distort scores on samples this short, while aggregates can hide a dense line. Per-tip jargon, sentence-count, and length checks enforce the register directly.",
    ],
    memberWording: {
      kind: "co-located",
      module: "src/shared/tips.ts",
      exportName: "TIPS",
    },
    renderer: {
      module: "src/shared/tip_inventory_codegen.ts",
      exportName: "renderTipInventoryDoc",
    },
    documentation: "project/map/_internal/tip-inventory.md",
    tests: ["tests/tip_inventory_codegen_test.ts"],
  },
  "canonical-sets": {
    artifactPath: "project/map/_internal/registry-atlas.md",
    banner:
      "<!-- GENERATED by `deno task codegen` from CANONICAL_SETS (scripts/canonical_sets.ts) — do NOT edit by hand. Change the registry and regenerate. -->",
    title: "Registry atlas",
    subtitle:
      "The meta-registry generates every canonical set's members, source, guards, artifacts, and enrollments.",
    framing: [
      "To add a set, declare it in `scripts/canonical_sets.ts`. The enrollment guard (`tests/canonical_sets_enrolment_test.ts`) requires a declared owner for every conventionally named guard test and codegen target. The claim sweep (`tests/ssot_claim_guard_test.ts`) requires every module that claims single-source-of-truth status to have a declared source or recorded absence.",
    ],
    memberWording: {
      kind: "co-located",
      module: "scripts/canonical_sets.ts",
      exportName: "CANONICAL_SETS",
    },
    renderer: {
      module: "scripts/canonical_sets.ts",
      exportName: "renderRegistryAtlasDoc",
    },
    documentation: "project/map/_internal/registry-atlas.md",
    tests: ["tests/canonical_sets_enrolment_test.ts"],
  },
  "public-schema-publications": {
    artifactPath: "project/map/_internal/public-contract-digest.md",
    banner:
      "<!-- GENERATED by `deno task codegen` from PUBLIC_SCHEMA_PUBLICATIONS (src/shared/public_schemas.ts) and the committed artifacts under schema/ — do NOT edit by hand. Change the registries and regenerate. -->",
    title: "Public contract digest",
    subtitle:
      "Every published command, tool, result shape, configuration key, and convention, rendered from the committed contract artifacts.",
    framing: [
      "Each section renders one publication from its artifact under `schema/`: the surface's contract sentence, its same-major policy, and a table for every member. Evolving members carry their tier, open vocabularies list their known members, and closed vocabularies list the members each artifact carries.",
      "The digest is a reading aid. The artifacts are the contract, and the [compatibility policy](../70-reference/compatibility-policy.md) explains the rules the comparators enforce.",
    ],
    memberWording: {
      kind: "co-located",
      module: "src/shared/public_schemas.ts",
      exportName: "PUBLIC_SCHEMA_PUBLICATIONS",
    },
    renderer: {
      module: "scripts/contract_digest.ts",
      exportName: "renderContractDigestDoc",
    },
    documentation: "project/map/_internal/public-contract-digest.md",
    tests: ["tests/contract_digest_test.ts"],
  },
} as const satisfies Record<string, GeneratedInventoryPolicy>;

export type GeneratedInventoryPolicyId =
  keyof typeof GENERATED_INVENTORY_POLICIES;
