/** Generate the provider-logo provenance record from the provider registry. */

import {
  PROVIDER_TRADEMARK_NOTICE,
  providerBrandSilhouette,
  PROVIDERS,
} from "../src/lib/providers.ts";
import { AGENT_NAMES } from "../src/shared/agent_catalogue.ts";

export const PROVIDER_BRAND_PROVENANCE_REL =
  "site/pages/assets/integrations/README.md";

/** Render every checked-in provider SVG with its first-party provenance. */
export function renderProviderBrandProvenance(): string {
  const lines = [
    "<!-- GENERATED by `deno task codegen` from PROVIDERS (src/lib/providers.ts) — do NOT edit by hand. -->",
    "",
    "# Integration logo provenance",
    "",
    "These unmodified vendor assets identify coding-agent integrations supported by discern. Review the linked first-party brand rules before changing their presentation and again before the first public release tag.",
    "",
    PROVIDER_TRADEMARK_NOTICE,
    "",
    "| File | Owner | Upstream asset | Asset source | Retrieved | Brand rules |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  for (const name of AGENT_NAMES) {
    const brand = PROVIDERS[name].brand;
    const assets = [brand.mark, providerBrandSilhouette(brand), brand.wordmark];
    const seen = new Set<string>();
    for (const asset of assets) {
      if (seen.has(asset.path)) continue;
      seen.add(asset.path);
      lines.push(
        `| [\`${asset.path.slice(asset.path.lastIndexOf("/") + 1)}\`](${
          asset.path.slice(asset.path.lastIndexOf("/") + 1)
        }) | ${brand.owner} | ${asset.upstream} | [source](${brand.assetSourceUrl}) | ${brand.retrievedOn} | [rules](${brand.brandRulesUrl}) |`,
      );
    }
    if (brand.note !== undefined) {
      lines.push(
        `| _${
          PROVIDERS[name].label
        } note_ | ${brand.owner} | ${brand.note} | [brand page](${brand.sourceUrl}) | ${brand.retrievedOn} | [rules](${brand.brandRulesUrl}) |`,
      );
    }
  }
  return `${lines.join("\n")}\n`;
}
