/** Generate the small compiled projection without importing the site into the binary. */
import {
  type AuthoredRelease,
  currentRelease,
  loadReleaseRecords,
} from "../site/releases/records.ts";
import denoJson from "../deno.json" with { type: "json" };

export const RELEASE_METADATA_PATH = "src/lib/release_metadata.ts";

/** The version stays a JSON import; only the optional resolved name is generated. */
export function renderReleaseMetadata(
  records: readonly AuthoredRelease[],
  version: string,
): string {
  const record = currentRelease(records, version);
  return `// GENERATED by scripts/codegen.ts from release records. Do not edit.\n` +
    `import denoJson from "../../deno.json" with { type: "json" };\n\n` +
    `export const RELEASE_METADATA: { version: string; codename?: string } = {\n` +
    `  version: denoJson.version,\n` +
    (record.codename === undefined
      ? ""
      : `  codename: ${JSON.stringify(record.codename)},\n`) +
    `};\n`;
}

/** Refuse stale generated metadata before compiling release bytes. */
export async function verifyReleaseMetadata(): Promise<void> {
  const expected = renderReleaseMetadata(
    await loadReleaseRecords(),
    denoJson.version,
  );
  const actual = await Deno.readTextFile(
    new URL(`../${RELEASE_METADATA_PATH}`, import.meta.url),
  );
  if (actual !== expected) {
    throw new Error(
      `${RELEASE_METADATA_PATH}: stale release metadata; run deno task codegen`,
    );
  }
}
