/**
 * Operator-oriented `discern --help` — group, reorder, and annotate the flat
 * command list so the daily-driver verbs lead and the workflow reads as a map.
 *
 * WHY this adapts Cliffy's public facts instead of calling `.group()`: in Cliffy
 * (1.2.x), `.group()` groups OPTIONS, not commands, and the built-in help
 * generator renders every subcommand in one flat, registration-ordered block.
 * No exported generator supports command groups. Cliffy remains the command-fact
 * and parser authority through its public getters; the published design-system
 * CLI owns text measurement, wrapping, Tokens, and the complete visible root-help
 * treatment. (ADR 0066, as amended by ADR 0279.)
 */

import type { Command, Example, Option } from "@cliffy/command";
import { renderSectionCli } from "discern-design-system/cli";
import type { EnvReader } from "./shared/env.ts";
import {
  alignedLabelWidth,
  displayWidth,
  renderAlignedRows,
  wrapText,
} from "./lib/text.ts";
import {
  type TerminalContext,
  terminalContext,
  terminalContextWithColor,
  terminalLine,
  terminalMultiline,
  terminalProcessContext,
} from "./lib/terminal.ts";

/** Ambient inputs that callers may pin for deterministic help rendering. */
export interface OperatorHelpOptions {
  /** Lay out the whole root-help artifact to this width. */
  readonly width?: number;
  /** Environment source used by terminal-width fallback (chiefly `$COLUMNS`). */
  readonly env?: EnvReader;
  /** Package presentation facts already resolved at the CLI boundary. */
  readonly terminal?: TerminalContext;
  /**
   * The CLI's resolved colour decision (`--no-color` flag + NO_COLOR + isatty).
   * When set, it controls the package context for the complete help. Cliffy's
   * generated bytes are discarded. Omitted, the process-wide terminal context
   * applies.
   */
  readonly color?: boolean;
}

/** A named, ordered bucket of top-level commands for the help listing. */
export interface CommandGroup {
  /** The heading shown above the bucket. */
  readonly name: string;
  /** A short dim annotation after the heading — chiefly WHO drives this group, so
   * a first-time reader sees that the loop and worktree verbs are the ones their
   * coding agent runs, not chores for them. */
  readonly note: string;
  /** The command names, in the order they should read under the heading. */
  readonly commands: readonly string[];
}

/**
 * The command → group map, ordered so the verbs an agent runs every iteration
 * lead and the once-in-a-while human chores sink. This is the SSOT for
 * `discern --help` grouping: the guard test (`tests/engine_help_groups_test.ts`)
 * asserts every visible top-level command is covered here, so a verb registered
 * without a home fails the gate rather than landing silently ungrouped.
 *
 * The notes allude to WHO runs each group: discern is driven mainly by the
 * human's coding agent, and the loop + worktree verbs are almost always the
 * agent's, not the human's — so a novice doesn't read them as their own chores.
 */
export const COMMAND_GROUPS: readonly CommandGroup[] = [
  {
    name: "Your desk",
    note: "interactive task supervision and worktree entry",
    commands: ["desk", "enter"],
  },
  {
    name: "Agentic loop",
    note: "your coding agent runs these as it works",
    commands: [
      "status",
      "prepare",
      "done",
      "test",
      "progress",
      "queue",
      "tidy",
    ],
  },
  {
    name: "Worktree lifecycle",
    note: "isolated workspaces your agent drives",
    commands: ["start", "update", "await", "accept", "worktree", "identity"],
  },
  {
    name: "Project Scripts",
    note: "project-owned automation, listed or run by name",
    commands: ["scripts"],
  },
  {
    name: "Setup & maintenance",
    note: "you or your agent tend the installation",
    commands: [
      "setup",
      "upgrade",
      "doctor",
      "config",
      "refresh",
      "uninstall",
    ],
  },
  {
    name: "Inspect & explore",
    note: "read-only views for you or your agent",
    commands: [
      "improvement",
      "standards",
      "checkpoints",
      "skills",
      "impact",
      "coupling",
      "patterns",
      "map",
      "docs",
      "help",
      "licenses",
      "mcp",
    ],
  },
];

/** Every command name that has a declared group (drives the coverage guard). */
export function groupedCommandNames(): Set<string> {
  return new Set(COMMAND_GROUPS.flatMap((g) => g.commands));
}

/**
 * Resolve one presentation snapshot for the whole help render. An injected width
 * alters only the immutable snapshot used here; it never re-observes the process.
 */
function helpPresentation(options: OperatorHelpOptions): {
  readonly terminal: TerminalContext;
  readonly width: number;
} {
  const base = options.terminal ??
    (options.env === undefined
      ? terminalContext()
      : terminalProcessContext({ env: options.env, fallbackColumns: 150 }));
  const width = Math.max(
    1,
    Math.floor(options.width ?? base.capabilities.columns),
  );
  const colored = terminalContextWithColor(
    base,
    options.color ?? base.color,
  );
  return {
    terminal: colored,
    width,
  };
}

/** Paint one root-help section heading through package Token roles. */
function helpHeading(text: string, terminal: TerminalContext): string {
  return terminal.tone(text, "accent", "strong");
}

/**
 * Wrap one fact within an indented help row. Long tokens break only at
 * package-owned grapheme boundaries, so every emitted line remains bounded.
 */
function wrapHelpFact(
  text: string,
  width: number,
  indent: string,
): string[] {
  const contentWidth = Math.max(1, width - displayWidth(indent));
  return wrapText(text, contentWidth, "", { breakLongWords: true })
    .map((line) => `${indent}${line}`.trimEnd());
}

/** Render one section's label + body rows through the shared aligned-listing
 * authority: accent labels, muted bodies, stacking on narrow terminals. */
function renderHelpRows(
  rows: readonly { label: string; body: string }[],
  terminal: TerminalContext,
  width: number,
  labelCap: number,
): string[] {
  return renderAlignedRows(
    rows.map((row) => ({
      label: terminalLine(row.label.trimEnd()),
      body: terminalMultiline(row.body.trim()),
    })),
    {
      labelCap,
      width,
      styleLabel: (cell) => terminal.tone(cell, "accent", "strong"),
      styleBody: (line) => terminal.role(line, "muted"),
    },
  );
}

/** Canonical public Cliffy option label: aliases plus any argument definition. */
function optionLabel(option: Option): string {
  const flags = option.flags.join(", ");
  return option.typeDefinition === undefined || option.typeDefinition === ""
    ? flags
    : `${flags} ${option.typeDefinition}`;
}

/** Render the parser-owned root usage from public Cliffy command facts. */
function renderUsage(
  root: Command,
  terminal: TerminalContext,
  width: number,
): string[] {
  const usage = terminalLine(root.getUsage());
  const path = terminalLine(root.getPath());
  const value = `${path}${usage === "" ? "" : ` ${usage}`}`;
  const label = "Usage:";
  const inlinePrefix = `${label}   `;
  if (displayWidth(inlinePrefix) + displayWidth(value) <= width) {
    return [
      `${helpHeading(label, terminal)}   ${terminal.tone(value, "accent")}`,
    ];
  }
  return [
    helpHeading(label, terminal),
    ...wrapHelpFact(value, width, "  ").map((line) =>
      terminal.tone(line, "accent").trimEnd()
    ),
  ];
}

/** Render one prose section with its facts retained and safely width-bounded. */
function renderProseSection(
  heading: string,
  content: string,
  terminal: TerminalContext,
  width: number,
): string[] {
  return [
    helpHeading(`${heading}:`, terminal),
    "",
    ...wrapHelpFact(terminalMultiline(content), width, "  "),
  ];
}

/** Render public Cliffy option facts with adaptive hanging indents. */
function renderOptions(
  options: readonly Option[],
  terminal: TerminalContext,
  width: number,
): string[] {
  return [
    helpHeading("Options:", terminal),
    "",
    ...renderHelpRows(
      options.map((option) => ({
        label: optionLabel(option),
        body: `- ${option.description}`,
      })),
      terminal,
      width,
      28,
    ),
  ];
}

/** Render public Cliffy example facts in their declared order. */
function renderExamples(
  examples: readonly Example[],
  terminal: TerminalContext,
  width: number,
): string[] {
  return [
    helpHeading("Examples:", terminal),
    "",
    ...renderHelpRows(
      examples.map((example) => ({
        label: example.name,
        body: example.description,
      })),
      terminal,
      width,
      28,
    ),
  ];
}

/**
 * Render the grouped "Commands:" section from the live command tree. Reads the
 * authoritative name + one-line description straight off each visible command
 * (so it can never disagree with what Cliffy would have listed), laid out under
 * {@link COMMAND_GROUPS} headings with a uniform name column and the description
 * word-wrapped to `width` with a hanging indent (so a long line never wraps back
 * to column 0 and shreds the alignment in a narrow terminal).
 */
function renderGroupedCommands(
  root: Command,
  terminal: TerminalContext,
  width: number,
): string {
  const visible = root.getCommands(false).map((command) => {
    const rawName = command.getName();
    return {
      rawName,
      name: terminalLine(rawName),
      description: terminalMultiline(command.getShortDescription()),
    };
  });
  const byName = new Map(visible.map((entry) => [entry.rawName, entry]));
  // One shared name column across every group, so the whole Commands section
  // aligns; the shared authority owns the gutter, wrap, and narrow stacking.
  const nameCol = alignedLabelWidth(visible.map((entry) => entry.name), 20);

  const heading = (text: string): string =>
    terminal.tone(text, "accent", "strong");
  const name = (text: string): string =>
    terminal.tone(text, "accent", "strong");
  const desc = (text: string): string => terminal.role(text, "muted");
  const rowLines = (entry: (typeof visible)[number]): string[] =>
    renderAlignedRows([{ label: entry.name, body: entry.description }], {
      labelWidth: nameCol,
      indent: "    ",
      width,
      styleLabel: name,
      styleBody: desc,
    });

  const out: string[] = ["Commands:", ""];
  const seen = new Set<string>();
  for (const group of COMMAND_GROUPS) {
    const members = group.commands
      .map((n) => byName.get(n))
      .filter((entry): entry is (typeof visible)[number] =>
        entry !== undefined
      );
    if (members.length === 0) {
      continue;
    }
    if (width >= 5) {
      out.push(terminal.presenter.present(renderSectionCli, {
        title: terminalLine(group.name),
        body: terminalMultiline(`— ${group.note}`),
        treatment: "rule",
        spacing: "none",
        width,
      }));
    } else {
      out.push(heading(group.name), desc(`— ${group.note}`));
    }
    for (const entry of members) {
      out.push(...rowLines(entry));
      seen.add(entry.rawName);
    }
    out.push("");
  }

  // Defence in depth: a visible command with no declared group still shows, so a
  // missing assignment is loud rather than a vanished verb. The guard test keeps
  // this list empty; rendering it is the belt to that test's braces.
  const ungrouped = visible.filter((entry) => !seen.has(entry.rawName));
  if (ungrouped.length > 0) {
    out.push(`  ${heading("Other")}`);
    for (const entry of ungrouped) {
      out.push(...rowLines(entry));
    }
    out.push("");
  }

  if (out.at(-1) === "") {
    out.pop();
  }
  return out.join("\n");
}

/**
 * Render the operator-oriented root help from Cliffy's public command facts.
 * `getHelp()` first registers the framework's built-in help/version options; its
 * rendered bytes are discarded so one package-backed width and Token context
 * governs the complete artifact. Cliffy remains the parser and fact authority.
 */
export function operatorHelp(
  root: Command,
  options: OperatorHelpOptions = {},
): string {
  const presentation = helpPresentation(options);
  root.getHelp({ colors: false, width: presentation.width });
  const terminal = presentation.terminal;
  const width = presentation.width;
  const sections: string[][] = [renderUsage(root, terminal, width)];
  if (root.getDescription() !== "") {
    sections.push(
      renderProseSection("Description", root.getDescription(), terminal, width),
    );
  }
  const registeredOptions = root.getOptions(false);
  if (registeredOptions.length > 0) {
    sections.push(renderOptions(registeredOptions, terminal, width));
  }
  if (root.getCommands(false).length > 0) {
    sections.push(renderGroupedCommands(root, terminal, width).split("\n"));
  }
  const examples = root.getExamples();
  if (examples.length > 0) {
    sections.push(renderExamples(examples, terminal, width));
  }
  const rebuilt = sections.flatMap((section, index) =>
    index === 0 ? section : ["", ...section]
  ).map((line) => line.trimEnd()).join("\n");
  return appendFooter(rebuilt, terminal, width);
}

/** Append the "drill into any command" pointer as a trailing footer line, set
 * off by a blank line from the examples above it. */
function appendFooter(
  help: string,
  terminal: TerminalContext,
  width: number,
): string {
  const note = "Run `discern <command> --help` for detail on any command.";
  const body = help.replace(/\n+$/, "");
  const footer = wrapText(note, width, "", { breakLongWords: true })
    .map((line) => terminal.role(line, "muted").trimEnd())
    .join("\n");
  return `${body}\n\n${footer}\n`;
}
